    if (core_id == 3) {
        // Writer: enqueue via memory-mapped IPR_EAST_ADDR
        for (int iter = 0; iter < NUM_ITER; iter++) {
            enqueue(write_fifo_3to2, values_to_write_3[0]);
            enqueue(write_fifo_3to1, values_to_write_3[0]);
            uint32_t val_1_0 = dequeue(read_fifo_3from2);
            uint32_t val_2_0 = dequeue(read_fifo_3from1);

            enqueue(write_fifo_3to2, values_to_write_3[1]);
            enqueue(write_fifo_3to1, values_to_write_3[1]);
            uint32_t val_1_1 = dequeue(read_fifo_3from2);
            uint32_t val_2_1 = dequeue(read_fifo_3from1);

            enqueue(write_fifo_3to2, values_to_write_3[2]);
            enqueue(write_fifo_3to1, values_to_write_3[2]);
            uint32_t val_1_2 = dequeue(read_fifo_3from2);
            uint32_t val_2_2 = dequeue(read_fifo_3from1);

            enqueue(write_fifo_3to2, values_to_write_3[3]);
            enqueue(write_fifo_3to1, values_to_write_3[3]);
            uint32_t val_1_3 = dequeue(read_fifo_3from2);
            uint32_t val_2_3 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[4]);
            enqueue(write_fifo_3to1, values_to_write_3[4]);
            uint32_t val_1_4 = dequeue(read_fifo_3from2);
            uint32_t val_2_4 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[5]);
            enqueue(write_fifo_3to1, values_to_write_3[5]);
            uint32_t val_1_5 = dequeue(read_fifo_3from2);
            uint32_t val_2_5 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[6]);
            enqueue(write_fifo_3to1, values_to_write_3[6]);
            uint32_t val_1_6 = dequeue(read_fifo_3from2);
            uint32_t val_2_6 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[7]);
            enqueue(write_fifo_3to1, values_to_write_3[7]);
            uint32_t val_1_7 = dequeue(read_fifo_3from2);
            uint32_t val_2_7 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[8]);
            enqueue(write_fifo_3to1, values_to_write_3[8]);
            uint32_t val_1_8 = dequeue(read_fifo_3from2);
            uint32_t val_2_8 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[9]);
            enqueue(write_fifo_3to1, values_to_write_3[9]);
            uint32_t val_1_9 = dequeue(read_fifo_3from2);
            uint32_t val_2_9 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[10]);
            enqueue(write_fifo_3to1, values_to_write_3[10]);
            uint32_t val_1_10 = dequeue(read_fifo_3from2);
            uint32_t val_2_10 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[11]);
            enqueue(write_fifo_3to1, values_to_write_3[11]);
            uint32_t val_1_11 = dequeue(read_fifo_3from2);
            uint32_t val_2_11 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[12]);
            enqueue(write_fifo_3to1, values_to_write_3[12]);
            uint32_t val_1_12 = dequeue(read_fifo_3from2);
            uint32_t val_2_12 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[13]);
            enqueue(write_fifo_3to1, values_to_write_3[13]);
            uint32_t val_1_13 = dequeue(read_fifo_3from2);
            uint32_t val_2_13 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[14]);
            enqueue(write_fifo_3to1, values_to_write_3[14]);
            uint32_t val_1_14 = dequeue(read_fifo_3from2);
            uint32_t val_2_14 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[15]);
            enqueue(write_fifo_3to1, values_to_write_3[15]);
            uint32_t val_1_15 = dequeue(read_fifo_3from2);
            uint32_t val_2_15 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[16]);
            enqueue(write_fifo_3to1, values_to_write_3[16]);
            uint32_t val_1_16 = dequeue(read_fifo_3from2);
            uint32_t val_2_16 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[17]);
            enqueue(write_fifo_3to1, values_to_write_3[17]);
            uint32_t val_1_17 = dequeue(read_fifo_3from2);
            uint32_t val_2_17 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[18]);
            enqueue(write_fifo_3to1, values_to_write_3[18]);
            uint32_t val_1_18 = dequeue(read_fifo_3from2);
            uint32_t val_2_18 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[19]);
            enqueue(write_fifo_3to1, values_to_write_3[19]);
            uint32_t val_1_19 = dequeue(read_fifo_3from2);
            uint32_t val_2_19 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[20]);
            enqueue(write_fifo_3to1, values_to_write_3[20]);
            uint32_t val_1_20 = dequeue(read_fifo_3from2);
            uint32_t val_2_20 = dequeue(read_fifo_3from1);

            enqueue(write_fifo_3to2, values_to_write_3[21]);
            enqueue(write_fifo_3to1, values_to_write_3[21]);
            uint32_t val_1_21 = dequeue(read_fifo_3from2);
            uint32_t val_2_21 = dequeue(read_fifo_3from1);

            enqueue(write_fifo_3to2, values_to_write_3[22]);
            enqueue(write_fifo_3to1, values_to_write_3[22]);
            uint32_t val_1_22 = dequeue(read_fifo_3from2);
            uint32_t val_2_22 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[23]);
            enqueue(write_fifo_3to1, values_to_write_3[23]);
            uint32_t val_1_23 = dequeue(read_fifo_3from2);
            uint32_t val_2_23 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[24]);
            enqueue(write_fifo_3to1, values_to_write_3[24]);
            uint32_t val_1_24 = dequeue(read_fifo_3from2);
            uint32_t val_2_24 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[25]);
            enqueue(write_fifo_3to1, values_to_write_3[25]);
            uint32_t val_1_25 = dequeue(read_fifo_3from2);
            uint32_t val_2_25 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[26]);
            enqueue(write_fifo_3to1, values_to_write_3[26]);
            uint32_t val_1_26 = dequeue(read_fifo_3from2);
            uint32_t val_2_26 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[27]);
            enqueue(write_fifo_3to1, values_to_write_3[27]);
            uint32_t val_1_27 = dequeue(read_fifo_3from2);
            uint32_t val_2_27 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[28]);
            enqueue(write_fifo_3to1, values_to_write_3[28]);
            uint32_t val_1_28 = dequeue(read_fifo_3from2);
            uint32_t val_2_28 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[29]);
            enqueue(write_fifo_3to1, values_to_write_3[29]);
            uint32_t val_1_29 = dequeue(read_fifo_3from2);
            uint32_t val_2_29 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[30]);
            enqueue(write_fifo_3to1, values_to_write_3[30]);
            uint32_t val_1_30 = dequeue(read_fifo_3from2);
            uint32_t val_2_30 = dequeue(read_fifo_3from1);
            enqueue(write_fifo_3to2, values_to_write_3[31]);
            enqueue(write_fifo_3to1, values_to_write_3[31]);
            uint32_t val_1_31 = dequeue(read_fifo_3from2);
            uint32_t val_2_31 = dequeue(read_fifo_3from1);
        }
    }
