################################################################################
#       Setting dont_touch and dont_use preserve setting
################################################################################
catch {set_db base_cell:BHDBWP16P90 .dont_use true}
catch {set_db base_cell:BUFFD20BWP16P90 .dont_use true}
catch {set_db base_cell:BUFFD24BWP16P90 .dont_use true}
catch {set_db base_cell:BUFFSKND20BWP16P90 .dont_use true}
catch {set_db base_cell:BUFFSKND24BWP16P90 .dont_use true}
catch {set_db base_cell:BUFFSKPD20BWP16P90 .dont_use true}
catch {set_db base_cell:BUFFSKPD24BWP16P90 .dont_use true}
catch {set_db base_cell:BUFTD20BWP16P90 .dont_use true}
catch {set_db base_cell:BUFTD24BWP16P90 .dont_use true}
catch {set_db base_cell:CKBD20BWP16P90 .dont_use true}
catch {set_db base_cell:CKBD24BWP16P90 .dont_use true}
catch {set_db base_cell:CKLHQD20BWP16P90 .dont_use true}
catch {set_db base_cell:CKLHQD24BWP16P90 .dont_use true}
catch {set_db base_cell:CKLNQD20BWP16P90 .dont_use true}
catch {set_db base_cell:CKLNQD24BWP16P90 .dont_use true}
catch {set_db base_cell:CKLNQOPTBBD20BWP16P90 .dont_use true}
catch {set_db base_cell:CKLNQOPTBBD24BWP16P90 .dont_use true}
catch {set_db base_cell:CKND20BWP16P90 .dont_use true}
catch {set_db base_cell:CKND24BWP16P90 .dont_use true}
catch {set_db base_cell:DCCKBD20BWP16P90 .dont_use true}
catch {set_db base_cell:DCCKBD24BWP16P90 .dont_use true}
catch {set_db base_cell:DCCKND20BWP16P90 .dont_use true}
catch {set_db base_cell:DCCKND24BWP16P90 .dont_use true}
catch {set_db base_cell:GAN2MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GAN2MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GAOI21MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GAOI21MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GAOI22MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GAOI22MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GBUFFMCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GBUFFMCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GBUFFMCOD3BWP16P90 .dont_use true}
catch {set_db base_cell:GBUFFMCOD4BWP16P90 .dont_use true}
catch {set_db base_cell:GBUFFMCOD8BWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP10MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP11MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP12MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP1MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP2MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP3MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP4MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP5MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP6MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP8MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDCAP9MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GDFCNQMCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GDFQMCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GFILL10MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GFILL11MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GFILL12MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GFILL1MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GFILL2MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GFILL3MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GFILL4MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GFILL5MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GFILL6MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GFILL8MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GFILL9MCOBWP16P90 .dont_use true}
catch {set_db base_cell:GINVMCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GINVMCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GINVMCOD3BWP16P90 .dont_use true}
catch {set_db base_cell:GINVMCOD4BWP16P90 .dont_use true}
catch {set_db base_cell:GINVMCOD8BWP16P90 .dont_use true}
catch {set_db base_cell:GMUX2MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GMUX2MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GMUX2NMCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GMUX2NMCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GND2MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GND2MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GND3MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GND3MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GNR2MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GNR2MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GNR3MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GNR3MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GOAI21MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GOAI21MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GOR2MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GOR2MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GSDFCNQMCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GSDFQMCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GTIEHMCOBWP16P90 .dont_use true}
catch {set_db base_cell:GTIELMCOBWP16P90 .dont_use true}
catch {set_db base_cell:GXNR2MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GXNR2MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:GXOR2MCOD1BWP16P90 .dont_use true}
catch {set_db base_cell:GXOR2MCOD2BWP16P90 .dont_use true}
catch {set_db base_cell:INVD20BWP16P90 .dont_use true}
catch {set_db base_cell:INVD24BWP16P90 .dont_use true}
catch {set_db base_cell:INVSKND20BWP16P90 .dont_use true}
catch {set_db base_cell:INVSKND24BWP16P90 .dont_use true}
catch {set_db base_cell:INVSKPD20BWP16P90 .dont_use true}
catch {set_db base_cell:INVSKPD24BWP16P90 .dont_use true}
catch {set_db base_cell:ND2D20BWP16P90 .dont_use true}
catch {set_db base_cell:ND2D24BWP16P90 .dont_use true}
catch {set_db base_cell:ND2SKNBD20BWP16P90 .dont_use true}
catch {set_db base_cell:ND2SKNBD24BWP16P90 .dont_use true}
catch {set_db base_cell:ND2SKND20BWP16P90 .dont_use true}
catch {set_db base_cell:ND2SKND24BWP16P90 .dont_use true}
catch {set_db base_cell:NR2D20BWP16P90 .dont_use true}
catch {set_db base_cell:NR2D24BWP16P90 .dont_use true}
catch {set_db base_cell:NR2SKPBD20BWP16P90 .dont_use true}
catch {set_db base_cell:NR2SKPBD24BWP16P90 .dont_use true}
catch {set_db base_cell:NR2SKPD20BWP16P90 .dont_use true}
catch {set_db base_cell:NR2SKPD24BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQND0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQND1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQND2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQNOPTBBD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQNOPTBBD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQNOPTBBD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQOPTBBD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQOPTBBD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQOPTBBD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCNQOPTBBD8BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCSNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCSNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCSNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFCSNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKCNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKCNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKCNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKCNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKCSNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKCSNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKCSNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKCSNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKSNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKSNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKSNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFKSNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFMQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFMQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFMQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFMQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCNQND0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCNQND1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCNQND2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCSNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCSNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCSNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNCSNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNQND0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNQND1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNQND2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNQND4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNSNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNSNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNSNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNSNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNSNQND0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNSNQND1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFNSNQND2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQND0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQND1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQND2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQND4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQNOPTBBD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQNOPTBBD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQNOPTBBD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQOPTBBD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQOPTBBD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQOPTBBD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFQOPTBBD8BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQND0BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQND1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQND2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQNOPTBBD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQNOPTBBD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQNOPTBBD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQOPTBBD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQOPTBBD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQOPTBBD4BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSNQOPTBBD8BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSYNCNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSYNCNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSYNCSNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSYNCSNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSYNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSYNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSYNSNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SDFSYNSNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SEDFCNQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SEDFCNQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SEDFCNQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SEDFCNQD4BWP16P90 .dont_use true}
catch {set_db base_cell:SEDFQD0BWP16P90 .dont_use true}
catch {set_db base_cell:SEDFQD1BWP16P90 .dont_use true}
catch {set_db base_cell:SEDFQD2BWP16P90 .dont_use true}
catch {set_db base_cell:SEDFQD4BWP16P90 .dont_use true}
catch {set_db base_cell:BHDBWP16P90LVT .dont_use true}
catch {set_db base_cell:BUFFD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:BUFFD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:BUFFSKND20BWP16P90LVT .dont_use true}
catch {set_db base_cell:BUFFSKND24BWP16P90LVT .dont_use true}
catch {set_db base_cell:BUFFSKPD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:BUFFSKPD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:BUFTD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:BUFTD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:CKBD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:CKBD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:CKLHQD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:CKLHQD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:CKLNQD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:CKLNQD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:CKLNQOPTBBD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:CKLNQOPTBBD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:CKND20BWP16P90LVT .dont_use true}
catch {set_db base_cell:CKND24BWP16P90LVT .dont_use true}
catch {set_db base_cell:DCCKBD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:DCCKBD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:DCCKND20BWP16P90LVT .dont_use true}
catch {set_db base_cell:DCCKND24BWP16P90LVT .dont_use true}
catch {set_db base_cell:GAN2MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GAN2MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GAOI21MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GAOI21MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GAOI22MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GAOI22MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GBUFFMCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GBUFFMCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GBUFFMCOD3BWP16P90LVT .dont_use true}
catch {set_db base_cell:GBUFFMCOD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:GBUFFMCOD8BWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP10MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP11MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP12MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP1MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP2MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP3MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP4MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP5MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP6MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP8MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDCAP9MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GDFCNQMCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GDFQMCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL10MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL11MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL12MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL1MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL2MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL3MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL4MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL5MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL6MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL8MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GFILL9MCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GINVMCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GINVMCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GINVMCOD3BWP16P90LVT .dont_use true}
catch {set_db base_cell:GINVMCOD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:GINVMCOD8BWP16P90LVT .dont_use true}
catch {set_db base_cell:GMUX2MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GMUX2MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GMUX2NMCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GMUX2NMCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GND2MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GND2MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GND3MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GND3MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GNR2MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GNR2MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GNR3MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GNR3MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GOAI21MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GOAI21MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GOR2MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GOR2MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GSDFCNQMCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GSDFQMCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GTIEHMCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GTIELMCOBWP16P90LVT .dont_use true}
catch {set_db base_cell:GXNR2MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GXNR2MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:GXOR2MCOD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:GXOR2MCOD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:INVD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:INVD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:INVSKND20BWP16P90LVT .dont_use true}
catch {set_db base_cell:INVSKND24BWP16P90LVT .dont_use true}
catch {set_db base_cell:INVSKPD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:INVSKPD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:ND2D20BWP16P90LVT .dont_use true}
catch {set_db base_cell:ND2D24BWP16P90LVT .dont_use true}
catch {set_db base_cell:ND2SKNBD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:ND2SKNBD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:ND2SKND20BWP16P90LVT .dont_use true}
catch {set_db base_cell:ND2SKND24BWP16P90LVT .dont_use true}
catch {set_db base_cell:NR2D20BWP16P90LVT .dont_use true}
catch {set_db base_cell:NR2D24BWP16P90LVT .dont_use true}
catch {set_db base_cell:NR2SKPBD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:NR2SKPBD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:NR2SKPD20BWP16P90LVT .dont_use true}
catch {set_db base_cell:NR2SKPD24BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQND0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQND1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQND2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQNOPTBBD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQNOPTBBD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQNOPTBBD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQOPTBBD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQOPTBBD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQOPTBBD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCNQOPTBBD8BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCSNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCSNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCSNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFCSNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKCNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKCNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKCNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKCNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKCSNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKCSNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKCSNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKCSNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKSNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKSNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKSNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFKSNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFMQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFMQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFMQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFMQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCNQND0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCNQND1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCNQND2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCSNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCSNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCSNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNCSNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNQND0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNQND1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNQND2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNQND4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNSNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNSNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNSNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNSNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNSNQND0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNSNQND1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFNSNQND2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQND0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQND1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQND2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQND4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQNOPTBBD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQNOPTBBD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQNOPTBBD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQOPTBBD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQOPTBBD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQOPTBBD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFQOPTBBD8BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQND0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQND1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQND2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQNOPTBBD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQNOPTBBD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQNOPTBBD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQOPTBBD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQOPTBBD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQOPTBBD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSNQOPTBBD8BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSYNCNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSYNCNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSYNCSNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSYNCSNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSYNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSYNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSYNSNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SDFSYNSNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SEDFCNQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SEDFCNQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SEDFCNQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SEDFCNQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:SEDFQD0BWP16P90LVT .dont_use true}
catch {set_db base_cell:SEDFQD1BWP16P90LVT .dont_use true}
catch {set_db base_cell:SEDFQD2BWP16P90LVT .dont_use true}
catch {set_db base_cell:SEDFQD4BWP16P90LVT .dont_use true}
catch {set_db base_cell:BHDBWP16P90 .dont_touch true}
catch {set_db base_cell:BUFFD20BWP16P90 .dont_touch true}
catch {set_db base_cell:BUFFD24BWP16P90 .dont_touch true}
catch {set_db base_cell:BUFFSKND20BWP16P90 .dont_touch true}
catch {set_db base_cell:BUFFSKND24BWP16P90 .dont_touch true}
catch {set_db base_cell:BUFFSKPD20BWP16P90 .dont_touch true}
catch {set_db base_cell:BUFFSKPD24BWP16P90 .dont_touch true}
catch {set_db base_cell:BUFTD20BWP16P90 .dont_touch true}
catch {set_db base_cell:BUFTD24BWP16P90 .dont_touch true}
catch {set_db base_cell:CKBD20BWP16P90 .dont_touch true}
catch {set_db base_cell:CKBD24BWP16P90 .dont_touch true}
catch {set_db base_cell:CKLHQD20BWP16P90 .dont_touch true}
catch {set_db base_cell:CKLHQD24BWP16P90 .dont_touch true}
catch {set_db base_cell:CKLNQD20BWP16P90 .dont_touch true}
catch {set_db base_cell:CKLNQD24BWP16P90 .dont_touch true}
catch {set_db base_cell:CKLNQOPTBBD20BWP16P90 .dont_touch true}
catch {set_db base_cell:CKLNQOPTBBD24BWP16P90 .dont_touch true}
catch {set_db base_cell:CKND20BWP16P90 .dont_touch true}
catch {set_db base_cell:CKND24BWP16P90 .dont_touch true}
catch {set_db base_cell:DCCKBD20BWP16P90 .dont_touch true}
catch {set_db base_cell:DCCKBD24BWP16P90 .dont_touch true}
catch {set_db base_cell:DCCKND20BWP16P90 .dont_touch true}
catch {set_db base_cell:DCCKND24BWP16P90 .dont_touch true}
catch {set_db base_cell:GAN2MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GAN2MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GAOI21MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GAOI21MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GAOI22MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GAOI22MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GBUFFMCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GBUFFMCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GBUFFMCOD3BWP16P90 .dont_touch true}
catch {set_db base_cell:GBUFFMCOD4BWP16P90 .dont_touch true}
catch {set_db base_cell:GBUFFMCOD8BWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP10MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP11MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP12MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP1MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP2MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP3MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP4MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP5MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP6MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP8MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDCAP9MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GDFCNQMCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GDFQMCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL10MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL11MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL12MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL1MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL2MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL3MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL4MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL5MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL6MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL8MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GFILL9MCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GINVMCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GINVMCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GINVMCOD3BWP16P90 .dont_touch true}
catch {set_db base_cell:GINVMCOD4BWP16P90 .dont_touch true}
catch {set_db base_cell:GINVMCOD8BWP16P90 .dont_touch true}
catch {set_db base_cell:GMUX2MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GMUX2MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GMUX2NMCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GMUX2NMCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GND2MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GND2MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GND3MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GND3MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GNR2MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GNR2MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GNR3MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GNR3MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GOAI21MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GOAI21MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GOR2MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GOR2MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GSDFCNQMCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GSDFQMCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GTIEHMCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GTIELMCOBWP16P90 .dont_touch true}
catch {set_db base_cell:GXNR2MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GXNR2MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:GXOR2MCOD1BWP16P90 .dont_touch true}
catch {set_db base_cell:GXOR2MCOD2BWP16P90 .dont_touch true}
catch {set_db base_cell:INVD20BWP16P90 .dont_touch true}
catch {set_db base_cell:INVD24BWP16P90 .dont_touch true}
catch {set_db base_cell:INVSKND20BWP16P90 .dont_touch true}
catch {set_db base_cell:INVSKND24BWP16P90 .dont_touch true}
catch {set_db base_cell:INVSKPD20BWP16P90 .dont_touch true}
catch {set_db base_cell:INVSKPD24BWP16P90 .dont_touch true}
catch {set_db base_cell:ND2D20BWP16P90 .dont_touch true}
catch {set_db base_cell:ND2D24BWP16P90 .dont_touch true}
catch {set_db base_cell:ND2SKNBD20BWP16P90 .dont_touch true}
catch {set_db base_cell:ND2SKNBD24BWP16P90 .dont_touch true}
catch {set_db base_cell:ND2SKND20BWP16P90 .dont_touch true}
catch {set_db base_cell:ND2SKND24BWP16P90 .dont_touch true}
catch {set_db base_cell:NR2D20BWP16P90 .dont_touch true}
catch {set_db base_cell:NR2D24BWP16P90 .dont_touch true}
catch {set_db base_cell:NR2SKPBD20BWP16P90 .dont_touch true}
catch {set_db base_cell:NR2SKPBD24BWP16P90 .dont_touch true}
catch {set_db base_cell:NR2SKPD20BWP16P90 .dont_touch true}
catch {set_db base_cell:NR2SKPD24BWP16P90 .dont_touch true}
catch {set_db base_cell:BHDBWP16P90LVT .dont_touch true}
catch {set_db base_cell:BUFFD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:BUFFD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:BUFFSKND20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:BUFFSKND24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:BUFFSKPD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:BUFFSKPD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:BUFTD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:BUFTD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:CKBD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:CKBD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:CKLHQD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:CKLHQD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:CKLNQD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:CKLNQD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:CKLNQOPTBBD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:CKLNQOPTBBD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:CKND20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:CKND24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:DCCKBD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:DCCKBD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:DCCKND20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:DCCKND24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GAN2MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GAN2MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GAOI21MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GAOI21MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GAOI22MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GAOI22MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GBUFFMCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GBUFFMCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GBUFFMCOD3BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GBUFFMCOD4BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GBUFFMCOD8BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP10MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP11MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP12MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP1MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP2MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP3MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP4MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP5MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP6MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP8MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDCAP9MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDFCNQMCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GDFQMCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL10MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL11MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL12MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL1MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL2MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL3MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL4MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL5MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL6MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL8MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GFILL9MCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GINVMCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GINVMCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GINVMCOD3BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GINVMCOD4BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GINVMCOD8BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GMUX2MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GMUX2MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GMUX2NMCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GMUX2NMCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GND2MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GND2MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GND3MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GND3MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GNR2MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GNR2MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GNR3MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GNR3MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GOAI21MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GOAI21MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GOR2MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GOR2MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GSDFCNQMCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GSDFQMCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GTIEHMCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GTIELMCOBWP16P90LVT .dont_touch true}
catch {set_db base_cell:GXNR2MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GXNR2MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GXOR2MCOD1BWP16P90LVT .dont_touch true}
catch {set_db base_cell:GXOR2MCOD2BWP16P90LVT .dont_touch true}
catch {set_db base_cell:INVD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:INVD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:INVSKND20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:INVSKND24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:INVSKPD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:INVSKPD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:ND2D20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:ND2D24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:ND2SKNBD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:ND2SKNBD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:ND2SKND20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:ND2SKND24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:NR2D20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:NR2D24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:NR2SKPBD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:NR2SKPBD24BWP16P90LVT .dont_touch true}
catch {set_db base_cell:NR2SKPD20BWP16P90LVT .dont_touch true}
catch {set_db base_cell:NR2SKPD24BWP16P90LVT .dont_touch true}
catch {set_db hinst:ipr_cntrl/async_fifo_i_wptr_full_inst/RC_CG_HIER_INST0 .dont_touch_hports true}
