
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Jun 18 2025 13:22:17 UTC (Jun 18 2025 13:22:17 UTC)

// Verification Directory fv/ipr_cntrl 

module rptr_empty_ADDRSIZE4(rclk, rrst_n, rinc, rq2_wptr, rempty,
     arempty, raddr, rptr);
  input rclk, rrst_n, rinc;
  input [4:0] rq2_wptr;
  output rempty, arempty;
  output [3:0] raddr;
  output [4:0] rptr;
  wire rclk, rrst_n, rinc;
  wire [4:0] rq2_wptr;
  wire rempty, arempty;
  wire [3:0] raddr;
  wire [4:0] rptr;
  wire [4:0] rbinnext;
  wire [4:0] rgraynext;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  XOR2D0BWP16P90 g259__2398(.A1 (rbinnext[3]), .A2 (rbinnext[4]), .Z
       (rgraynext[3]));
  XOR2D0BWP16P90 g260__5107(.A1 (rbinnext[2]), .A2 (rbinnext[3]), .Z
       (rgraynext[2]));
  XOR2D0BWP16P90 g261__6260(.A1 (rptr[4]), .A2 (n_11), .Z
       (rbinnext[4]));
  HA1D0BWP16P90 g262__4319(.A (raddr[3]), .B (n_10), .CO (n_11), .S
       (rbinnext[3]));
  XOR2D0BWP16P90 g263__8428(.A1 (rbinnext[1]), .A2 (rbinnext[2]), .Z
       (rgraynext[1]));
  HA1D0BWP16P90 g264__5526(.A (raddr[2]), .B (n_9), .CO (n_10), .S
       (rbinnext[2]));
  XOR2D0BWP16P90 g265__6783(.A1 (rbinnext[0]), .A2 (rbinnext[1]), .Z
       (rgraynext[0]));
  HA1D0BWP16P90 g266__3680(.A (raddr[1]), .B (n_8), .CO (n_9), .S
       (rbinnext[1]));
  HA1D0BWP16P90 g267__1617(.A (raddr[0]), .B (n_7), .CO (n_8), .S
       (rbinnext[0]));
  INR2D0BWP16P90 g268__2802(.A1 (rinc), .B1 (rempty), .ZN (n_7));
  DFSNQD0BWP16P90 rempty_reg(.SDN (rrst_n), .CP (rclk), .D (n_6), .Q
       (rempty));
  NR4D0BWP16P90 g295__1705(.A1 (n_5), .A2 (n_3), .A3 (n_2), .A4 (n_0),
       .ZN (n_6));
  ND2D0BWP16P90 g296__5122(.A1 (n_4), .A2 (n_1), .ZN (n_5));
  XNR2D0BWP16P90 g297__8246(.A1 (rq2_wptr[3]), .A2 (rgraynext[3]), .ZN
       (n_4));
  XOR2D0BWP16P90 g298__7098(.A1 (rq2_wptr[2]), .A2 (rgraynext[2]), .Z
       (n_3));
  XOR2D0BWP16P90 g299__6131(.A1 (rq2_wptr[4]), .A2 (rbinnext[4]), .Z
       (n_2));
  XNR2D0BWP16P90 g300__1881(.A1 (rq2_wptr[1]), .A2 (rgraynext[1]), .ZN
       (n_1));
  XOR2D0BWP16P90 g301__5115(.A1 (rq2_wptr[0]), .A2 (rgraynext[0]), .Z
       (n_0));
  DFCNQD0BWP16P90 \rbin_reg[1] (.CDN (rrst_n), .CP (rclk), .D
       (rbinnext[1]), .Q (raddr[1]));
  DFCNQD0BWP16P90 \rbin_reg[2] (.CDN (rrst_n), .CP (rclk), .D
       (rbinnext[2]), .Q (raddr[2]));
  DFCNQD0BWP16P90 \rbin_reg[3] (.CDN (rrst_n), .CP (rclk), .D
       (rbinnext[3]), .Q (raddr[3]));
  DFCNQD0BWP16P90 \rbin_reg[4] (.CDN (rrst_n), .CP (rclk), .D
       (rbinnext[4]), .Q (rptr[4]));
  DFCNQD0BWP16P90 \rbin_reg[0] (.CDN (rrst_n), .CP (rclk), .D
       (rbinnext[0]), .Q (raddr[0]));
  DFCNQD0BWP16P90 \rptr_reg[0] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[0]), .Q (rptr[0]));
  DFCNQD0BWP16P90 \rptr_reg[3] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[3]), .Q (rptr[3]));
  DFCNQD0BWP16P90 \rptr_reg[1] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[1]), .Q (rptr[1]));
  DFCNQD0BWP16P90 \rptr_reg[2] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[2]), .Q (rptr[2]));
endmodule

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module wptr_full_ADDRSIZE4(wclk, wrst_n, winc, wq2_rptr, wfull, awfull,
     waddr, wptr);
  input wclk, wrst_n, winc;
  input [4:0] wq2_rptr;
  output wfull, awfull;
  output [3:0] waddr;
  output [4:0] wptr;
  wire wclk, wrst_n, winc;
  wire [4:0] wq2_rptr;
  wire wfull, awfull;
  wire [3:0] waddr;
  wire [4:0] wptr;
  wire [4:0] wgraynext;
  wire [4:0] wbinnext;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_12, rc_gclk;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_12), .ck_in (wclk), .ck_out
       (rc_gclk), .test (1'b0));
  DFCNQD0BWP16P90 \wptr_reg[3] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[3]), .Q (wptr[3]));
  XOR2D0BWP16P90 g294__7482(.A1 (wbinnext[4]), .A2 (wbinnext[3]), .Z
       (wgraynext[3]));
  DFCNQD0BWP16P90 \wptr_reg[2] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[2]), .Q (wptr[2]));
  XOR2D0BWP16P90 g296__4733(.A1 (wbinnext[3]), .A2 (wbinnext[2]), .Z
       (wgraynext[2]));
  XOR2D0BWP16P90 g297__6161(.A1 (n_10), .A2 (wptr[4]), .Z
       (wbinnext[4]));
  HA1D0BWP16P90 g298__9315(.A (waddr[3]), .B (n_9), .CO (n_10), .S
       (wbinnext[3]));
  DFCNQD0BWP16P90 \wptr_reg[1] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[1]), .Q (wptr[1]));
  XOR2D0BWP16P90 g300__9945(.A1 (wbinnext[2]), .A2 (wbinnext[1]), .Z
       (wgraynext[1]));
  HA1D0BWP16P90 g301__2883(.A (waddr[2]), .B (n_8), .CO (n_9), .S
       (wbinnext[2]));
  DFCNQD0BWP16P90 \wptr_reg[0] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[0]), .Q (wptr[0]));
  XOR2D0BWP16P90 g303__2346(.A1 (wbinnext[1]), .A2 (wbinnext[0]), .Z
       (wgraynext[0]));
  HA1D0BWP16P90 g304__1666(.A (waddr[1]), .B (n_7), .CO (n_8), .S
       (wbinnext[1]));
  HA1D0BWP16P90 g305__7410(.A (waddr[0]), .B (n_12), .CO (n_7), .S
       (wbinnext[0]));
  INR2D0BWP16P90 g306__6417(.A1 (winc), .B1 (wfull), .ZN (n_12));
  DFCNQD0BWP16P90 wfull_reg(.CDN (wrst_n), .CP (wclk), .D (n_6), .Q
       (wfull));
  NR4D0BWP16P90 g307__5477(.A1 (n_5), .A2 (n_3), .A3 (n_2), .A4 (n_0),
       .ZN (n_6));
  ND2D0BWP16P90 g308__2398(.A1 (n_4), .A2 (n_1), .ZN (n_5));
  XOR2D0BWP16P90 g309__5107(.A1 (wq2_rptr[3]), .A2 (wgraynext[3]), .Z
       (n_4));
  XOR2D0BWP16P90 g310__6260(.A1 (wq2_rptr[2]), .A2 (wgraynext[2]), .Z
       (n_3));
  XNR2D0BWP16P90 g311__4319(.A1 (wq2_rptr[4]), .A2 (wbinnext[4]), .ZN
       (n_2));
  XNR2D0BWP16P90 g312__8428(.A1 (wq2_rptr[1]), .A2 (wgraynext[1]), .ZN
       (n_1));
  XOR2D0BWP16P90 g313__5526(.A1 (wq2_rptr[0]), .A2 (wgraynext[0]), .Z
       (n_0));
  DFCNQD0BWP16P90 \wbin_reg[3] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[3]), .Q (waddr[3]));
  DFCNQD0BWP16P90 \wbin_reg[2] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[2]), .Q (waddr[2]));
  DFCNQD0BWP16P90 \wbin_reg[0] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[0]), .Q (waddr[0]));
  DFCNQD0BWP16P90 \wbin_reg[4] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[4]), .Q (wptr[4]));
  DFCNQD0BWP16P90 \wbin_reg[1] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[1]), .Q (waddr[1]));
endmodule

module ipr_cntrl(w_clk, w_rst_n, r_clk, r_rst_n, error_flag, we, re,
     rdata, wdata, waddr, raddr, fifo_full, read_if_req, read_if_addr,
     read_if_be, read_if_we, read_if_gnt, read_if_rvalid,
     read_if_rdata, write_if_req, write_if_addr, write_if_wdata,
     write_if_we, write_if_be, write_if_gnt, write_if_rvalid,
     write_if_rdata);
  input w_clk, w_rst_n, r_clk, r_rst_n, read_if_req, read_if_we,
       write_if_req, write_if_we;
  input [7:0] rdata;
  input [31:0] read_if_addr, write_if_addr, write_if_wdata;
  input [3:0] read_if_be, write_if_be;
  output error_flag, we, re, fifo_full, read_if_gnt, read_if_rvalid,
       write_if_gnt, write_if_rvalid;
  output [7:0] wdata;
  output [3:0] waddr, raddr;
  output [31:0] read_if_rdata, write_if_rdata;
  wire w_clk, w_rst_n, r_clk, r_rst_n, read_if_req, read_if_we,
       write_if_req, write_if_we;
  wire [7:0] rdata;
  wire [31:0] read_if_addr, write_if_addr, write_if_wdata;
  wire [3:0] read_if_be, write_if_be;
  wire error_flag, we, re, fifo_full, read_if_gnt, read_if_rvalid,
       write_if_gnt, write_if_rvalid;
  wire [7:0] wdata;
  wire [3:0] waddr, raddr;
  wire [31:0] read_if_rdata, write_if_rdata;
  wire [4:0] async_fifo_i_rq2_wptr;
  wire [4:0] async_fifo_i_rptr;
  wire [4:0] async_fifo_i_wq2_rptr;
  wire [4:0] async_fifo_i_wptr;
  wire [4:0] async_fifo_i_sync_r2w_inst_wq1_rptr;
  wire [4:0] async_fifo_i_sync_w2r_inst_rq1_wptr;
  wire async_fifo_i_n_8, async_fifo_i_n_10, fifo_empty;
  assign write_if_rdata[0] = 1'b0;
  assign write_if_rdata[1] = 1'b0;
  assign write_if_rdata[2] = 1'b0;
  assign write_if_rdata[3] = 1'b0;
  assign write_if_rdata[4] = 1'b0;
  assign write_if_rdata[5] = 1'b0;
  assign write_if_rdata[6] = 1'b0;
  assign write_if_rdata[7] = 1'b0;
  assign write_if_rdata[8] = 1'b0;
  assign write_if_rdata[9] = 1'b0;
  assign write_if_rdata[10] = 1'b0;
  assign write_if_rdata[11] = 1'b0;
  assign write_if_rdata[12] = 1'b0;
  assign write_if_rdata[13] = 1'b0;
  assign write_if_rdata[14] = 1'b0;
  assign write_if_rdata[15] = 1'b0;
  assign write_if_rdata[16] = 1'b0;
  assign write_if_rdata[17] = 1'b0;
  assign write_if_rdata[18] = 1'b0;
  assign write_if_rdata[19] = 1'b0;
  assign write_if_rdata[20] = 1'b0;
  assign write_if_rdata[21] = 1'b0;
  assign write_if_rdata[22] = 1'b0;
  assign write_if_rdata[23] = 1'b0;
  assign write_if_rdata[24] = 1'b0;
  assign write_if_rdata[25] = 1'b0;
  assign write_if_rdata[26] = 1'b0;
  assign write_if_rdata[27] = 1'b0;
  assign write_if_rdata[28] = 1'b0;
  assign write_if_rdata[29] = 1'b0;
  assign write_if_rdata[30] = 1'b0;
  assign write_if_rdata[31] = 1'b0;
  assign read_if_rdata[0] = rdata[0];
  assign read_if_rdata[1] = rdata[1];
  assign read_if_rdata[2] = rdata[2];
  assign read_if_rdata[3] = rdata[3];
  assign read_if_rdata[4] = rdata[4];
  assign read_if_rdata[5] = rdata[5];
  assign read_if_rdata[6] = rdata[6];
  assign read_if_rdata[7] = rdata[7];
  assign read_if_rdata[8] = 1'b0;
  assign read_if_rdata[9] = 1'b0;
  assign read_if_rdata[10] = 1'b0;
  assign read_if_rdata[11] = 1'b0;
  assign read_if_rdata[12] = 1'b0;
  assign read_if_rdata[13] = 1'b0;
  assign read_if_rdata[14] = 1'b0;
  assign read_if_rdata[15] = 1'b0;
  assign read_if_rdata[16] = 1'b0;
  assign read_if_rdata[17] = 1'b0;
  assign read_if_rdata[18] = 1'b0;
  assign read_if_rdata[19] = 1'b0;
  assign read_if_rdata[20] = 1'b0;
  assign read_if_rdata[21] = 1'b0;
  assign read_if_rdata[22] = 1'b0;
  assign read_if_rdata[23] = 1'b0;
  assign read_if_rdata[24] = 1'b0;
  assign read_if_rdata[25] = 1'b0;
  assign read_if_rdata[26] = 1'b0;
  assign read_if_rdata[27] = 1'b0;
  assign read_if_rdata[28] = 1'b0;
  assign read_if_rdata[29] = 1'b0;
  assign read_if_rdata[30] = 1'b0;
  assign read_if_rdata[31] = 1'b0;
  assign wdata[0] = write_if_wdata[0];
  assign wdata[1] = write_if_wdata[1];
  assign wdata[2] = write_if_wdata[2];
  assign wdata[3] = write_if_wdata[3];
  assign wdata[4] = write_if_wdata[4];
  assign wdata[5] = write_if_wdata[5];
  assign wdata[6] = write_if_wdata[6];
  assign wdata[7] = write_if_wdata[7];
  assign error_flag = 1'b0;
  rptr_empty_ADDRSIZE4 async_fifo_i_rptr_empty_inst(.rclk (r_clk),
       .rrst_n (r_rst_n), .rinc (re), .rq2_wptr
       (async_fifo_i_rq2_wptr), .rempty (fifo_empty), .arempty
       (async_fifo_i_n_10), .raddr (raddr), .rptr (async_fifo_i_rptr));
  wptr_full_ADDRSIZE4 async_fifo_i_wptr_full_inst(.wclk (w_clk),
       .wrst_n (w_rst_n), .winc (we), .wq2_rptr
       (async_fifo_i_wq2_rptr), .wfull (fifo_full), .awfull
       (async_fifo_i_n_8), .waddr (waddr), .wptr (async_fifo_i_wptr));
  IINR4D0BWP16P90 g209__6783(.A1 (write_if_req), .A2 (write_if_we), .B1
       (fifo_full), .B2 (write_if_rvalid), .ZN (write_if_gnt));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[4] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[4]), .Q
       (async_fifo_i_wq2_rptr[4]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[3] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[3]), .Q
       (async_fifo_i_wq2_rptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[2] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[2]), .Q
       (async_fifo_i_wq2_rptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[1] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[1]), .Q
       (async_fifo_i_wq2_rptr[1]));
  AN2D0BWP16P90 g214__3680(.A1 (write_if_req), .A2 (write_if_we), .Z
       (we));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[4] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[4]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[4]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[2] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[2]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[1] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[1]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[1]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[3] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[3]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[0] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[0]), .Q
       (async_fifo_i_wq2_rptr[0]));
  INR4D0BWP16P90 g210__1617(.A1 (read_if_req), .B1 (fifo_empty), .B2
       (read_if_rvalid), .B3 (read_if_we), .ZN (read_if_gnt));
  INR3D0BWP16P90 g211__2802(.A1 (read_if_rvalid), .B1
       (read_if_addr[3]), .B2 (read_if_addr[2]), .ZN (re));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[0] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[0]), .Q
       (async_fifo_i_rq2_wptr[0]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[4] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[4]), .Q
       (async_fifo_i_rq2_wptr[4]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[3] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[3]), .Q
       (async_fifo_i_rq2_wptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[2] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[2]), .Q
       (async_fifo_i_rq2_wptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[1] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[1]), .Q
       (async_fifo_i_rq2_wptr[1]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[2] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[2]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[1] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[1]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[1]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[4] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[4]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[4]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[3] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[3]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[0] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[0]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[0]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[0] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[0]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[0]));
  DFCNQD0BWP16P90 write_gnt_dly_reg(.CDN (w_rst_n), .CP (w_clk), .D
       (write_if_gnt), .Q (write_if_rvalid));
  DFCNQD0BWP16P90 read_gnt_dly_reg(.CDN (r_rst_n), .CP (r_clk), .D
       (read_if_gnt), .Q (read_if_rvalid));
endmodule

