
//input ports
add mapped point w_clk w_clk -type PI PI
add mapped point w_rst_n w_rst_n -type PI PI
add mapped point r_clk r_clk -type PI PI
add mapped point r_rst_n r_rst_n -type PI PI
add mapped point rdata[7] rdata[7] -type PI PI
add mapped point rdata[6] rdata[6] -type PI PI
add mapped point rdata[5] rdata[5] -type PI PI
add mapped point rdata[4] rdata[4] -type PI PI
add mapped point rdata[3] rdata[3] -type PI PI
add mapped point rdata[2] rdata[2] -type PI PI
add mapped point rdata[1] rdata[1] -type PI PI
add mapped point rdata[0] rdata[0] -type PI PI
add mapped point read_if.req read_if_req -type PI PI
add mapped point read_if.addr[31] read_if_addr[31] -type PI PI
add mapped point read_if.addr[30] read_if_addr[30] -type PI PI
add mapped point read_if.addr[29] read_if_addr[29] -type PI PI
add mapped point read_if.addr[28] read_if_addr[28] -type PI PI
add mapped point read_if.addr[27] read_if_addr[27] -type PI PI
add mapped point read_if.addr[26] read_if_addr[26] -type PI PI
add mapped point read_if.addr[25] read_if_addr[25] -type PI PI
add mapped point read_if.addr[24] read_if_addr[24] -type PI PI
add mapped point read_if.addr[23] read_if_addr[23] -type PI PI
add mapped point read_if.addr[22] read_if_addr[22] -type PI PI
add mapped point read_if.addr[21] read_if_addr[21] -type PI PI
add mapped point read_if.addr[20] read_if_addr[20] -type PI PI
add mapped point read_if.addr[19] read_if_addr[19] -type PI PI
add mapped point read_if.addr[18] read_if_addr[18] -type PI PI
add mapped point read_if.addr[17] read_if_addr[17] -type PI PI
add mapped point read_if.addr[16] read_if_addr[16] -type PI PI
add mapped point read_if.addr[15] read_if_addr[15] -type PI PI
add mapped point read_if.addr[14] read_if_addr[14] -type PI PI
add mapped point read_if.addr[13] read_if_addr[13] -type PI PI
add mapped point read_if.addr[12] read_if_addr[12] -type PI PI
add mapped point read_if.addr[11] read_if_addr[11] -type PI PI
add mapped point read_if.addr[10] read_if_addr[10] -type PI PI
add mapped point read_if.addr[9] read_if_addr[9] -type PI PI
add mapped point read_if.addr[8] read_if_addr[8] -type PI PI
add mapped point read_if.addr[7] read_if_addr[7] -type PI PI
add mapped point read_if.addr[6] read_if_addr[6] -type PI PI
add mapped point read_if.addr[5] read_if_addr[5] -type PI PI
add mapped point read_if.addr[4] read_if_addr[4] -type PI PI
add mapped point read_if.addr[3] read_if_addr[3] -type PI PI
add mapped point read_if.addr[2] read_if_addr[2] -type PI PI
add mapped point read_if.addr[1] read_if_addr[1] -type PI PI
add mapped point read_if.addr[0] read_if_addr[0] -type PI PI
add mapped point read_if.be[3] read_if_be[3] -type PI PI
add mapped point read_if.be[2] read_if_be[2] -type PI PI
add mapped point read_if.be[1] read_if_be[1] -type PI PI
add mapped point read_if.be[0] read_if_be[0] -type PI PI
add mapped point read_if.we read_if_we -type PI PI
add mapped point write_if.req write_if_req -type PI PI
add mapped point write_if.addr[31] write_if_addr[31] -type PI PI
add mapped point write_if.addr[30] write_if_addr[30] -type PI PI
add mapped point write_if.addr[29] write_if_addr[29] -type PI PI
add mapped point write_if.addr[28] write_if_addr[28] -type PI PI
add mapped point write_if.addr[27] write_if_addr[27] -type PI PI
add mapped point write_if.addr[26] write_if_addr[26] -type PI PI
add mapped point write_if.addr[25] write_if_addr[25] -type PI PI
add mapped point write_if.addr[24] write_if_addr[24] -type PI PI
add mapped point write_if.addr[23] write_if_addr[23] -type PI PI
add mapped point write_if.addr[22] write_if_addr[22] -type PI PI
add mapped point write_if.addr[21] write_if_addr[21] -type PI PI
add mapped point write_if.addr[20] write_if_addr[20] -type PI PI
add mapped point write_if.addr[19] write_if_addr[19] -type PI PI
add mapped point write_if.addr[18] write_if_addr[18] -type PI PI
add mapped point write_if.addr[17] write_if_addr[17] -type PI PI
add mapped point write_if.addr[16] write_if_addr[16] -type PI PI
add mapped point write_if.addr[15] write_if_addr[15] -type PI PI
add mapped point write_if.addr[14] write_if_addr[14] -type PI PI
add mapped point write_if.addr[13] write_if_addr[13] -type PI PI
add mapped point write_if.addr[12] write_if_addr[12] -type PI PI
add mapped point write_if.addr[11] write_if_addr[11] -type PI PI
add mapped point write_if.addr[10] write_if_addr[10] -type PI PI
add mapped point write_if.addr[9] write_if_addr[9] -type PI PI
add mapped point write_if.addr[8] write_if_addr[8] -type PI PI
add mapped point write_if.addr[7] write_if_addr[7] -type PI PI
add mapped point write_if.addr[6] write_if_addr[6] -type PI PI
add mapped point write_if.addr[5] write_if_addr[5] -type PI PI
add mapped point write_if.addr[4] write_if_addr[4] -type PI PI
add mapped point write_if.addr[3] write_if_addr[3] -type PI PI
add mapped point write_if.addr[2] write_if_addr[2] -type PI PI
add mapped point write_if.addr[1] write_if_addr[1] -type PI PI
add mapped point write_if.addr[0] write_if_addr[0] -type PI PI
add mapped point write_if.wdata[31] write_if_wdata[31] -type PI PI
add mapped point write_if.wdata[30] write_if_wdata[30] -type PI PI
add mapped point write_if.wdata[29] write_if_wdata[29] -type PI PI
add mapped point write_if.wdata[28] write_if_wdata[28] -type PI PI
add mapped point write_if.wdata[27] write_if_wdata[27] -type PI PI
add mapped point write_if.wdata[26] write_if_wdata[26] -type PI PI
add mapped point write_if.wdata[25] write_if_wdata[25] -type PI PI
add mapped point write_if.wdata[24] write_if_wdata[24] -type PI PI
add mapped point write_if.wdata[23] write_if_wdata[23] -type PI PI
add mapped point write_if.wdata[22] write_if_wdata[22] -type PI PI
add mapped point write_if.wdata[21] write_if_wdata[21] -type PI PI
add mapped point write_if.wdata[20] write_if_wdata[20] -type PI PI
add mapped point write_if.wdata[19] write_if_wdata[19] -type PI PI
add mapped point write_if.wdata[18] write_if_wdata[18] -type PI PI
add mapped point write_if.wdata[17] write_if_wdata[17] -type PI PI
add mapped point write_if.wdata[16] write_if_wdata[16] -type PI PI
add mapped point write_if.wdata[15] write_if_wdata[15] -type PI PI
add mapped point write_if.wdata[14] write_if_wdata[14] -type PI PI
add mapped point write_if.wdata[13] write_if_wdata[13] -type PI PI
add mapped point write_if.wdata[12] write_if_wdata[12] -type PI PI
add mapped point write_if.wdata[11] write_if_wdata[11] -type PI PI
add mapped point write_if.wdata[10] write_if_wdata[10] -type PI PI
add mapped point write_if.wdata[9] write_if_wdata[9] -type PI PI
add mapped point write_if.wdata[8] write_if_wdata[8] -type PI PI
add mapped point write_if.wdata[7] write_if_wdata[7] -type PI PI
add mapped point write_if.wdata[6] write_if_wdata[6] -type PI PI
add mapped point write_if.wdata[5] write_if_wdata[5] -type PI PI
add mapped point write_if.wdata[4] write_if_wdata[4] -type PI PI
add mapped point write_if.wdata[3] write_if_wdata[3] -type PI PI
add mapped point write_if.wdata[2] write_if_wdata[2] -type PI PI
add mapped point write_if.wdata[1] write_if_wdata[1] -type PI PI
add mapped point write_if.wdata[0] write_if_wdata[0] -type PI PI
add mapped point write_if.we write_if_we -type PI PI
add mapped point write_if.be[3] write_if_be[3] -type PI PI
add mapped point write_if.be[2] write_if_be[2] -type PI PI
add mapped point write_if.be[1] write_if_be[1] -type PI PI
add mapped point write_if.be[0] write_if_be[0] -type PI PI

//output ports
add mapped point error_flag error_flag -type PO PO
add mapped point we we -type PO PO
add mapped point re re -type PO PO
add mapped point wdata[7] wdata[7] -type PO PO
add mapped point wdata[6] wdata[6] -type PO PO
add mapped point wdata[5] wdata[5] -type PO PO
add mapped point wdata[4] wdata[4] -type PO PO
add mapped point wdata[3] wdata[3] -type PO PO
add mapped point wdata[2] wdata[2] -type PO PO
add mapped point wdata[1] wdata[1] -type PO PO
add mapped point wdata[0] wdata[0] -type PO PO
add mapped point waddr[3] waddr[3] -type PO PO
add mapped point waddr[2] waddr[2] -type PO PO
add mapped point waddr[1] waddr[1] -type PO PO
add mapped point waddr[0] waddr[0] -type PO PO
add mapped point raddr[3] raddr[3] -type PO PO
add mapped point raddr[2] raddr[2] -type PO PO
add mapped point raddr[1] raddr[1] -type PO PO
add mapped point raddr[0] raddr[0] -type PO PO
add mapped point fifo_full fifo_full -type PO PO
add mapped point read_if.gnt read_if_gnt -type PO PO
add mapped point read_if.rvalid read_if_rvalid -type PO PO
add mapped point read_if.rdata[31] read_if_rdata[31] -type PO PO
add mapped point read_if.rdata[30] read_if_rdata[30] -type PO PO
add mapped point read_if.rdata[29] read_if_rdata[29] -type PO PO
add mapped point read_if.rdata[28] read_if_rdata[28] -type PO PO
add mapped point read_if.rdata[27] read_if_rdata[27] -type PO PO
add mapped point read_if.rdata[26] read_if_rdata[26] -type PO PO
add mapped point read_if.rdata[25] read_if_rdata[25] -type PO PO
add mapped point read_if.rdata[24] read_if_rdata[24] -type PO PO
add mapped point read_if.rdata[23] read_if_rdata[23] -type PO PO
add mapped point read_if.rdata[22] read_if_rdata[22] -type PO PO
add mapped point read_if.rdata[21] read_if_rdata[21] -type PO PO
add mapped point read_if.rdata[20] read_if_rdata[20] -type PO PO
add mapped point read_if.rdata[19] read_if_rdata[19] -type PO PO
add mapped point read_if.rdata[18] read_if_rdata[18] -type PO PO
add mapped point read_if.rdata[17] read_if_rdata[17] -type PO PO
add mapped point read_if.rdata[16] read_if_rdata[16] -type PO PO
add mapped point read_if.rdata[15] read_if_rdata[15] -type PO PO
add mapped point read_if.rdata[14] read_if_rdata[14] -type PO PO
add mapped point read_if.rdata[13] read_if_rdata[13] -type PO PO
add mapped point read_if.rdata[12] read_if_rdata[12] -type PO PO
add mapped point read_if.rdata[11] read_if_rdata[11] -type PO PO
add mapped point read_if.rdata[10] read_if_rdata[10] -type PO PO
add mapped point read_if.rdata[9] read_if_rdata[9] -type PO PO
add mapped point read_if.rdata[8] read_if_rdata[8] -type PO PO
add mapped point read_if.rdata[7] read_if_rdata[7] -type PO PO
add mapped point read_if.rdata[6] read_if_rdata[6] -type PO PO
add mapped point read_if.rdata[5] read_if_rdata[5] -type PO PO
add mapped point read_if.rdata[4] read_if_rdata[4] -type PO PO
add mapped point read_if.rdata[3] read_if_rdata[3] -type PO PO
add mapped point read_if.rdata[2] read_if_rdata[2] -type PO PO
add mapped point read_if.rdata[1] read_if_rdata[1] -type PO PO
add mapped point read_if.rdata[0] read_if_rdata[0] -type PO PO
add mapped point write_if.gnt write_if_gnt -type PO PO
add mapped point write_if.rvalid write_if_rvalid -type PO PO
add mapped point write_if.rdata[31] write_if_rdata[31] -type PO PO
add mapped point write_if.rdata[30] write_if_rdata[30] -type PO PO
add mapped point write_if.rdata[29] write_if_rdata[29] -type PO PO
add mapped point write_if.rdata[28] write_if_rdata[28] -type PO PO
add mapped point write_if.rdata[27] write_if_rdata[27] -type PO PO
add mapped point write_if.rdata[26] write_if_rdata[26] -type PO PO
add mapped point write_if.rdata[25] write_if_rdata[25] -type PO PO
add mapped point write_if.rdata[24] write_if_rdata[24] -type PO PO
add mapped point write_if.rdata[23] write_if_rdata[23] -type PO PO
add mapped point write_if.rdata[22] write_if_rdata[22] -type PO PO
add mapped point write_if.rdata[21] write_if_rdata[21] -type PO PO
add mapped point write_if.rdata[20] write_if_rdata[20] -type PO PO
add mapped point write_if.rdata[19] write_if_rdata[19] -type PO PO
add mapped point write_if.rdata[18] write_if_rdata[18] -type PO PO
add mapped point write_if.rdata[17] write_if_rdata[17] -type PO PO
add mapped point write_if.rdata[16] write_if_rdata[16] -type PO PO
add mapped point write_if.rdata[15] write_if_rdata[15] -type PO PO
add mapped point write_if.rdata[14] write_if_rdata[14] -type PO PO
add mapped point write_if.rdata[13] write_if_rdata[13] -type PO PO
add mapped point write_if.rdata[12] write_if_rdata[12] -type PO PO
add mapped point write_if.rdata[11] write_if_rdata[11] -type PO PO
add mapped point write_if.rdata[10] write_if_rdata[10] -type PO PO
add mapped point write_if.rdata[9] write_if_rdata[9] -type PO PO
add mapped point write_if.rdata[8] write_if_rdata[8] -type PO PO
add mapped point write_if.rdata[7] write_if_rdata[7] -type PO PO
add mapped point write_if.rdata[6] write_if_rdata[6] -type PO PO
add mapped point write_if.rdata[5] write_if_rdata[5] -type PO PO
add mapped point write_if.rdata[4] write_if_rdata[4] -type PO PO
add mapped point write_if.rdata[3] write_if_rdata[3] -type PO PO
add mapped point write_if.rdata[2] write_if_rdata[2] -type PO PO
add mapped point write_if.rdata[1] write_if_rdata[1] -type PO PO
add mapped point write_if.rdata[0] write_if_rdata[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point async_fifo_i/rptr_empty_inst/rempty/q async_fifo_i_rptr_empty_inst/rempty_reg/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[1]/q async_fifo_i_rptr_empty_inst/rbin_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[2]/q async_fifo_i_rptr_empty_inst/rbin_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[3]/q async_fifo_i_rptr_empty_inst/rbin_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[4]/q async_fifo_i_rptr_empty_inst/rbin_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[0]/q async_fifo_i_rptr_empty_inst/rbin_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rptr[0]/q async_fifo_i_rptr_empty_inst/rptr_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rptr[3]/q async_fifo_i_rptr_empty_inst/rptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rptr[1]/q async_fifo_i_rptr_empty_inst/rptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rptr[2]/q async_fifo_i_rptr_empty_inst/rptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wptr[3]/q async_fifo_i_wptr_full_inst/wptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wptr[2]/q async_fifo_i_wptr_full_inst/wptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wptr[1]/q async_fifo_i_wptr_full_inst/wptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wptr[0]/q async_fifo_i_wptr_full_inst/wptr_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wfull/q async_fifo_i_wptr_full_inst/wfull_reg/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[3]/q async_fifo_i_wptr_full_inst/wbin_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[2]/q async_fifo_i_wptr_full_inst/wbin_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[0]/q async_fifo_i_wptr_full_inst/wbin_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[4]/q async_fifo_i_wptr_full_inst/wbin_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[1]/q async_fifo_i_wptr_full_inst/wbin_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[4]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[3]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[2]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[1]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[4]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[2]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[1]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[3]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[0]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[0]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[4]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[3]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[2]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[1]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[2]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[1]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[4]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[3]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[0]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[0]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[0]/Q -type DFF DFF
add mapped point write_gnt_dly/q write_gnt_dly_reg/Q -type DFF DFF
add mapped point read_gnt_dly/q read_gnt_dly_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
