
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Jun 22 2025 18:27:30 UTC (Jun 22 2025 18:27:30 UTC)

// Verification Directory fv/ipr 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_3(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_4(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_5(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_6(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module RC_CG_MOD_7(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module fifomem_DATASIZE8_ADDRSIZE3_FALLTHROUGH1(wclk, wclken, waddr,
     wdata, wfull, rclk, rclken, raddr, rdata);
  input wclk, wclken, wfull, rclk, rclken;
  input [2:0] waddr, raddr;
  input [7:0] wdata;
  output [7:0] rdata;
  wire wclk, wclken, wfull, rclk, rclken;
  wire [2:0] waddr, raddr;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_57, n_58, n_70;
  wire n_72, n_73, n_74, n_75, n_76, n_87, n_88, n_89;
  wire n_90, n_91, n_92, rc_gclk, rc_gclk_232, rc_gclk_234,
       rc_gclk_236, rc_gclk_238;
  wire rc_gclk_240, rc_gclk_242, rc_gclk_244;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_92), .ck_in (wclk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_1 RC_CG_HIER_INST1(.enable (n_70), .ck_in (wclk), .ck_out
       (rc_gclk_232), .test (1'b0));
  RC_CG_MOD_2 RC_CG_HIER_INST2(.enable (n_89), .ck_in (wclk), .ck_out
       (rc_gclk_234), .test (1'b0));
  RC_CG_MOD_3 RC_CG_HIER_INST3(.enable (n_72), .ck_in (wclk), .ck_out
       (rc_gclk_236), .test (1'b0));
  RC_CG_MOD_4 RC_CG_HIER_INST4(.enable (n_73), .ck_in (wclk), .ck_out
       (rc_gclk_238), .test (1'b0));
  RC_CG_MOD_5 RC_CG_HIER_INST5(.enable (n_74), .ck_in (wclk), .ck_out
       (rc_gclk_240), .test (1'b0));
  RC_CG_MOD_6 RC_CG_HIER_INST6(.enable (n_75), .ck_in (wclk), .ck_out
       (rc_gclk_242), .test (1'b0));
  RC_CG_MOD_7 RC_CG_HIER_INST7(.enable (n_76), .ck_in (wclk), .ck_out
       (rc_gclk_244), .test (1'b0));
  AN2D0BWP16P90 g707__2398(.A1 (n_91), .A2 (waddr[0]), .Z (n_76));
  NR2D0BWP16P90 g708__5107(.A1 (n_58), .A2 (waddr[0]), .ZN (n_75));
  INR2D0BWP16P90 g709__6260(.A1 (waddr[0]), .B1 (n_58), .ZN (n_74));
  AN2D0BWP16P90 g712__5526(.A1 (n_88), .A2 (waddr[0]), .Z (n_70));
  AN2D0BWP16P90 g713__6783(.A1 (n_57), .A2 (waddr[0]), .Z (n_72));
  INR2D0BWP16P90 g714__3680(.A1 (n_57), .B1 (waddr[0]), .ZN (n_73));
  ND2D0BWP16P90 g717__2802(.A1 (n_90), .A2 (waddr[1]), .ZN (n_58));
  NR2D0BWP16P90 g719__1705(.A1 (n_87), .A2 (waddr[1]), .ZN (n_57));
  DFQND0BWP16P90 \mem_reg[0][0] (.CP (rc_gclk), .D (wdata[0]), .QN
       (\mem[0] [0]));
  DFQND0BWP16P90 \mem_reg[0][1] (.CP (rc_gclk), .D (wdata[1]), .QN
       (\mem[0] [1]));
  DFQND0BWP16P90 \mem_reg[0][2] (.CP (rc_gclk), .D (wdata[2]), .QN
       (\mem[0] [2]));
  DFQND0BWP16P90 \mem_reg[0][3] (.CP (rc_gclk), .D (wdata[3]), .QN
       (\mem[0] [3]));
  DFQND0BWP16P90 \mem_reg[0][4] (.CP (rc_gclk), .D (wdata[4]), .QN
       (\mem[0] [4]));
  DFQD0BWP16P90 \mem_reg[0][5] (.CP (rc_gclk), .D (wdata[5]), .Q
       (\mem[0] [5]));
  DFQD0BWP16P90 \mem_reg[0][6] (.CP (rc_gclk), .D (wdata[6]), .Q
       (\mem[0] [6]));
  DFQND0BWP16P90 \mem_reg[0][7] (.CP (rc_gclk), .D (wdata[7]), .QN
       (\mem[0] [7]));
  DFQND0BWP16P90 \mem_reg[1][0] (.CP (rc_gclk_244), .D (wdata[0]), .QN
       (\mem[1] [0]));
  DFQND0BWP16P90 \mem_reg[1][1] (.CP (rc_gclk_244), .D (wdata[1]), .QN
       (\mem[1] [1]));
  DFQD0BWP16P90 \mem_reg[1][2] (.CP (rc_gclk_244), .D (wdata[2]), .Q
       (\mem[1] [2]));
  DFQD0BWP16P90 \mem_reg[1][3] (.CP (rc_gclk_244), .D (wdata[3]), .Q
       (\mem[1] [3]));
  DFQND0BWP16P90 \mem_reg[1][4] (.CP (rc_gclk_244), .D (wdata[4]), .QN
       (\mem[1] [4]));
  DFQD0BWP16P90 \mem_reg[1][5] (.CP (rc_gclk_244), .D (wdata[5]), .Q
       (\mem[1] [5]));
  DFQD0BWP16P90 \mem_reg[1][6] (.CP (rc_gclk_244), .D (wdata[6]), .Q
       (\mem[1] [6]));
  DFQD0BWP16P90 \mem_reg[1][7] (.CP (rc_gclk_244), .D (wdata[7]), .Q
       (\mem[1] [7]));
  DFQND0BWP16P90 \mem_reg[2][0] (.CP (rc_gclk_242), .D (wdata[0]), .QN
       (\mem[2] [0]));
  DFQND0BWP16P90 \mem_reg[2][1] (.CP (rc_gclk_242), .D (wdata[1]), .QN
       (\mem[2] [1]));
  DFQND0BWP16P90 \mem_reg[2][2] (.CP (rc_gclk_242), .D (wdata[2]), .QN
       (\mem[2] [2]));
  DFQND0BWP16P90 \mem_reg[2][3] (.CP (rc_gclk_242), .D (wdata[3]), .QN
       (\mem[2] [3]));
  DFQND0BWP16P90 \mem_reg[2][4] (.CP (rc_gclk_242), .D (wdata[4]), .QN
       (\mem[2] [4]));
  DFQD0BWP16P90 \mem_reg[2][5] (.CP (rc_gclk_242), .D (wdata[5]), .Q
       (\mem[2] [5]));
  DFQD0BWP16P90 \mem_reg[2][6] (.CP (rc_gclk_242), .D (wdata[6]), .Q
       (\mem[2] [6]));
  DFQND0BWP16P90 \mem_reg[2][7] (.CP (rc_gclk_242), .D (wdata[7]), .QN
       (\mem[2] [7]));
  DFQND0BWP16P90 \mem_reg[3][0] (.CP (rc_gclk_240), .D (wdata[0]), .QN
       (\mem[3] [0]));
  DFQND0BWP16P90 \mem_reg[3][1] (.CP (rc_gclk_240), .D (wdata[1]), .QN
       (\mem[3] [1]));
  DFQD0BWP16P90 \mem_reg[3][2] (.CP (rc_gclk_240), .D (wdata[2]), .Q
       (\mem[3] [2]));
  DFQD0BWP16P90 \mem_reg[3][3] (.CP (rc_gclk_240), .D (wdata[3]), .Q
       (\mem[3] [3]));
  DFQND0BWP16P90 \mem_reg[3][4] (.CP (rc_gclk_240), .D (wdata[4]), .QN
       (\mem[3] [4]));
  DFQD0BWP16P90 \mem_reg[3][5] (.CP (rc_gclk_240), .D (wdata[5]), .Q
       (\mem[3] [5]));
  DFQD0BWP16P90 \mem_reg[3][6] (.CP (rc_gclk_240), .D (wdata[6]), .Q
       (\mem[3] [6]));
  DFQD0BWP16P90 \mem_reg[3][7] (.CP (rc_gclk_240), .D (wdata[7]), .Q
       (\mem[3] [7]));
  DFQND0BWP16P90 \mem_reg[4][0] (.CP (rc_gclk_238), .D (wdata[0]), .QN
       (\mem[4] [0]));
  DFQND0BWP16P90 \mem_reg[4][1] (.CP (rc_gclk_238), .D (wdata[1]), .QN
       (\mem[4] [1]));
  DFQD0BWP16P90 \mem_reg[4][2] (.CP (rc_gclk_238), .D (wdata[2]), .Q
       (\mem[4] [2]));
  DFQND0BWP16P90 \mem_reg[4][3] (.CP (rc_gclk_238), .D (wdata[3]), .QN
       (\mem[4] [3]));
  DFQND0BWP16P90 \mem_reg[4][4] (.CP (rc_gclk_238), .D (wdata[4]), .QN
       (\mem[4] [4]));
  DFQD0BWP16P90 \mem_reg[4][5] (.CP (rc_gclk_238), .D (wdata[5]), .Q
       (\mem[4] [5]));
  DFQD0BWP16P90 \mem_reg[4][6] (.CP (rc_gclk_238), .D (wdata[6]), .Q
       (\mem[4] [6]));
  DFQND0BWP16P90 \mem_reg[4][7] (.CP (rc_gclk_238), .D (wdata[7]), .QN
       (\mem[4] [7]));
  DFQND0BWP16P90 \mem_reg[5][0] (.CP (rc_gclk_236), .D (wdata[0]), .QN
       (\mem[5] [0]));
  DFQND0BWP16P90 \mem_reg[5][1] (.CP (rc_gclk_236), .D (wdata[1]), .QN
       (\mem[5] [1]));
  DFQD0BWP16P90 \mem_reg[5][2] (.CP (rc_gclk_236), .D (wdata[2]), .Q
       (\mem[5] [2]));
  DFQD0BWP16P90 \mem_reg[5][3] (.CP (rc_gclk_236), .D (wdata[3]), .Q
       (\mem[5] [3]));
  DFQND0BWP16P90 \mem_reg[5][4] (.CP (rc_gclk_236), .D (wdata[4]), .QN
       (\mem[5] [4]));
  DFQD0BWP16P90 \mem_reg[5][5] (.CP (rc_gclk_236), .D (wdata[5]), .Q
       (\mem[5] [5]));
  DFQD0BWP16P90 \mem_reg[5][6] (.CP (rc_gclk_236), .D (wdata[6]), .Q
       (\mem[5] [6]));
  DFQD0BWP16P90 \mem_reg[5][7] (.CP (rc_gclk_236), .D (wdata[7]), .Q
       (\mem[5] [7]));
  DFQND0BWP16P90 \mem_reg[6][0] (.CP (rc_gclk_234), .D (wdata[0]), .QN
       (\mem[6] [0]));
  DFQND0BWP16P90 \mem_reg[6][1] (.CP (rc_gclk_234), .D (wdata[1]), .QN
       (\mem[6] [1]));
  DFQD0BWP16P90 \mem_reg[6][2] (.CP (rc_gclk_234), .D (wdata[2]), .Q
       (\mem[6] [2]));
  DFQND0BWP16P90 \mem_reg[6][3] (.CP (rc_gclk_234), .D (wdata[3]), .QN
       (\mem[6] [3]));
  DFQND0BWP16P90 \mem_reg[6][4] (.CP (rc_gclk_234), .D (wdata[4]), .QN
       (\mem[6] [4]));
  DFQD0BWP16P90 \mem_reg[6][5] (.CP (rc_gclk_234), .D (wdata[5]), .Q
       (\mem[6] [5]));
  DFQD0BWP16P90 \mem_reg[6][6] (.CP (rc_gclk_234), .D (wdata[6]), .Q
       (\mem[6] [6]));
  DFQND0BWP16P90 \mem_reg[6][7] (.CP (rc_gclk_234), .D (wdata[7]), .QN
       (\mem[6] [7]));
  DFQND0BWP16P90 \mem_reg[7][0] (.CP (rc_gclk_232), .D (wdata[0]), .QN
       (\mem[7] [0]));
  DFQND0BWP16P90 \mem_reg[7][1] (.CP (rc_gclk_232), .D (wdata[1]), .QN
       (\mem[7] [1]));
  DFQD0BWP16P90 \mem_reg[7][2] (.CP (rc_gclk_232), .D (wdata[2]), .Q
       (\mem[7] [2]));
  DFQD0BWP16P90 \mem_reg[7][3] (.CP (rc_gclk_232), .D (wdata[3]), .Q
       (\mem[7] [3]));
  DFQND0BWP16P90 \mem_reg[7][4] (.CP (rc_gclk_232), .D (wdata[4]), .QN
       (\mem[7] [4]));
  DFQD0BWP16P90 \mem_reg[7][5] (.CP (rc_gclk_232), .D (wdata[5]), .Q
       (\mem[7] [5]));
  DFQD0BWP16P90 \mem_reg[7][6] (.CP (rc_gclk_232), .D (wdata[6]), .Q
       (\mem[7] [6]));
  DFQD0BWP16P90 \mem_reg[7][7] (.CP (rc_gclk_232), .D (wdata[7]), .Q
       (\mem[7] [7]));
  OAI221D0BWP16P90 g1290__6131(.A1 (n_15), .A2 (\mem[1] [1]), .B1
       (\mem[7] [1]), .B2 (n_10), .C (n_52), .ZN (rdata[1]));
  OAI221D0BWP16P90 g1291__1881(.A1 (n_20), .A2 (\mem[3] [0]), .B1
       (\mem[7] [0]), .B2 (n_10), .C (n_51), .ZN (rdata[0]));
  ND4D0BWP16P90 g1292__5115(.A1 (n_41), .A2 (n_32), .A3 (n_45), .A4
       (n_25), .ZN (rdata[5]));
  ND4D0BWP16P90 g1293__7482(.A1 (n_40), .A2 (n_39), .A3 (n_38), .A4
       (n_23), .ZN (rdata[2]));
  OAI221D0BWP16P90 g1294__4733(.A1 (n_7), .A2 (\mem[0] [3]), .B1
       (\mem[4] [3]), .B2 (n_21), .C (n_48), .ZN (rdata[3]));
  ND4D0BWP16P90 g1295__6161(.A1 (n_42), .A2 (n_28), .A3 (n_29), .A4
       (n_26), .ZN (rdata[6]));
  OAI221D0BWP16P90 g1296__9315(.A1 (n_7), .A2 (\mem[0] [4]), .B1
       (\mem[4] [4]), .B2 (n_21), .C (n_50), .ZN (rdata[4]));
  OAI221D0BWP16P90 g1297__9945(.A1 (n_7), .A2 (\mem[0] [7]), .B1
       (\mem[4] [7]), .B2 (n_21), .C (n_49), .ZN (rdata[7]));
  NR3D0BWP16P90 g1298__2883(.A1 (n_30), .A2 (n_44), .A3 (n_27), .ZN
       (n_52));
  NR3D0BWP16P90 g1299__2346(.A1 (n_31), .A2 (n_43), .A3 (n_24), .ZN
       (n_51));
  NR3D0BWP16P90 g1300__1666(.A1 (n_37), .A2 (n_34), .A3 (n_36), .ZN
       (n_50));
  AOI221D0BWP16P90 g1301__7410(.A1 (n_16), .A2 (\mem[1] [7]), .B1
       (n_12), .B2 (\mem[5] [7]), .C (n_47), .ZN (n_49));
  AOI221D0BWP16P90 g1302__6417(.A1 (n_19), .A2 (\mem[3] [3]), .B1
       (n_12), .B2 (\mem[5] [3]), .C (n_46), .ZN (n_48));
  OAI221D0BWP16P90 g1303__5477(.A1 (n_14), .A2 (\mem[2] [7]), .B1
       (\mem[6] [7]), .B2 (n_18), .C (n_35), .ZN (n_47));
  OAI221D0BWP16P90 g1304__2398(.A1 (n_14), .A2 (\mem[2] [3]), .B1
       (\mem[6] [3]), .B2 (n_18), .C (n_33), .ZN (n_46));
  AOI22D0BWP16P90 g1305__5107(.A1 (n_19), .A2 (\mem[3] [5]), .B1 (n_9),
       .B2 (\mem[7] [5]), .ZN (n_45));
  OAI22D0BWP16P90 g1306__6260(.A1 (n_21), .A2 (\mem[4] [1]), .B1
       (n_20), .B2 (\mem[3] [1]), .ZN (n_44));
  OAI22D0BWP16P90 g1307__4319(.A1 (n_15), .A2 (\mem[1] [0]), .B1
       (n_18), .B2 (\mem[6] [0]), .ZN (n_43));
  AOI22D0BWP16P90 g1308__8428(.A1 (n_16), .A2 (\mem[1] [6]), .B1
       (n_17), .B2 (\mem[6] [6]), .ZN (n_42));
  AOI22D0BWP16P90 g1309__5526(.A1 (n_16), .A2 (\mem[1] [5]), .B1
       (n_17), .B2 (\mem[6] [5]), .ZN (n_41));
  AOI22D0BWP16P90 g1310__6783(.A1 (n_16), .A2 (\mem[1] [2]), .B1
       (n_17), .B2 (\mem[6] [2]), .ZN (n_40));
  AOI22D0BWP16P90 g1311__3680(.A1 (n_22), .A2 (\mem[4] [2]), .B1
       (n_12), .B2 (\mem[5] [2]), .ZN (n_39));
  AOI22D0BWP16P90 g1312__1617(.A1 (n_19), .A2 (\mem[3] [2]), .B1 (n_9),
       .B2 (\mem[7] [2]), .ZN (n_38));
  OAI22D0BWP16P90 g1313__2802(.A1 (n_20), .A2 (\mem[3] [4]), .B1
       (n_10), .B2 (\mem[7] [4]), .ZN (n_37));
  OAI22D0BWP16P90 g1314__1705(.A1 (n_15), .A2 (\mem[1] [4]), .B1
       (n_11), .B2 (\mem[5] [4]), .ZN (n_36));
  AOI22D0BWP16P90 g1315__5122(.A1 (n_19), .A2 (\mem[3] [7]), .B1 (n_9),
       .B2 (\mem[7] [7]), .ZN (n_35));
  OAI22D0BWP16P90 g1316__8246(.A1 (n_14), .A2 (\mem[2] [4]), .B1
       (n_18), .B2 (\mem[6] [4]), .ZN (n_34));
  AOI22D0BWP16P90 g1317__7098(.A1 (n_16), .A2 (\mem[1] [3]), .B1 (n_9),
       .B2 (\mem[7] [3]), .ZN (n_33));
  AOI22D0BWP16P90 g1318__6131(.A1 (n_8), .A2 (\mem[0] [5]), .B1 (n_22),
       .B2 (\mem[4] [5]), .ZN (n_32));
  OAI22D0BWP16P90 g1319__1881(.A1 (n_7), .A2 (\mem[0] [0]), .B1 (n_21),
       .B2 (\mem[4] [0]), .ZN (n_31));
  OAI22D0BWP16P90 g1320__5115(.A1 (n_14), .A2 (\mem[2] [1]), .B1
       (n_18), .B2 (\mem[6] [1]), .ZN (n_30));
  AOI22D0BWP16P90 g1321__7482(.A1 (n_13), .A2 (\mem[2] [6]), .B1
       (n_22), .B2 (\mem[4] [6]), .ZN (n_29));
  AOI22D0BWP16P90 g1322__4733(.A1 (n_19), .A2 (\mem[3] [6]), .B1
       (n_12), .B2 (\mem[5] [6]), .ZN (n_28));
  OAI22D0BWP16P90 g1323__6161(.A1 (n_7), .A2 (\mem[0] [1]), .B1 (n_11),
       .B2 (\mem[5] [1]), .ZN (n_27));
  AOI22D0BWP16P90 g1324__9315(.A1 (n_8), .A2 (\mem[0] [6]), .B1 (n_9),
       .B2 (\mem[7] [6]), .ZN (n_26));
  AOI22D0BWP16P90 g1325__9945(.A1 (n_13), .A2 (\mem[2] [5]), .B1
       (n_12), .B2 (\mem[5] [5]), .ZN (n_25));
  OAI22D0BWP16P90 g1326__2883(.A1 (n_14), .A2 (\mem[2] [0]), .B1
       (n_11), .B2 (\mem[5] [0]), .ZN (n_24));
  OA22D0BWP16P90 g1327__2346(.A1 (n_7), .A2 (\mem[0] [2]), .B1 (n_14),
       .B2 (\mem[2] [2]), .Z (n_23));
  INVD0BWP16P90 g1328(.I (n_22), .ZN (n_21));
  INVD0BWP16P90 g1329(.I (n_20), .ZN (n_19));
  INVD0BWP16P90 g1330(.I (n_18), .ZN (n_17));
  INVD0BWP16P90 g1331(.I (n_16), .ZN (n_15));
  NR2D0BWP16P90 g1332__1666(.A1 (raddr[1]), .A2 (n_6), .ZN (n_22));
  ND2D0BWP16P90 g1333__7410(.A1 (n_0), .A2 (raddr[1]), .ZN (n_20));
  ND2D0BWP16P90 g1334__6417(.A1 (n_5), .A2 (raddr[1]), .ZN (n_18));
  NR2D0BWP16P90 g1335__5477(.A1 (n_1), .A2 (raddr[1]), .ZN (n_16));
  INVD0BWP16P90 g1336(.I (n_14), .ZN (n_13));
  INVD0BWP16P90 g1337(.I (n_12), .ZN (n_11));
  INVD0BWP16P90 g1338(.I (n_10), .ZN (n_9));
  INVD0BWP16P90 g1339(.I (n_8), .ZN (n_7));
  ND2D0BWP16P90 g1340__2398(.A1 (n_4), .A2 (raddr[1]), .ZN (n_14));
  NR2D0BWP16P90 g1341__5107(.A1 (n_2), .A2 (raddr[1]), .ZN (n_12));
  ND2D0BWP16P90 g1342__6260(.A1 (raddr[1]), .A2 (n_3), .ZN (n_10));
  INR2D0BWP16P90 g1343__4319(.A1 (n_4), .B1 (raddr[1]), .ZN (n_8));
  INVD0BWP16P90 g1344(.I (n_5), .ZN (n_6));
  INVD0BWP16P90 g1345(.I (n_2), .ZN (n_3));
  INVD0BWP16P90 g1346(.I (n_0), .ZN (n_1));
  INR2D0BWP16P90 g1377__8428(.A1 (raddr[2]), .B1 (raddr[0]), .ZN (n_5));
  NR2D0BWP16P90 g1378__5526(.A1 (raddr[0]), .A2 (raddr[2]), .ZN (n_4));
  ND2D0BWP16P90 g1379__6783(.A1 (raddr[2]), .A2 (raddr[0]), .ZN (n_2));
  INR2D0BWP16P90 g1380__3680(.A1 (raddr[0]), .B1 (raddr[2]), .ZN (n_0));
  IND3D0BWP16P90 g36(.A1 (wfull), .B1 (waddr[2]), .B2 (wclken), .ZN
       (n_87));
  INR2D0BWP16P90 g35(.A1 (waddr[1]), .B1 (n_87), .ZN (n_88));
  INR2D0BWP16P90 g34(.A1 (n_88), .B1 (waddr[0]), .ZN (n_89));
  INR2D0BWP16P90 g1415(.A1 (n_90), .B1 (waddr[1]), .ZN (n_91));
  INR3D0BWP16P90 g1416(.A1 (wclken), .B1 (waddr[2]), .B2 (wfull), .ZN
       (n_90));
  INR2D0BWP16P90 g1417(.A1 (n_91), .B1 (waddr[0]), .ZN (n_92));
endmodule

module RC_CG_MOD_46(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module rptr_empty_ADDRSIZE3(rclk, rrst_n, rinc, rq2_wptr, rempty,
     arempty, raddr, rptr);
  input rclk, rrst_n, rinc;
  input [3:0] rq2_wptr;
  output rempty, arempty;
  output [2:0] raddr;
  output [3:0] rptr;
  wire rclk, rrst_n, rinc;
  wire [3:0] rq2_wptr;
  wire rempty, arempty;
  wire [2:0] raddr;
  wire [3:0] rptr;
  wire [3:0] rgraynext;
  wire [3:0] rbinnext;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, rc_gclk;
  RC_CG_MOD_46 RC_CG_HIER_INST8(.enable (n_9), .ck_in (rclk), .ck_out
       (rc_gclk), .test (1'b0));
  DFCNQD0BWP16P90 \rptr_reg[2] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[2]), .Q (rptr[2]));
  XOR2D0BWP16P90 g212__1617(.A1 (rbinnext[2]), .A2 (rbinnext[3]), .Z
       (rgraynext[2]));
  DFCNQD0BWP16P90 \rptr_reg[1] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[1]), .Q (rptr[1]));
  XOR2D0BWP16P90 g214__2802(.A1 (rbinnext[1]), .A2 (rbinnext[2]), .Z
       (rgraynext[1]));
  XOR2D0BWP16P90 g215__1705(.A1 (rptr[3]), .A2 (n_7), .Z (rbinnext[3]));
  HA1D0BWP16P90 g216__5122(.A (raddr[2]), .B (n_6), .CO (n_7), .S
       (rbinnext[2]));
  DFCNQD0BWP16P90 \rptr_reg[0] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[0]), .Q (rptr[0]));
  XOR2D0BWP16P90 g218__8246(.A1 (rbinnext[0]), .A2 (rbinnext[1]), .Z
       (rgraynext[0]));
  HA1D0BWP16P90 g219__7098(.A (raddr[1]), .B (n_5), .CO (n_6), .S
       (rbinnext[1]));
  HA1D0BWP16P90 g220__6131(.A (raddr[0]), .B (n_9), .CO (n_5), .S
       (rbinnext[0]));
  INR2D0BWP16P90 g221__1881(.A1 (rinc), .B1 (rempty), .ZN (n_9));
  DFSNQD0BWP16P90 rempty_reg(.SDN (rrst_n), .CP (rclk), .D (n_4), .Q
       (rempty));
  NR4D0BWP16P90 g222__5115(.A1 (n_3), .A2 (n_2), .A3 (n_1), .A4 (n_0),
       .ZN (n_4));
  XOR2D0BWP16P90 g223__7482(.A1 (rq2_wptr[2]), .A2 (rgraynext[2]), .Z
       (n_3));
  XOR2D0BWP16P90 g224__4733(.A1 (rq2_wptr[1]), .A2 (rgraynext[1]), .Z
       (n_2));
  XOR2D0BWP16P90 g217__6161(.A1 (rq2_wptr[3]), .A2 (rbinnext[3]), .Z
       (n_1));
  XOR2D0BWP16P90 g225__9315(.A1 (rq2_wptr[0]), .A2 (rgraynext[0]), .Z
       (n_0));
  DFCNQD0BWP16P90 \rbin_reg[2] (.CDN (rrst_n), .CP (rc_gclk), .D
       (rbinnext[2]), .Q (raddr[2]));
  DFCNQD0BWP16P90 \rbin_reg[0] (.CDN (rrst_n), .CP (rc_gclk), .D
       (rbinnext[0]), .Q (raddr[0]));
  DFCNQD0BWP16P90 \rbin_reg[3] (.CDN (rrst_n), .CP (rc_gclk), .D
       (rbinnext[3]), .Q (rptr[3]));
  DFCNQD0BWP16P90 \rbin_reg[1] (.CDN (rrst_n), .CP (rc_gclk), .D
       (rbinnext[1]), .Q (raddr[1]));
endmodule

module RC_CG_MOD_46_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQD1BWP16P90 RC_CGIC_INST(.E (enable), .CP (ck_in), .TE (test), .Q
       (ck_out));
endmodule

module wptr_full_ADDRSIZE3(wclk, wrst_n, winc, wq2_rptr, wfull, awfull,
     waddr, wptr);
  input wclk, wrst_n, winc;
  input [3:0] wq2_rptr;
  output wfull, awfull;
  output [2:0] waddr;
  output [3:0] wptr;
  wire wclk, wrst_n, winc;
  wire [3:0] wq2_rptr;
  wire wfull, awfull;
  wire [2:0] waddr;
  wire [3:0] wptr;
  wire [3:0] wgraynext;
  wire [3:0] wbinnext;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, rc_gclk;
  RC_CG_MOD_46_1 RC_CG_HIER_INST9(.enable (n_9), .ck_in (wclk), .ck_out
       (rc_gclk), .test (1'b0));
  DFCNQD0BWP16P90 \wptr_reg[2] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[2]), .Q (wptr[2]));
  XOR2D0BWP16P90 g216__9945(.A1 (wbinnext[3]), .A2 (wbinnext[2]), .Z
       (wgraynext[2]));
  DFCNQD0BWP16P90 \wptr_reg[1] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[1]), .Q (wptr[1]));
  XOR2D0BWP16P90 g218__2883(.A1 (wbinnext[2]), .A2 (wbinnext[1]), .Z
       (wgraynext[1]));
  XOR2D0BWP16P90 g219__2346(.A1 (n_7), .A2 (wptr[3]), .Z (wbinnext[3]));
  HA1D0BWP16P90 g220__1666(.A (waddr[2]), .B (n_6), .CO (n_7), .S
       (wbinnext[2]));
  DFCNQD0BWP16P90 \wptr_reg[0] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[0]), .Q (wptr[0]));
  XOR2D0BWP16P90 g222__7410(.A1 (wbinnext[1]), .A2 (wbinnext[0]), .Z
       (wgraynext[0]));
  HA1D0BWP16P90 g223__6417(.A (waddr[1]), .B (n_5), .CO (n_6), .S
       (wbinnext[1]));
  HA1D0BWP16P90 g224__5477(.A (waddr[0]), .B (n_9), .CO (n_5), .S
       (wbinnext[0]));
  INR2D0BWP16P90 g225__2398(.A1 (winc), .B1 (wfull), .ZN (n_9));
  DFCNQD0BWP16P90 wfull_reg(.CDN (wrst_n), .CP (wclk), .D (n_4), .Q
       (wfull));
  NR4D0BWP16P90 g226__5107(.A1 (n_3), .A2 (n_2), .A3 (n_1), .A4 (n_0),
       .ZN (n_4));
  XNR2D0BWP16P90 g227__6260(.A1 (wq2_rptr[2]), .A2 (wgraynext[2]), .ZN
       (n_3));
  XOR2D0BWP16P90 g228__4319(.A1 (wq2_rptr[1]), .A2 (wgraynext[1]), .Z
       (n_2));
  XNR2D0BWP16P90 g221__8428(.A1 (wq2_rptr[3]), .A2 (wbinnext[3]), .ZN
       (n_1));
  XOR2D0BWP16P90 g229__5526(.A1 (wq2_rptr[0]), .A2 (wgraynext[0]), .Z
       (n_0));
  DFCNQD0BWP16P90 \wbin_reg[1] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[1]), .Q (waddr[1]));
  DFCNQD0BWP16P90 \wbin_reg[2] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[2]), .Q (waddr[2]));
  DFCNQD0BWP16P90 \wbin_reg[0] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[0]), .Q (waddr[0]));
  DFCNQD0BWP16P90 \wbin_reg[3] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[3]), .Q (wptr[3]));
endmodule

module ipr(w_clk, w_rst_n, r_clk, r_rst_n, error_flag, read_if_req,
     read_if_addr, read_if_be, read_if_we, read_if_gnt, read_if_rvalid,
     read_if_rdata, write_if_req, write_if_addr, write_if_wdata,
     write_if_we, write_if_be, write_if_gnt, write_if_rvalid,
     write_if_rdata);
  input w_clk, w_rst_n, r_clk, r_rst_n, read_if_req, read_if_we,
       write_if_req, write_if_we;
  input [31:0] read_if_addr, write_if_addr, write_if_wdata;
  input [3:0] read_if_be, write_if_be;
  output error_flag, read_if_gnt, read_if_rvalid, write_if_gnt,
       write_if_rvalid;
  output [31:0] read_if_rdata, write_if_rdata;
  wire w_clk, w_rst_n, r_clk, r_rst_n, read_if_req, read_if_we,
       write_if_req, write_if_we;
  wire [31:0] read_if_addr, write_if_addr, write_if_wdata;
  wire [3:0] read_if_be, write_if_be;
  wire error_flag, read_if_gnt, read_if_rvalid, write_if_gnt,
       write_if_rvalid;
  wire [31:0] read_if_rdata, write_if_rdata;
  wire [2:0] async_fifo_i_waddr;
  wire [2:0] async_fifo_i_raddr;
  wire [3:0] async_fifo_i_rq2_wptr;
  wire [3:0] async_fifo_i_rptr;
  wire [3:0] async_fifo_i_wq2_rptr;
  wire [3:0] async_fifo_i_wptr;
  wire [3:0] async_fifo_i_sync_r2w_inst_wq1_rptr;
  wire [3:0] async_fifo_i_sync_w2r_inst_rq1_wptr;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, async_fifo_i_n_17,
       async_fifo_i_n_27, fifo_empty, fifo_full, we;
  assign write_if_rdata[0] = 1'b0;
  assign write_if_rdata[1] = 1'b0;
  assign write_if_rdata[2] = 1'b0;
  assign write_if_rdata[3] = 1'b0;
  assign write_if_rdata[4] = 1'b0;
  assign write_if_rdata[5] = 1'b0;
  assign write_if_rdata[6] = 1'b0;
  assign write_if_rdata[7] = 1'b0;
  assign write_if_rdata[8] = 1'b0;
  assign write_if_rdata[9] = 1'b0;
  assign write_if_rdata[10] = 1'b0;
  assign write_if_rdata[11] = 1'b0;
  assign write_if_rdata[12] = 1'b0;
  assign write_if_rdata[13] = 1'b0;
  assign write_if_rdata[14] = 1'b0;
  assign write_if_rdata[15] = 1'b0;
  assign write_if_rdata[16] = 1'b0;
  assign write_if_rdata[17] = 1'b0;
  assign write_if_rdata[18] = 1'b0;
  assign write_if_rdata[19] = 1'b0;
  assign write_if_rdata[20] = 1'b0;
  assign write_if_rdata[21] = 1'b0;
  assign write_if_rdata[22] = 1'b0;
  assign write_if_rdata[23] = 1'b0;
  assign write_if_rdata[24] = 1'b0;
  assign write_if_rdata[25] = 1'b0;
  assign write_if_rdata[26] = 1'b0;
  assign write_if_rdata[27] = 1'b0;
  assign write_if_rdata[28] = 1'b0;
  assign write_if_rdata[29] = 1'b0;
  assign write_if_rdata[30] = 1'b0;
  assign write_if_rdata[31] = 1'b0;
  assign read_if_rdata[8] = 1'b0;
  assign read_if_rdata[9] = 1'b0;
  assign read_if_rdata[10] = 1'b0;
  assign read_if_rdata[11] = 1'b0;
  assign read_if_rdata[12] = 1'b0;
  assign read_if_rdata[13] = 1'b0;
  assign read_if_rdata[14] = 1'b0;
  assign read_if_rdata[15] = 1'b0;
  assign read_if_rdata[16] = 1'b0;
  assign read_if_rdata[17] = 1'b0;
  assign read_if_rdata[18] = 1'b0;
  assign read_if_rdata[19] = 1'b0;
  assign read_if_rdata[20] = 1'b0;
  assign read_if_rdata[21] = 1'b0;
  assign read_if_rdata[22] = 1'b0;
  assign read_if_rdata[23] = 1'b0;
  assign read_if_rdata[24] = 1'b0;
  assign read_if_rdata[25] = 1'b0;
  assign read_if_rdata[26] = 1'b0;
  assign read_if_rdata[27] = 1'b0;
  assign read_if_rdata[28] = 1'b0;
  assign read_if_rdata[29] = 1'b0;
  assign read_if_rdata[30] = 1'b0;
  assign read_if_rdata[31] = 1'b0;
  assign error_flag = 1'b0;
  fifomem_DATASIZE8_ADDRSIZE3_FALLTHROUGH1
       async_fifo_i_fifomem_inst(.wclk (w_clk), .wclken (we), .waddr
       (async_fifo_i_waddr), .wdata (write_if_wdata[7:0]), .wfull
       (fifo_full), .rclk (UNCONNECTED_HIER_Z), .rclken
       (UNCONNECTED_HIER_Z0), .raddr (async_fifo_i_raddr), .rdata
       (read_if_rdata[7:0]));
  rptr_empty_ADDRSIZE3 async_fifo_i_rptr_empty_inst(.rclk (r_clk),
       .rrst_n (r_rst_n), .rinc (read_if_rvalid), .rq2_wptr
       (async_fifo_i_rq2_wptr), .rempty (fifo_empty), .arempty
       (async_fifo_i_n_27), .raddr (async_fifo_i_raddr), .rptr
       (async_fifo_i_rptr));
  wptr_full_ADDRSIZE3 async_fifo_i_wptr_full_inst(.wclk (w_clk),
       .wrst_n (w_rst_n), .winc (we), .wq2_rptr
       (async_fifo_i_wq2_rptr), .wfull (fifo_full), .awfull
       (async_fifo_i_n_17), .waddr (async_fifo_i_waddr), .wptr
       (async_fifo_i_wptr));
  IINR4D0BWP16P90 g206__6783(.A1 (write_if_req), .A2 (write_if_we), .B1
       (fifo_full), .B2 (write_if_rvalid), .ZN (write_if_gnt));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[3] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[3]), .Q
       (async_fifo_i_wq2_rptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[2] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[2]), .Q
       (async_fifo_i_wq2_rptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[1] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[1]), .Q
       (async_fifo_i_wq2_rptr[1]));
  AN2D0BWP16P90 g210__3680(.A1 (write_if_req), .A2 (write_if_we), .Z
       (we));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[2] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[2]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[1] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[1]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[1]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[0] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[0]), .Q
       (async_fifo_i_wq2_rptr[0]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[3] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[3]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[3]));
  INR4D0BWP16P90 g189__1617(.A1 (read_if_req), .B1 (fifo_empty), .B2
       (read_if_rvalid), .B3 (read_if_we), .ZN (read_if_gnt));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[3] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[3]), .Q
       (async_fifo_i_rq2_wptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[2] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[2]), .Q
       (async_fifo_i_rq2_wptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[1] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[1]), .Q
       (async_fifo_i_rq2_wptr[1]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[0] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[0]), .Q
       (async_fifo_i_rq2_wptr[0]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[2] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[2]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[0] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[0]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[0]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[1] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[1]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[1]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[3] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[3]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[0] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[0]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[0]));
  DFCNQD0BWP16P90 write_gnt_dly_reg(.CDN (w_rst_n), .CP (w_clk), .D
       (write_if_gnt), .Q (write_if_rvalid));
  DFCNQD0BWP16P90 read_gnt_dly_reg(.CDN (r_rst_n), .CP (r_clk), .D
       (read_if_gnt), .Q (read_if_rvalid));
endmodule

