
//input ports
add mapped point w_clk w_clk -type PI PI
add mapped point w_rst_n w_rst_n -type PI PI
add mapped point r_clk r_clk -type PI PI
add mapped point r_rst_n r_rst_n -type PI PI
add mapped point read_if.req read_if_req -type PI PI
add mapped point read_if.addr[31] read_if_addr[31] -type PI PI
add mapped point read_if.addr[30] read_if_addr[30] -type PI PI
add mapped point read_if.addr[29] read_if_addr[29] -type PI PI
add mapped point read_if.addr[28] read_if_addr[28] -type PI PI
add mapped point read_if.addr[27] read_if_addr[27] -type PI PI
add mapped point read_if.addr[26] read_if_addr[26] -type PI PI
add mapped point read_if.addr[25] read_if_addr[25] -type PI PI
add mapped point read_if.addr[24] read_if_addr[24] -type PI PI
add mapped point read_if.addr[23] read_if_addr[23] -type PI PI
add mapped point read_if.addr[22] read_if_addr[22] -type PI PI
add mapped point read_if.addr[21] read_if_addr[21] -type PI PI
add mapped point read_if.addr[20] read_if_addr[20] -type PI PI
add mapped point read_if.addr[19] read_if_addr[19] -type PI PI
add mapped point read_if.addr[18] read_if_addr[18] -type PI PI
add mapped point read_if.addr[17] read_if_addr[17] -type PI PI
add mapped point read_if.addr[16] read_if_addr[16] -type PI PI
add mapped point read_if.addr[15] read_if_addr[15] -type PI PI
add mapped point read_if.addr[14] read_if_addr[14] -type PI PI
add mapped point read_if.addr[13] read_if_addr[13] -type PI PI
add mapped point read_if.addr[12] read_if_addr[12] -type PI PI
add mapped point read_if.addr[11] read_if_addr[11] -type PI PI
add mapped point read_if.addr[10] read_if_addr[10] -type PI PI
add mapped point read_if.addr[9] read_if_addr[9] -type PI PI
add mapped point read_if.addr[8] read_if_addr[8] -type PI PI
add mapped point read_if.addr[7] read_if_addr[7] -type PI PI
add mapped point read_if.addr[6] read_if_addr[6] -type PI PI
add mapped point read_if.addr[5] read_if_addr[5] -type PI PI
add mapped point read_if.addr[4] read_if_addr[4] -type PI PI
add mapped point read_if.addr[3] read_if_addr[3] -type PI PI
add mapped point read_if.addr[2] read_if_addr[2] -type PI PI
add mapped point read_if.addr[1] read_if_addr[1] -type PI PI
add mapped point read_if.addr[0] read_if_addr[0] -type PI PI
add mapped point read_if.be[3] read_if_be[3] -type PI PI
add mapped point read_if.be[2] read_if_be[2] -type PI PI
add mapped point read_if.be[1] read_if_be[1] -type PI PI
add mapped point read_if.be[0] read_if_be[0] -type PI PI
add mapped point read_if.we read_if_we -type PI PI
add mapped point write_if.req write_if_req -type PI PI
add mapped point write_if.addr[31] write_if_addr[31] -type PI PI
add mapped point write_if.addr[30] write_if_addr[30] -type PI PI
add mapped point write_if.addr[29] write_if_addr[29] -type PI PI
add mapped point write_if.addr[28] write_if_addr[28] -type PI PI
add mapped point write_if.addr[27] write_if_addr[27] -type PI PI
add mapped point write_if.addr[26] write_if_addr[26] -type PI PI
add mapped point write_if.addr[25] write_if_addr[25] -type PI PI
add mapped point write_if.addr[24] write_if_addr[24] -type PI PI
add mapped point write_if.addr[23] write_if_addr[23] -type PI PI
add mapped point write_if.addr[22] write_if_addr[22] -type PI PI
add mapped point write_if.addr[21] write_if_addr[21] -type PI PI
add mapped point write_if.addr[20] write_if_addr[20] -type PI PI
add mapped point write_if.addr[19] write_if_addr[19] -type PI PI
add mapped point write_if.addr[18] write_if_addr[18] -type PI PI
add mapped point write_if.addr[17] write_if_addr[17] -type PI PI
add mapped point write_if.addr[16] write_if_addr[16] -type PI PI
add mapped point write_if.addr[15] write_if_addr[15] -type PI PI
add mapped point write_if.addr[14] write_if_addr[14] -type PI PI
add mapped point write_if.addr[13] write_if_addr[13] -type PI PI
add mapped point write_if.addr[12] write_if_addr[12] -type PI PI
add mapped point write_if.addr[11] write_if_addr[11] -type PI PI
add mapped point write_if.addr[10] write_if_addr[10] -type PI PI
add mapped point write_if.addr[9] write_if_addr[9] -type PI PI
add mapped point write_if.addr[8] write_if_addr[8] -type PI PI
add mapped point write_if.addr[7] write_if_addr[7] -type PI PI
add mapped point write_if.addr[6] write_if_addr[6] -type PI PI
add mapped point write_if.addr[5] write_if_addr[5] -type PI PI
add mapped point write_if.addr[4] write_if_addr[4] -type PI PI
add mapped point write_if.addr[3] write_if_addr[3] -type PI PI
add mapped point write_if.addr[2] write_if_addr[2] -type PI PI
add mapped point write_if.addr[1] write_if_addr[1] -type PI PI
add mapped point write_if.addr[0] write_if_addr[0] -type PI PI
add mapped point write_if.wdata[31] write_if_wdata[31] -type PI PI
add mapped point write_if.wdata[30] write_if_wdata[30] -type PI PI
add mapped point write_if.wdata[29] write_if_wdata[29] -type PI PI
add mapped point write_if.wdata[28] write_if_wdata[28] -type PI PI
add mapped point write_if.wdata[27] write_if_wdata[27] -type PI PI
add mapped point write_if.wdata[26] write_if_wdata[26] -type PI PI
add mapped point write_if.wdata[25] write_if_wdata[25] -type PI PI
add mapped point write_if.wdata[24] write_if_wdata[24] -type PI PI
add mapped point write_if.wdata[23] write_if_wdata[23] -type PI PI
add mapped point write_if.wdata[22] write_if_wdata[22] -type PI PI
add mapped point write_if.wdata[21] write_if_wdata[21] -type PI PI
add mapped point write_if.wdata[20] write_if_wdata[20] -type PI PI
add mapped point write_if.wdata[19] write_if_wdata[19] -type PI PI
add mapped point write_if.wdata[18] write_if_wdata[18] -type PI PI
add mapped point write_if.wdata[17] write_if_wdata[17] -type PI PI
add mapped point write_if.wdata[16] write_if_wdata[16] -type PI PI
add mapped point write_if.wdata[15] write_if_wdata[15] -type PI PI
add mapped point write_if.wdata[14] write_if_wdata[14] -type PI PI
add mapped point write_if.wdata[13] write_if_wdata[13] -type PI PI
add mapped point write_if.wdata[12] write_if_wdata[12] -type PI PI
add mapped point write_if.wdata[11] write_if_wdata[11] -type PI PI
add mapped point write_if.wdata[10] write_if_wdata[10] -type PI PI
add mapped point write_if.wdata[9] write_if_wdata[9] -type PI PI
add mapped point write_if.wdata[8] write_if_wdata[8] -type PI PI
add mapped point write_if.wdata[7] write_if_wdata[7] -type PI PI
add mapped point write_if.wdata[6] write_if_wdata[6] -type PI PI
add mapped point write_if.wdata[5] write_if_wdata[5] -type PI PI
add mapped point write_if.wdata[4] write_if_wdata[4] -type PI PI
add mapped point write_if.wdata[3] write_if_wdata[3] -type PI PI
add mapped point write_if.wdata[2] write_if_wdata[2] -type PI PI
add mapped point write_if.wdata[1] write_if_wdata[1] -type PI PI
add mapped point write_if.wdata[0] write_if_wdata[0] -type PI PI
add mapped point write_if.we write_if_we -type PI PI
add mapped point write_if.be[3] write_if_be[3] -type PI PI
add mapped point write_if.be[2] write_if_be[2] -type PI PI
add mapped point write_if.be[1] write_if_be[1] -type PI PI
add mapped point write_if.be[0] write_if_be[0] -type PI PI

//output ports
add mapped point error_flag error_flag -type PO PO
add mapped point read_if.gnt read_if_gnt -type PO PO
add mapped point read_if.rvalid read_if_rvalid -type PO PO
add mapped point read_if.rdata[31] read_if_rdata[31] -type PO PO
add mapped point read_if.rdata[30] read_if_rdata[30] -type PO PO
add mapped point read_if.rdata[29] read_if_rdata[29] -type PO PO
add mapped point read_if.rdata[28] read_if_rdata[28] -type PO PO
add mapped point read_if.rdata[27] read_if_rdata[27] -type PO PO
add mapped point read_if.rdata[26] read_if_rdata[26] -type PO PO
add mapped point read_if.rdata[25] read_if_rdata[25] -type PO PO
add mapped point read_if.rdata[24] read_if_rdata[24] -type PO PO
add mapped point read_if.rdata[23] read_if_rdata[23] -type PO PO
add mapped point read_if.rdata[22] read_if_rdata[22] -type PO PO
add mapped point read_if.rdata[21] read_if_rdata[21] -type PO PO
add mapped point read_if.rdata[20] read_if_rdata[20] -type PO PO
add mapped point read_if.rdata[19] read_if_rdata[19] -type PO PO
add mapped point read_if.rdata[18] read_if_rdata[18] -type PO PO
add mapped point read_if.rdata[17] read_if_rdata[17] -type PO PO
add mapped point read_if.rdata[16] read_if_rdata[16] -type PO PO
add mapped point read_if.rdata[15] read_if_rdata[15] -type PO PO
add mapped point read_if.rdata[14] read_if_rdata[14] -type PO PO
add mapped point read_if.rdata[13] read_if_rdata[13] -type PO PO
add mapped point read_if.rdata[12] read_if_rdata[12] -type PO PO
add mapped point read_if.rdata[11] read_if_rdata[11] -type PO PO
add mapped point read_if.rdata[10] read_if_rdata[10] -type PO PO
add mapped point read_if.rdata[9] read_if_rdata[9] -type PO PO
add mapped point read_if.rdata[8] read_if_rdata[8] -type PO PO
add mapped point read_if.rdata[7] read_if_rdata[7] -type PO PO
add mapped point read_if.rdata[6] read_if_rdata[6] -type PO PO
add mapped point read_if.rdata[5] read_if_rdata[5] -type PO PO
add mapped point read_if.rdata[4] read_if_rdata[4] -type PO PO
add mapped point read_if.rdata[3] read_if_rdata[3] -type PO PO
add mapped point read_if.rdata[2] read_if_rdata[2] -type PO PO
add mapped point read_if.rdata[1] read_if_rdata[1] -type PO PO
add mapped point read_if.rdata[0] read_if_rdata[0] -type PO PO
add mapped point write_if.gnt write_if_gnt -type PO PO
add mapped point write_if.rvalid write_if_rvalid -type PO PO
add mapped point write_if.rdata[31] write_if_rdata[31] -type PO PO
add mapped point write_if.rdata[30] write_if_rdata[30] -type PO PO
add mapped point write_if.rdata[29] write_if_rdata[29] -type PO PO
add mapped point write_if.rdata[28] write_if_rdata[28] -type PO PO
add mapped point write_if.rdata[27] write_if_rdata[27] -type PO PO
add mapped point write_if.rdata[26] write_if_rdata[26] -type PO PO
add mapped point write_if.rdata[25] write_if_rdata[25] -type PO PO
add mapped point write_if.rdata[24] write_if_rdata[24] -type PO PO
add mapped point write_if.rdata[23] write_if_rdata[23] -type PO PO
add mapped point write_if.rdata[22] write_if_rdata[22] -type PO PO
add mapped point write_if.rdata[21] write_if_rdata[21] -type PO PO
add mapped point write_if.rdata[20] write_if_rdata[20] -type PO PO
add mapped point write_if.rdata[19] write_if_rdata[19] -type PO PO
add mapped point write_if.rdata[18] write_if_rdata[18] -type PO PO
add mapped point write_if.rdata[17] write_if_rdata[17] -type PO PO
add mapped point write_if.rdata[16] write_if_rdata[16] -type PO PO
add mapped point write_if.rdata[15] write_if_rdata[15] -type PO PO
add mapped point write_if.rdata[14] write_if_rdata[14] -type PO PO
add mapped point write_if.rdata[13] write_if_rdata[13] -type PO PO
add mapped point write_if.rdata[12] write_if_rdata[12] -type PO PO
add mapped point write_if.rdata[11] write_if_rdata[11] -type PO PO
add mapped point write_if.rdata[10] write_if_rdata[10] -type PO PO
add mapped point write_if.rdata[9] write_if_rdata[9] -type PO PO
add mapped point write_if.rdata[8] write_if_rdata[8] -type PO PO
add mapped point write_if.rdata[7] write_if_rdata[7] -type PO PO
add mapped point write_if.rdata[6] write_if_rdata[6] -type PO PO
add mapped point write_if.rdata[5] write_if_rdata[5] -type PO PO
add mapped point write_if.rdata[4] write_if_rdata[4] -type PO PO
add mapped point write_if.rdata[3] write_if_rdata[3] -type PO PO
add mapped point write_if.rdata[2] write_if_rdata[2] -type PO PO
add mapped point write_if.rdata[1] write_if_rdata[1] -type PO PO
add mapped point write_if.rdata[0] write_if_rdata[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point async_fifo_i/fifomem_inst/mem[0][0]/q async_fifo_i_fifomem_inst/mem_reg[0][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[0][1]/q async_fifo_i_fifomem_inst/mem_reg[0][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[0][2]/q async_fifo_i_fifomem_inst/mem_reg[0][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[0][3]/q async_fifo_i_fifomem_inst/mem_reg[0][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[0][4]/q async_fifo_i_fifomem_inst/mem_reg[0][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[0][5]/q async_fifo_i_fifomem_inst/mem_reg[0][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[0][6]/q async_fifo_i_fifomem_inst/mem_reg[0][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[0][7]/q async_fifo_i_fifomem_inst/mem_reg[0][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[1][0]/q async_fifo_i_fifomem_inst/mem_reg[1][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[1][1]/q async_fifo_i_fifomem_inst/mem_reg[1][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[1][2]/q async_fifo_i_fifomem_inst/mem_reg[1][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[1][3]/q async_fifo_i_fifomem_inst/mem_reg[1][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[1][4]/q async_fifo_i_fifomem_inst/mem_reg[1][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[1][5]/q async_fifo_i_fifomem_inst/mem_reg[1][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[1][6]/q async_fifo_i_fifomem_inst/mem_reg[1][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[1][7]/q async_fifo_i_fifomem_inst/mem_reg[1][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[2][0]/q async_fifo_i_fifomem_inst/mem_reg[2][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[2][1]/q async_fifo_i_fifomem_inst/mem_reg[2][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[2][2]/q async_fifo_i_fifomem_inst/mem_reg[2][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[2][3]/q async_fifo_i_fifomem_inst/mem_reg[2][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[2][4]/q async_fifo_i_fifomem_inst/mem_reg[2][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[2][5]/q async_fifo_i_fifomem_inst/mem_reg[2][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[2][6]/q async_fifo_i_fifomem_inst/mem_reg[2][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[2][7]/q async_fifo_i_fifomem_inst/mem_reg[2][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[3][0]/q async_fifo_i_fifomem_inst/mem_reg[3][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[3][1]/q async_fifo_i_fifomem_inst/mem_reg[3][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[3][2]/q async_fifo_i_fifomem_inst/mem_reg[3][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[3][3]/q async_fifo_i_fifomem_inst/mem_reg[3][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[3][4]/q async_fifo_i_fifomem_inst/mem_reg[3][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[3][5]/q async_fifo_i_fifomem_inst/mem_reg[3][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[3][6]/q async_fifo_i_fifomem_inst/mem_reg[3][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[3][7]/q async_fifo_i_fifomem_inst/mem_reg[3][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[4][0]/q async_fifo_i_fifomem_inst/mem_reg[4][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[4][1]/q async_fifo_i_fifomem_inst/mem_reg[4][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[4][2]/q async_fifo_i_fifomem_inst/mem_reg[4][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[4][3]/q async_fifo_i_fifomem_inst/mem_reg[4][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[4][4]/q async_fifo_i_fifomem_inst/mem_reg[4][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[4][5]/q async_fifo_i_fifomem_inst/mem_reg[4][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[4][6]/q async_fifo_i_fifomem_inst/mem_reg[4][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[4][7]/q async_fifo_i_fifomem_inst/mem_reg[4][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[5][0]/q async_fifo_i_fifomem_inst/mem_reg[5][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[5][1]/q async_fifo_i_fifomem_inst/mem_reg[5][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[5][2]/q async_fifo_i_fifomem_inst/mem_reg[5][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[5][3]/q async_fifo_i_fifomem_inst/mem_reg[5][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[5][4]/q async_fifo_i_fifomem_inst/mem_reg[5][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[5][5]/q async_fifo_i_fifomem_inst/mem_reg[5][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[5][6]/q async_fifo_i_fifomem_inst/mem_reg[5][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[5][7]/q async_fifo_i_fifomem_inst/mem_reg[5][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[6][0]/q async_fifo_i_fifomem_inst/mem_reg[6][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[6][1]/q async_fifo_i_fifomem_inst/mem_reg[6][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[6][2]/q async_fifo_i_fifomem_inst/mem_reg[6][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[6][3]/q async_fifo_i_fifomem_inst/mem_reg[6][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[6][4]/q async_fifo_i_fifomem_inst/mem_reg[6][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[6][5]/q async_fifo_i_fifomem_inst/mem_reg[6][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[6][6]/q async_fifo_i_fifomem_inst/mem_reg[6][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[6][7]/q async_fifo_i_fifomem_inst/mem_reg[6][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[7][0]/q async_fifo_i_fifomem_inst/mem_reg[7][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[7][1]/q async_fifo_i_fifomem_inst/mem_reg[7][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[7][2]/q async_fifo_i_fifomem_inst/mem_reg[7][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[7][3]/q async_fifo_i_fifomem_inst/mem_reg[7][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[7][4]/q async_fifo_i_fifomem_inst/mem_reg[7][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[7][5]/q async_fifo_i_fifomem_inst/mem_reg[7][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[7][6]/q async_fifo_i_fifomem_inst/mem_reg[7][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[7][7]/q async_fifo_i_fifomem_inst/mem_reg[7][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[8][0]/q async_fifo_i_fifomem_inst/mem_reg[8][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[8][1]/q async_fifo_i_fifomem_inst/mem_reg[8][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[8][2]/q async_fifo_i_fifomem_inst/mem_reg[8][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[8][3]/q async_fifo_i_fifomem_inst/mem_reg[8][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[8][4]/q async_fifo_i_fifomem_inst/mem_reg[8][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[8][5]/q async_fifo_i_fifomem_inst/mem_reg[8][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[8][6]/q async_fifo_i_fifomem_inst/mem_reg[8][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[8][7]/q async_fifo_i_fifomem_inst/mem_reg[8][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[9][0]/q async_fifo_i_fifomem_inst/mem_reg[9][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[9][1]/q async_fifo_i_fifomem_inst/mem_reg[9][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[9][2]/q async_fifo_i_fifomem_inst/mem_reg[9][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[9][3]/q async_fifo_i_fifomem_inst/mem_reg[9][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[9][4]/q async_fifo_i_fifomem_inst/mem_reg[9][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[9][5]/q async_fifo_i_fifomem_inst/mem_reg[9][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[9][6]/q async_fifo_i_fifomem_inst/mem_reg[9][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[9][7]/q async_fifo_i_fifomem_inst/mem_reg[9][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[10][0]/q async_fifo_i_fifomem_inst/mem_reg[10][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[10][1]/q async_fifo_i_fifomem_inst/mem_reg[10][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[10][2]/q async_fifo_i_fifomem_inst/mem_reg[10][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[10][3]/q async_fifo_i_fifomem_inst/mem_reg[10][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[10][4]/q async_fifo_i_fifomem_inst/mem_reg[10][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[10][5]/q async_fifo_i_fifomem_inst/mem_reg[10][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[10][6]/q async_fifo_i_fifomem_inst/mem_reg[10][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[10][7]/q async_fifo_i_fifomem_inst/mem_reg[10][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[11][0]/q async_fifo_i_fifomem_inst/mem_reg[11][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[11][1]/q async_fifo_i_fifomem_inst/mem_reg[11][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[11][2]/q async_fifo_i_fifomem_inst/mem_reg[11][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[11][3]/q async_fifo_i_fifomem_inst/mem_reg[11][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[11][4]/q async_fifo_i_fifomem_inst/mem_reg[11][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[11][5]/q async_fifo_i_fifomem_inst/mem_reg[11][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[11][6]/q async_fifo_i_fifomem_inst/mem_reg[11][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[11][7]/q async_fifo_i_fifomem_inst/mem_reg[11][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[12][0]/q async_fifo_i_fifomem_inst/mem_reg[12][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[12][1]/q async_fifo_i_fifomem_inst/mem_reg[12][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[12][2]/q async_fifo_i_fifomem_inst/mem_reg[12][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[12][3]/q async_fifo_i_fifomem_inst/mem_reg[12][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[12][4]/q async_fifo_i_fifomem_inst/mem_reg[12][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[12][5]/q async_fifo_i_fifomem_inst/mem_reg[12][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[12][6]/q async_fifo_i_fifomem_inst/mem_reg[12][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[12][7]/q async_fifo_i_fifomem_inst/mem_reg[12][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[13][0]/q async_fifo_i_fifomem_inst/mem_reg[13][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[13][1]/q async_fifo_i_fifomem_inst/mem_reg[13][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[13][2]/q async_fifo_i_fifomem_inst/mem_reg[13][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[13][3]/q async_fifo_i_fifomem_inst/mem_reg[13][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[13][4]/q async_fifo_i_fifomem_inst/mem_reg[13][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[13][5]/q async_fifo_i_fifomem_inst/mem_reg[13][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[13][6]/q async_fifo_i_fifomem_inst/mem_reg[13][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[13][7]/q async_fifo_i_fifomem_inst/mem_reg[13][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[14][0]/q async_fifo_i_fifomem_inst/mem_reg[14][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[14][1]/q async_fifo_i_fifomem_inst/mem_reg[14][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[14][2]/q async_fifo_i_fifomem_inst/mem_reg[14][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[14][3]/q async_fifo_i_fifomem_inst/mem_reg[14][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[14][4]/q async_fifo_i_fifomem_inst/mem_reg[14][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[14][5]/q async_fifo_i_fifomem_inst/mem_reg[14][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[14][6]/q async_fifo_i_fifomem_inst/mem_reg[14][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[14][7]/q async_fifo_i_fifomem_inst/mem_reg[14][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[15][0]/q async_fifo_i_fifomem_inst/mem_reg[15][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[15][1]/q async_fifo_i_fifomem_inst/mem_reg[15][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[15][2]/q async_fifo_i_fifomem_inst/mem_reg[15][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[15][3]/q async_fifo_i_fifomem_inst/mem_reg[15][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[15][4]/q async_fifo_i_fifomem_inst/mem_reg[15][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[15][5]/q async_fifo_i_fifomem_inst/mem_reg[15][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[15][6]/q async_fifo_i_fifomem_inst/mem_reg[15][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[15][7]/q async_fifo_i_fifomem_inst/mem_reg[15][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[16][0]/q async_fifo_i_fifomem_inst/mem_reg[16][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[16][1]/q async_fifo_i_fifomem_inst/mem_reg[16][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[16][2]/q async_fifo_i_fifomem_inst/mem_reg[16][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[16][3]/q async_fifo_i_fifomem_inst/mem_reg[16][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[16][4]/q async_fifo_i_fifomem_inst/mem_reg[16][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[16][5]/q async_fifo_i_fifomem_inst/mem_reg[16][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[16][6]/q async_fifo_i_fifomem_inst/mem_reg[16][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[16][7]/q async_fifo_i_fifomem_inst/mem_reg[16][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[17][0]/q async_fifo_i_fifomem_inst/mem_reg[17][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[17][1]/q async_fifo_i_fifomem_inst/mem_reg[17][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[17][2]/q async_fifo_i_fifomem_inst/mem_reg[17][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[17][3]/q async_fifo_i_fifomem_inst/mem_reg[17][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[17][4]/q async_fifo_i_fifomem_inst/mem_reg[17][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[17][5]/q async_fifo_i_fifomem_inst/mem_reg[17][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[17][6]/q async_fifo_i_fifomem_inst/mem_reg[17][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[17][7]/q async_fifo_i_fifomem_inst/mem_reg[17][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[18][0]/q async_fifo_i_fifomem_inst/mem_reg[18][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[18][1]/q async_fifo_i_fifomem_inst/mem_reg[18][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[18][2]/q async_fifo_i_fifomem_inst/mem_reg[18][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[18][3]/q async_fifo_i_fifomem_inst/mem_reg[18][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[18][4]/q async_fifo_i_fifomem_inst/mem_reg[18][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[18][5]/q async_fifo_i_fifomem_inst/mem_reg[18][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[18][6]/q async_fifo_i_fifomem_inst/mem_reg[18][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[18][7]/q async_fifo_i_fifomem_inst/mem_reg[18][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[19][0]/q async_fifo_i_fifomem_inst/mem_reg[19][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[19][1]/q async_fifo_i_fifomem_inst/mem_reg[19][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[19][2]/q async_fifo_i_fifomem_inst/mem_reg[19][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[19][3]/q async_fifo_i_fifomem_inst/mem_reg[19][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[19][4]/q async_fifo_i_fifomem_inst/mem_reg[19][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[19][5]/q async_fifo_i_fifomem_inst/mem_reg[19][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[19][6]/q async_fifo_i_fifomem_inst/mem_reg[19][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[19][7]/q async_fifo_i_fifomem_inst/mem_reg[19][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[20][0]/q async_fifo_i_fifomem_inst/mem_reg[20][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[20][1]/q async_fifo_i_fifomem_inst/mem_reg[20][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[20][2]/q async_fifo_i_fifomem_inst/mem_reg[20][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[20][3]/q async_fifo_i_fifomem_inst/mem_reg[20][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[20][4]/q async_fifo_i_fifomem_inst/mem_reg[20][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[20][5]/q async_fifo_i_fifomem_inst/mem_reg[20][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[20][6]/q async_fifo_i_fifomem_inst/mem_reg[20][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[20][7]/q async_fifo_i_fifomem_inst/mem_reg[20][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[21][0]/q async_fifo_i_fifomem_inst/mem_reg[21][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[21][1]/q async_fifo_i_fifomem_inst/mem_reg[21][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[21][2]/q async_fifo_i_fifomem_inst/mem_reg[21][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[21][3]/q async_fifo_i_fifomem_inst/mem_reg[21][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[21][4]/q async_fifo_i_fifomem_inst/mem_reg[21][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[21][5]/q async_fifo_i_fifomem_inst/mem_reg[21][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[21][6]/q async_fifo_i_fifomem_inst/mem_reg[21][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[21][7]/q async_fifo_i_fifomem_inst/mem_reg[21][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[22][0]/q async_fifo_i_fifomem_inst/mem_reg[22][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[22][1]/q async_fifo_i_fifomem_inst/mem_reg[22][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[22][2]/q async_fifo_i_fifomem_inst/mem_reg[22][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[22][3]/q async_fifo_i_fifomem_inst/mem_reg[22][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[22][4]/q async_fifo_i_fifomem_inst/mem_reg[22][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[22][5]/q async_fifo_i_fifomem_inst/mem_reg[22][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[22][6]/q async_fifo_i_fifomem_inst/mem_reg[22][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[22][7]/q async_fifo_i_fifomem_inst/mem_reg[22][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[23][0]/q async_fifo_i_fifomem_inst/mem_reg[23][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[23][1]/q async_fifo_i_fifomem_inst/mem_reg[23][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[23][2]/q async_fifo_i_fifomem_inst/mem_reg[23][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[23][3]/q async_fifo_i_fifomem_inst/mem_reg[23][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[23][4]/q async_fifo_i_fifomem_inst/mem_reg[23][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[23][5]/q async_fifo_i_fifomem_inst/mem_reg[23][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[23][6]/q async_fifo_i_fifomem_inst/mem_reg[23][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[23][7]/q async_fifo_i_fifomem_inst/mem_reg[23][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[24][0]/q async_fifo_i_fifomem_inst/mem_reg[24][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[24][1]/q async_fifo_i_fifomem_inst/mem_reg[24][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[24][2]/q async_fifo_i_fifomem_inst/mem_reg[24][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[24][3]/q async_fifo_i_fifomem_inst/mem_reg[24][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[24][4]/q async_fifo_i_fifomem_inst/mem_reg[24][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[24][5]/q async_fifo_i_fifomem_inst/mem_reg[24][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[24][6]/q async_fifo_i_fifomem_inst/mem_reg[24][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[24][7]/q async_fifo_i_fifomem_inst/mem_reg[24][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[25][0]/q async_fifo_i_fifomem_inst/mem_reg[25][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[25][1]/q async_fifo_i_fifomem_inst/mem_reg[25][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[25][2]/q async_fifo_i_fifomem_inst/mem_reg[25][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[25][3]/q async_fifo_i_fifomem_inst/mem_reg[25][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[25][4]/q async_fifo_i_fifomem_inst/mem_reg[25][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[25][5]/q async_fifo_i_fifomem_inst/mem_reg[25][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[25][6]/q async_fifo_i_fifomem_inst/mem_reg[25][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[25][7]/q async_fifo_i_fifomem_inst/mem_reg[25][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[26][0]/q async_fifo_i_fifomem_inst/mem_reg[26][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[26][1]/q async_fifo_i_fifomem_inst/mem_reg[26][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[26][2]/q async_fifo_i_fifomem_inst/mem_reg[26][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[26][3]/q async_fifo_i_fifomem_inst/mem_reg[26][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[26][4]/q async_fifo_i_fifomem_inst/mem_reg[26][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[26][5]/q async_fifo_i_fifomem_inst/mem_reg[26][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[26][6]/q async_fifo_i_fifomem_inst/mem_reg[26][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[26][7]/q async_fifo_i_fifomem_inst/mem_reg[26][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[27][0]/q async_fifo_i_fifomem_inst/mem_reg[27][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[27][1]/q async_fifo_i_fifomem_inst/mem_reg[27][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[27][2]/q async_fifo_i_fifomem_inst/mem_reg[27][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[27][3]/q async_fifo_i_fifomem_inst/mem_reg[27][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[27][4]/q async_fifo_i_fifomem_inst/mem_reg[27][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[27][5]/q async_fifo_i_fifomem_inst/mem_reg[27][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[27][6]/q async_fifo_i_fifomem_inst/mem_reg[27][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[27][7]/q async_fifo_i_fifomem_inst/mem_reg[27][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[28][0]/q async_fifo_i_fifomem_inst/mem_reg[28][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[28][1]/q async_fifo_i_fifomem_inst/mem_reg[28][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[28][2]/q async_fifo_i_fifomem_inst/mem_reg[28][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[28][3]/q async_fifo_i_fifomem_inst/mem_reg[28][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[28][4]/q async_fifo_i_fifomem_inst/mem_reg[28][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[28][5]/q async_fifo_i_fifomem_inst/mem_reg[28][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[28][6]/q async_fifo_i_fifomem_inst/mem_reg[28][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[28][7]/q async_fifo_i_fifomem_inst/mem_reg[28][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[29][0]/q async_fifo_i_fifomem_inst/mem_reg[29][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[29][1]/q async_fifo_i_fifomem_inst/mem_reg[29][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[29][2]/q async_fifo_i_fifomem_inst/mem_reg[29][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[29][3]/q async_fifo_i_fifomem_inst/mem_reg[29][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[29][4]/q async_fifo_i_fifomem_inst/mem_reg[29][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[29][5]/q async_fifo_i_fifomem_inst/mem_reg[29][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[29][6]/q async_fifo_i_fifomem_inst/mem_reg[29][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[29][7]/q async_fifo_i_fifomem_inst/mem_reg[29][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[30][0]/q async_fifo_i_fifomem_inst/mem_reg[30][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[30][1]/q async_fifo_i_fifomem_inst/mem_reg[30][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[30][2]/q async_fifo_i_fifomem_inst/mem_reg[30][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[30][3]/q async_fifo_i_fifomem_inst/mem_reg[30][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[30][4]/q async_fifo_i_fifomem_inst/mem_reg[30][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[30][5]/q async_fifo_i_fifomem_inst/mem_reg[30][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[30][6]/q async_fifo_i_fifomem_inst/mem_reg[30][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[30][7]/q async_fifo_i_fifomem_inst/mem_reg[30][7]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[31][0]/q async_fifo_i_fifomem_inst/mem_reg[31][0]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[31][1]/q async_fifo_i_fifomem_inst/mem_reg[31][1]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[31][2]/q async_fifo_i_fifomem_inst/mem_reg[31][2]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[31][3]/q async_fifo_i_fifomem_inst/mem_reg[31][3]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[31][4]/q async_fifo_i_fifomem_inst/mem_reg[31][4]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[31][5]/q async_fifo_i_fifomem_inst/mem_reg[31][5]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[31][6]/q async_fifo_i_fifomem_inst/mem_reg[31][6]/Q -type DFF DFF
add mapped point async_fifo_i/fifomem_inst/mem[31][7]/q async_fifo_i_fifomem_inst/mem_reg[31][7]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rptr[4]/q async_fifo_i_rptr_empty_inst/rptr_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rptr[3]/q async_fifo_i_rptr_empty_inst/rptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rptr[2]/q async_fifo_i_rptr_empty_inst/rptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rptr[1]/q async_fifo_i_rptr_empty_inst/rptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rptr[0]/q async_fifo_i_rptr_empty_inst/rptr_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rempty/q async_fifo_i_rptr_empty_inst/rempty_reg/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[4]/q async_fifo_i_rptr_empty_inst/rbin_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[5]/q async_fifo_i_rptr_empty_inst/rbin_reg[5]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[3]/q async_fifo_i_rptr_empty_inst/rbin_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[0]/q async_fifo_i_rptr_empty_inst/rbin_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[1]/q async_fifo_i_rptr_empty_inst/rbin_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/rptr_empty_inst/rbin[2]/q async_fifo_i_rptr_empty_inst/rbin_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wptr[4]/q async_fifo_i_wptr_full_inst/wptr_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wptr[3]/q async_fifo_i_wptr_full_inst/wptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wptr[2]/q async_fifo_i_wptr_full_inst/wptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wptr[1]/q async_fifo_i_wptr_full_inst/wptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wptr[0]/q async_fifo_i_wptr_full_inst/wptr_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wfull/q async_fifo_i_wptr_full_inst/wfull_reg/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[4]/q async_fifo_i_wptr_full_inst/wbin_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[5]/q async_fifo_i_wptr_full_inst/wbin_reg[5]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[3]/q async_fifo_i_wptr_full_inst/wbin_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[0]/q async_fifo_i_wptr_full_inst/wbin_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[1]/q async_fifo_i_wptr_full_inst/wbin_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/wptr_full_inst/wbin[2]/q async_fifo_i_wptr_full_inst/wbin_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[5]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[5]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[4]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[3]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[2]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[1]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[4]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[3]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq2_rptr[0]/q async_fifo_i_sync_r2w_inst_wq2_rptr_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[2]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[1]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[5]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[5]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[5]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[5]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[4]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[3]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[2]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[1]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq2_wptr[0]/q async_fifo_i_sync_w2r_inst_rq2_wptr_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[4]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[4]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[2]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[2]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[0]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[0]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[1]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[1]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[3]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[3]/Q -type DFF DFF
add mapped point async_fifo_i/sync_w2r_inst/rq1_wptr[5]/q async_fifo_i_sync_w2r_inst_rq1_wptr_reg[5]/Q -type DFF DFF
add mapped point async_fifo_i/sync_r2w_inst/wq1_rptr[0]/q async_fifo_i_sync_r2w_inst_wq1_rptr_reg[0]/Q -type DFF DFF
add mapped point write_gnt_dly/q write_gnt_dly_reg/Q -type DFF DFF
add mapped point read_gnt_dly/q read_gnt_dly_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
