
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Jun 16 2025 11:28:24 UTC (Jun 16 2025 11:28:24 UTC)

// Verification Directory fv/ipr 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_3(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_4(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_5(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_6(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_7(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_8(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_9(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_10(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_11(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_12(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_13(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_14(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module RC_CG_MOD_15(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module fifomem_DATASIZE8_ADDRSIZE4_FALLTHROUGH1(wclk, wclken, waddr,
     wdata, wfull, rclk, rclken, raddr, rdata);
  input wclk, wclken, wfull, rclk, rclken;
  input [3:0] waddr, raddr;
  input [7:0] wdata;
  output [7:0] rdata;
  wire wclk, wclken, wfull, rclk, rclken;
  wire [3:0] waddr, raddr;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[15] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_123, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_213, n_214, n_215, n_216, n_217, n_218;
  wire n_219, n_220, n_221, n_222, n_223, n_224, n_226, n_228;
  wire n_240, n_241, rc_gclk, rc_gclk_450, rc_gclk_452, rc_gclk_454,
       rc_gclk_456, rc_gclk_458;
  wire rc_gclk_460, rc_gclk_462, rc_gclk_464, rc_gclk_466, rc_gclk_468,
       rc_gclk_470, rc_gclk_472, rc_gclk_474;
  wire rc_gclk_476, rc_gclk_478;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_228), .ck_in (wclk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_1 RC_CG_HIER_INST1(.enable (n_213), .ck_in (wclk), .ck_out
       (rc_gclk_450), .test (1'b0));
  RC_CG_MOD_2 RC_CG_HIER_INST2(.enable (n_214), .ck_in (wclk), .ck_out
       (rc_gclk_452), .test (1'b0));
  RC_CG_MOD_3 RC_CG_HIER_INST3(.enable (n_215), .ck_in (wclk), .ck_out
       (rc_gclk_454), .test (1'b0));
  RC_CG_MOD_4 RC_CG_HIER_INST4(.enable (n_216), .ck_in (wclk), .ck_out
       (rc_gclk_456), .test (1'b0));
  RC_CG_MOD_5 RC_CG_HIER_INST5(.enable (n_217), .ck_in (wclk), .ck_out
       (rc_gclk_458), .test (1'b0));
  RC_CG_MOD_6 RC_CG_HIER_INST6(.enable (n_218), .ck_in (wclk), .ck_out
       (rc_gclk_460), .test (1'b0));
  RC_CG_MOD_7 RC_CG_HIER_INST7(.enable (n_219), .ck_in (wclk), .ck_out
       (rc_gclk_462), .test (1'b0));
  RC_CG_MOD_8 RC_CG_HIER_INST8(.enable (n_220), .ck_in (wclk), .ck_out
       (rc_gclk_464), .test (1'b0));
  RC_CG_MOD_9 RC_CG_HIER_INST9(.enable (n_221), .ck_in (wclk), .ck_out
       (rc_gclk_466), .test (1'b0));
  RC_CG_MOD_10 RC_CG_HIER_INST10(.enable (n_222), .ck_in (wclk),
       .ck_out (rc_gclk_468), .test (1'b0));
  RC_CG_MOD_11 RC_CG_HIER_INST11(.enable (n_223), .ck_in (wclk),
       .ck_out (rc_gclk_470), .test (1'b0));
  RC_CG_MOD_12 RC_CG_HIER_INST12(.enable (n_224), .ck_in (wclk),
       .ck_out (rc_gclk_472), .test (1'b0));
  RC_CG_MOD_13 RC_CG_HIER_INST13(.enable (n_241), .ck_in (wclk),
       .ck_out (rc_gclk_474), .test (1'b0));
  RC_CG_MOD_14 RC_CG_HIER_INST14(.enable (n_226), .ck_in (wclk),
       .ck_out (rc_gclk_476), .test (1'b0));
  RC_CG_MOD_15 RC_CG_HIER_INST15(.enable (n_240), .ck_in (wclk),
       .ck_out (rc_gclk_478), .test (1'b0));
  INVSKND12BWP16P90LVT g1046(.I (wclken), .ZN (n_203));
  DFQND1BWP16P90LVT \mem_reg[0][0] (.CP (rc_gclk), .D (wdata[0]), .QN
       (\mem[0] [0]));
  DFQD2BWP16P90LVT \mem_reg[0][1] (.CP (rc_gclk), .D (wdata[1]), .Q
       (\mem[0] [1]));
  DFQD2BWP16P90LVT \mem_reg[0][2] (.CP (rc_gclk), .D (wdata[2]), .Q
       (\mem[0] [2]));
  DFQND1BWP16P90LVT \mem_reg[0][3] (.CP (rc_gclk), .D (wdata[3]), .QN
       (\mem[0] [3]));
  DFQD2BWP16P90LVT \mem_reg[0][4] (.CP (rc_gclk), .D (wdata[4]), .Q
       (\mem[0] [4]));
  DFQND1BWP16P90LVT \mem_reg[0][5] (.CP (rc_gclk), .D (wdata[5]), .QN
       (\mem[0] [5]));
  DFQD4BWP16P90LVT \mem_reg[0][6] (.CP (rc_gclk), .D (wdata[6]), .Q
       (\mem[0] [6]));
  DFQD2BWP16P90LVT \mem_reg[0][7] (.CP (rc_gclk), .D (wdata[7]), .Q
       (\mem[0] [7]));
  DFQND1BWP16P90LVT \mem_reg[1][0] (.CP (rc_gclk_478), .D (wdata[0]),
       .QN (\mem[1] [0]));
  DFQND1BWP16P90LVT \mem_reg[1][1] (.CP (rc_gclk_478), .D (wdata[1]),
       .QN (\mem[1] [1]));
  DFQD2BWP16P90LVT \mem_reg[1][2] (.CP (rc_gclk_478), .D (wdata[2]), .Q
       (\mem[1] [2]));
  DFQD4BWP16P90LVT \mem_reg[1][3] (.CP (rc_gclk_478), .D (wdata[3]), .Q
       (\mem[1] [3]));
  DFQD4BWP16P90LVT \mem_reg[1][4] (.CP (rc_gclk_478), .D (wdata[4]), .Q
       (\mem[1] [4]));
  DFQD2BWP16P90LVT \mem_reg[1][5] (.CP (rc_gclk_478), .D (wdata[5]), .Q
       (\mem[1] [5]));
  DFQND1BWP16P90LVT \mem_reg[1][6] (.CP (rc_gclk_478), .D (wdata[6]),
       .QN (\mem[1] [6]));
  DFQD2BWP16P90LVT \mem_reg[1][7] (.CP (rc_gclk_478), .D (wdata[7]), .Q
       (\mem[1] [7]));
  DFQD4BWP16P90LVT \mem_reg[2][0] (.CP (rc_gclk_476), .D (wdata[0]), .Q
       (\mem[2] [0]));
  DFQD2BWP16P90LVT \mem_reg[2][1] (.CP (rc_gclk_476), .D (wdata[1]), .Q
       (\mem[2] [1]));
  DFQD4BWP16P90LVT \mem_reg[2][2] (.CP (rc_gclk_476), .D (wdata[2]), .Q
       (\mem[2] [2]));
  DFQND1BWP16P90LVT \mem_reg[2][3] (.CP (rc_gclk_476), .D (wdata[3]),
       .QN (\mem[2] [3]));
  DFQND1BWP16P90LVT \mem_reg[2][4] (.CP (rc_gclk_476), .D (wdata[4]),
       .QN (\mem[2] [4]));
  DFQND1BWP16P90LVT \mem_reg[2][5] (.CP (rc_gclk_476), .D (wdata[5]),
       .QN (\mem[2] [5]));
  DFQD4BWP16P90LVT \mem_reg[2][6] (.CP (rc_gclk_476), .D (wdata[6]), .Q
       (\mem[2] [6]));
  DFQD4BWP16P90LVT \mem_reg[2][7] (.CP (rc_gclk_476), .D (wdata[7]), .Q
       (\mem[2] [7]));
  DFQND1BWP16P90LVT \mem_reg[3][0] (.CP (rc_gclk_474), .D (wdata[0]),
       .QN (\mem[3] [0]));
  DFQND1BWP16P90LVT \mem_reg[3][1] (.CP (rc_gclk_474), .D (wdata[1]),
       .QN (\mem[3] [1]));
  DFQD4BWP16P90LVT \mem_reg[3][2] (.CP (rc_gclk_474), .D (wdata[2]), .Q
       (\mem[3] [2]));
  DFQND1BWP16P90LVT \mem_reg[3][3] (.CP (rc_gclk_474), .D (wdata[3]),
       .QN (\mem[3] [3]));
  DFQD2BWP16P90LVT \mem_reg[3][4] (.CP (rc_gclk_474), .D (wdata[4]), .Q
       (\mem[3] [4]));
  DFQD4BWP16P90LVT \mem_reg[3][5] (.CP (rc_gclk_474), .D (wdata[5]), .Q
       (\mem[3] [5]));
  DFQND1BWP16P90LVT \mem_reg[3][6] (.CP (rc_gclk_474), .D (wdata[6]),
       .QN (\mem[3] [6]));
  DFQD2BWP16P90LVT \mem_reg[3][7] (.CP (rc_gclk_474), .D (wdata[7]), .Q
       (\mem[3] [7]));
  DFQD4BWP16P90LVT \mem_reg[4][0] (.CP (rc_gclk_472), .D (wdata[0]), .Q
       (\mem[4] [0]));
  DFQD2BWP16P90LVT \mem_reg[4][1] (.CP (rc_gclk_472), .D (wdata[1]), .Q
       (\mem[4] [1]));
  DFQD2BWP16P90LVT \mem_reg[4][2] (.CP (rc_gclk_472), .D (wdata[2]), .Q
       (\mem[4] [2]));
  DFQND1BWP16P90LVT \mem_reg[4][3] (.CP (rc_gclk_472), .D (wdata[3]),
       .QN (\mem[4] [3]));
  DFQD2BWP16P90LVT \mem_reg[4][4] (.CP (rc_gclk_472), .D (wdata[4]), .Q
       (\mem[4] [4]));
  DFQND1BWP16P90LVT \mem_reg[4][5] (.CP (rc_gclk_472), .D (wdata[5]),
       .QN (\mem[4] [5]));
  DFQND1BWP16P90LVT \mem_reg[4][6] (.CP (rc_gclk_472), .D (wdata[6]),
       .QN (\mem[4] [6]));
  DFQD2BWP16P90LVT \mem_reg[4][7] (.CP (rc_gclk_472), .D (wdata[7]), .Q
       (\mem[4] [7]));
  DFQND1BWP16P90LVT \mem_reg[5][0] (.CP (rc_gclk_470), .D (wdata[0]),
       .QN (\mem[5] [0]));
  DFQND1BWP16P90LVT \mem_reg[5][1] (.CP (rc_gclk_470), .D (wdata[1]),
       .QN (\mem[5] [1]));
  DFQD2BWP16P90LVT \mem_reg[5][2] (.CP (rc_gclk_470), .D (wdata[2]), .Q
       (\mem[5] [2]));
  DFQD2BWP16P90LVT \mem_reg[5][3] (.CP (rc_gclk_470), .D (wdata[3]), .Q
       (\mem[5] [3]));
  DFQD2BWP16P90LVT \mem_reg[5][4] (.CP (rc_gclk_470), .D (wdata[4]), .Q
       (\mem[5] [4]));
  DFQD4BWP16P90LVT \mem_reg[5][5] (.CP (rc_gclk_470), .D (wdata[5]), .Q
       (\mem[5] [5]));
  DFQD4BWP16P90LVT \mem_reg[5][6] (.CP (rc_gclk_470), .D (wdata[6]), .Q
       (\mem[5] [6]));
  DFQD2BWP16P90LVT \mem_reg[5][7] (.CP (rc_gclk_470), .D (wdata[7]), .Q
       (\mem[5] [7]));
  DFQND1BWP16P90LVT \mem_reg[6][0] (.CP (rc_gclk_468), .D (wdata[0]),
       .QN (\mem[6] [0]));
  DFQND1BWP16P90LVT \mem_reg[6][1] (.CP (rc_gclk_468), .D (wdata[1]),
       .QN (\mem[6] [1]));
  DFQD2BWP16P90LVT \mem_reg[6][2] (.CP (rc_gclk_468), .D (wdata[2]), .Q
       (\mem[6] [2]));
  DFQND1BWP16P90LVT \mem_reg[6][3] (.CP (rc_gclk_468), .D (wdata[3]),
       .QN (\mem[6] [3]));
  DFQND1BWP16P90LVT \mem_reg[6][4] (.CP (rc_gclk_468), .D (wdata[4]),
       .QN (\mem[6] [4]));
  DFQD2BWP16P90LVT \mem_reg[6][5] (.CP (rc_gclk_468), .D (wdata[5]), .Q
       (\mem[6] [5]));
  DFQND1BWP16P90LVT \mem_reg[6][6] (.CP (rc_gclk_468), .D (wdata[6]),
       .QN (\mem[6] [6]));
  DFQD2BWP16P90LVT \mem_reg[6][7] (.CP (rc_gclk_468), .D (wdata[7]), .Q
       (\mem[6] [7]));
  DFQND1BWP16P90LVT \mem_reg[7][0] (.CP (rc_gclk_466), .D (wdata[0]),
       .QN (\mem[7] [0]));
  DFQND1BWP16P90LVT \mem_reg[7][1] (.CP (rc_gclk_466), .D (wdata[1]),
       .QN (\mem[7] [1]));
  DFQD4BWP16P90LVT \mem_reg[7][2] (.CP (rc_gclk_466), .D (wdata[2]), .Q
       (\mem[7] [2]));
  DFQND1BWP16P90LVT \mem_reg[7][3] (.CP (rc_gclk_466), .D (wdata[3]),
       .QN (\mem[7] [3]));
  DFQD2BWP16P90LVT \mem_reg[7][4] (.CP (rc_gclk_466), .D (wdata[4]), .Q
       (\mem[7] [4]));
  DFQD4BWP16P90LVT \mem_reg[7][5] (.CP (rc_gclk_466), .D (wdata[5]), .Q
       (\mem[7] [5]));
  DFQD4BWP16P90LVT \mem_reg[7][6] (.CP (rc_gclk_466), .D (wdata[6]), .Q
       (\mem[7] [6]));
  DFQD4BWP16P90LVT \mem_reg[7][7] (.CP (rc_gclk_466), .D (wdata[7]), .Q
       (\mem[7] [7]));
  DFQND1BWP16P90LVT \mem_reg[8][0] (.CP (rc_gclk_464), .D (wdata[0]),
       .QN (\mem[8] [0]));
  DFQND1BWP16P90LVT \mem_reg[8][1] (.CP (rc_gclk_464), .D (wdata[1]),
       .QN (\mem[8] [1]));
  DFQND1BWP16P90LVT \mem_reg[8][2] (.CP (rc_gclk_464), .D (wdata[2]),
       .QN (\mem[8] [2]));
  DFQND1BWP16P90LVT \mem_reg[8][3] (.CP (rc_gclk_464), .D (wdata[3]),
       .QN (\mem[8] [3]));
  DFQND1BWP16P90LVT \mem_reg[8][4] (.CP (rc_gclk_464), .D (wdata[4]),
       .QN (\mem[8] [4]));
  DFQND1BWP16P90LVT \mem_reg[8][5] (.CP (rc_gclk_464), .D (wdata[5]),
       .QN (\mem[8] [5]));
  DFQD2BWP16P90LVT \mem_reg[8][6] (.CP (rc_gclk_464), .D (wdata[6]), .Q
       (\mem[8] [6]));
  DFQND1BWP16P90LVT \mem_reg[8][7] (.CP (rc_gclk_464), .D (wdata[7]),
       .QN (\mem[8] [7]));
  DFQD4BWP16P90LVT \mem_reg[9][0] (.CP (rc_gclk_462), .D (wdata[0]), .Q
       (\mem[9] [0]));
  DFQD4BWP16P90LVT \mem_reg[9][1] (.CP (rc_gclk_462), .D (wdata[1]), .Q
       (\mem[9] [1]));
  DFQND1BWP16P90LVT \mem_reg[9][2] (.CP (rc_gclk_462), .D (wdata[2]),
       .QN (\mem[9] [2]));
  DFQND1BWP16P90LVT \mem_reg[9][3] (.CP (rc_gclk_462), .D (wdata[3]),
       .QN (\mem[9] [3]));
  DFQND1BWP16P90LVT \mem_reg[9][4] (.CP (rc_gclk_462), .D (wdata[4]),
       .QN (\mem[9] [4]));
  DFQD2BWP16P90LVT \mem_reg[9][5] (.CP (rc_gclk_462), .D (wdata[5]), .Q
       (\mem[9] [5]));
  DFQD2BWP16P90LVT \mem_reg[9][6] (.CP (rc_gclk_462), .D (wdata[6]), .Q
       (\mem[9] [6]));
  DFQND1BWP16P90LVT \mem_reg[9][7] (.CP (rc_gclk_462), .D (wdata[7]),
       .QN (\mem[9] [7]));
  DFQD4BWP16P90LVT \mem_reg[10][0] (.CP (rc_gclk_460), .D (wdata[0]),
       .Q (\mem[10] [0]));
  DFQND1BWP16P90LVT \mem_reg[10][1] (.CP (rc_gclk_460), .D (wdata[1]),
       .QN (\mem[10] [1]));
  DFQND1BWP16P90LVT \mem_reg[10][2] (.CP (rc_gclk_460), .D (wdata[2]),
       .QN (\mem[10] [2]));
  DFQND1BWP16P90LVT \mem_reg[10][3] (.CP (rc_gclk_460), .D (wdata[3]),
       .QN (\mem[10] [3]));
  DFQND1BWP16P90LVT \mem_reg[10][4] (.CP (rc_gclk_460), .D (wdata[4]),
       .QN (\mem[10] [4]));
  DFQND1BWP16P90LVT \mem_reg[10][5] (.CP (rc_gclk_460), .D (wdata[5]),
       .QN (\mem[10] [5]));
  DFQD4BWP16P90LVT \mem_reg[10][6] (.CP (rc_gclk_460), .D (wdata[6]),
       .Q (\mem[10] [6]));
  DFQND1BWP16P90LVT \mem_reg[10][7] (.CP (rc_gclk_460), .D (wdata[7]),
       .QN (\mem[10] [7]));
  DFQND1BWP16P90LVT \mem_reg[11][0] (.CP (rc_gclk_458), .D (wdata[0]),
       .QN (\mem[11] [0]));
  DFQD2BWP16P90LVT \mem_reg[11][1] (.CP (rc_gclk_458), .D (wdata[1]),
       .Q (\mem[11] [1]));
  DFQND1BWP16P90LVT \mem_reg[11][2] (.CP (rc_gclk_458), .D (wdata[2]),
       .QN (\mem[11] [2]));
  DFQND1BWP16P90LVT \mem_reg[11][3] (.CP (rc_gclk_458), .D (wdata[3]),
       .QN (\mem[11] [3]));
  DFQD2BWP16P90LVT \mem_reg[11][4] (.CP (rc_gclk_458), .D (wdata[4]),
       .Q (\mem[11] [4]));
  DFQND1BWP16P90LVT \mem_reg[11][5] (.CP (rc_gclk_458), .D (wdata[5]),
       .QN (\mem[11] [5]));
  DFQD4BWP16P90LVT \mem_reg[11][6] (.CP (rc_gclk_458), .D (wdata[6]),
       .Q (\mem[11] [6]));
  DFQND1BWP16P90LVT \mem_reg[11][7] (.CP (rc_gclk_458), .D (wdata[7]),
       .QN (\mem[11] [7]));
  DFQND1BWP16P90LVT \mem_reg[12][0] (.CP (rc_gclk_456), .D (wdata[0]),
       .QN (\mem[12] [0]));
  DFQND1BWP16P90LVT \mem_reg[12][1] (.CP (rc_gclk_456), .D (wdata[1]),
       .QN (\mem[12] [1]));
  DFQND1BWP16P90LVT \mem_reg[12][2] (.CP (rc_gclk_456), .D (wdata[2]),
       .QN (\mem[12] [2]));
  DFQND1BWP16P90LVT \mem_reg[12][3] (.CP (rc_gclk_456), .D (wdata[3]),
       .QN (\mem[12] [3]));
  DFQND1BWP16P90LVT \mem_reg[12][4] (.CP (rc_gclk_456), .D (wdata[4]),
       .QN (\mem[12] [4]));
  DFQND1BWP16P90LVT \mem_reg[12][5] (.CP (rc_gclk_456), .D (wdata[5]),
       .QN (\mem[12] [5]));
  DFQND1BWP16P90LVT \mem_reg[12][6] (.CP (rc_gclk_456), .D (wdata[6]),
       .QN (\mem[12] [6]));
  DFQND1BWP16P90LVT \mem_reg[12][7] (.CP (rc_gclk_456), .D (wdata[7]),
       .QN (\mem[12] [7]));
  DFQND1BWP16P90LVT \mem_reg[13][0] (.CP (rc_gclk_454), .D (wdata[0]),
       .QN (\mem[13] [0]));
  DFQD2BWP16P90LVT \mem_reg[13][1] (.CP (rc_gclk_454), .D (wdata[1]),
       .Q (\mem[13] [1]));
  DFQND1BWP16P90LVT \mem_reg[13][2] (.CP (rc_gclk_454), .D (wdata[2]),
       .QN (\mem[13] [2]));
  DFQND1BWP16P90LVT \mem_reg[13][3] (.CP (rc_gclk_454), .D (wdata[3]),
       .QN (\mem[13] [3]));
  DFQND1BWP16P90LVT \mem_reg[13][4] (.CP (rc_gclk_454), .D (wdata[4]),
       .QN (\mem[13] [4]));
  DFQD2BWP16P90LVT \mem_reg[13][5] (.CP (rc_gclk_454), .D (wdata[5]),
       .Q (\mem[13] [5]));
  DFQND1BWP16P90LVT \mem_reg[13][6] (.CP (rc_gclk_454), .D (wdata[6]),
       .QN (\mem[13] [6]));
  DFQND1BWP16P90LVT \mem_reg[13][7] (.CP (rc_gclk_454), .D (wdata[7]),
       .QN (\mem[13] [7]));
  DFQND1BWP16P90LVT \mem_reg[14][0] (.CP (rc_gclk_452), .D (wdata[0]),
       .QN (\mem[14] [0]));
  DFQD2BWP16P90LVT \mem_reg[14][1] (.CP (rc_gclk_452), .D (wdata[1]),
       .Q (\mem[14] [1]));
  DFQND1BWP16P90LVT \mem_reg[14][2] (.CP (rc_gclk_452), .D (wdata[2]),
       .QN (\mem[14] [2]));
  DFQD4BWP16P90LVT \mem_reg[14][3] (.CP (rc_gclk_452), .D (wdata[3]),
       .Q (\mem[14] [3]));
  DFQND1BWP16P90LVT \mem_reg[14][4] (.CP (rc_gclk_452), .D (wdata[4]),
       .QN (\mem[14] [4]));
  DFQND1BWP16P90LVT \mem_reg[14][5] (.CP (rc_gclk_452), .D (wdata[5]),
       .QN (\mem[14] [5]));
  DFQND1BWP16P90LVT \mem_reg[14][6] (.CP (rc_gclk_452), .D (wdata[6]),
       .QN (\mem[14] [6]));
  DFQND1BWP16P90LVT \mem_reg[14][7] (.CP (rc_gclk_452), .D (wdata[7]),
       .QN (\mem[14] [7]));
  DFQND1BWP16P90LVT \mem_reg[15][0] (.CP (rc_gclk_450), .D (wdata[0]),
       .QN (\mem[15] [0]));
  DFQD2BWP16P90LVT \mem_reg[15][1] (.CP (rc_gclk_450), .D (wdata[1]),
       .Q (\mem[15] [1]));
  DFQND1BWP16P90LVT \mem_reg[15][2] (.CP (rc_gclk_450), .D (wdata[2]),
       .QN (\mem[15] [2]));
  DFQD4BWP16P90LVT \mem_reg[15][3] (.CP (rc_gclk_450), .D (wdata[3]),
       .Q (\mem[15] [3]));
  DFQD4BWP16P90LVT \mem_reg[15][4] (.CP (rc_gclk_450), .D (wdata[4]),
       .Q (\mem[15] [4]));
  DFQD4BWP16P90LVT \mem_reg[15][5] (.CP (rc_gclk_450), .D (wdata[5]),
       .Q (\mem[15] [5]));
  DFQND1BWP16P90LVT \mem_reg[15][6] (.CP (rc_gclk_450), .D (wdata[6]),
       .QN (\mem[15] [6]));
  DFQND1BWP16P90LVT \mem_reg[15][7] (.CP (rc_gclk_450), .D (wdata[7]),
       .QN (\mem[15] [7]));
  ND3OPTPAD2BWP16P90LVT g4297__2398(.A1 (n_199), .A2 (n_188), .A3
       (n_169), .ZN (rdata[3]));
  ND3OPTPAD2BWP16P90LVT g4298__5107(.A1 (n_197), .A2 (n_171), .A3
       (n_178), .ZN (rdata[7]));
  ND2SKNBD2BWP16P90LVT g4299__6260(.A1 (n_201), .A2 (n_198), .ZN
       (rdata[5]));
  ND3OPTPAD2BWP16P90LVT g4300__4319(.A1 (n_202), .A2 (n_172), .A3
       (n_193), .ZN (rdata[0]));
  ND3SKNBD1BWP16P90LVT g4301__8428(.A1 (n_200), .A2 (n_181), .A3
       (n_167), .ZN (rdata[6]));
  ND3OPTPAD2BWP16P90LVT g4302__5526(.A1 (n_196), .A2 (n_166), .A3
       (n_182), .ZN (rdata[1]));
  ND3OPTPAD1BWP16P90LVT g4303__6783(.A1 (n_195), .A2 (n_176), .A3
       (n_192), .ZN (rdata[2]));
  ND3OPTPAD2BWP16P90LVT g4304__3680(.A1 (n_194), .A2 (n_190), .A3
       (n_179), .ZN (rdata[4]));
  NR3OPTPAD2BWP16P90LVT g4305__1617(.A1 (n_184), .A2 (n_139), .A3
       (n_160), .ZN (n_202));
  NR3OPTPAD2BWP16P90LVT g4306__2802(.A1 (n_177), .A2 (n_144), .A3
       (n_145), .ZN (n_201));
  NR2SKPBD3BWP16P90LVT g4307__1705(.A1 (n_189), .A2 (n_183), .ZN
       (n_200));
  NR3OPTPAD2BWP16P90LVT g4308__5122(.A1 (n_168), .A2 (n_165), .A3
       (n_130), .ZN (n_199));
  NR3OPTPAD2BWP16P90LVT g4309__8246(.A1 (n_191), .A2 (n_161), .A3
       (n_158), .ZN (n_198));
  NR2SKPBD3BWP16P90LVT g4310__7098(.A1 (n_186), .A2 (n_170), .ZN
       (n_197));
  NR2SKPBD4BWP16P90LVT g4311__6131(.A1 (n_174), .A2 (n_187), .ZN
       (n_196));
  NR2SKPBD4BWP16P90LVT g4312__1881(.A1 (n_180), .A2 (n_175), .ZN
       (n_195));
  NR2SKPBD3BWP16P90LVT g4313__5115(.A1 (n_173), .A2 (n_185), .ZN
       (n_194));
  NR4SKPBD3BWP16P90LVT g4314__7482(.A1 (n_89), .A2 (n_61), .A3 (n_91),
       .A4 (n_62), .ZN (n_193));
  NR4SKPBD3BWP16P90LVT g4315__4733(.A1 (n_82), .A2 (n_98), .A3 (n_112),
       .A4 (n_99), .ZN (n_192));
  ND2SKNBD4BWP16P90LVT g4316__6161(.A1 (n_154), .A2 (n_141), .ZN
       (n_191));
  NR4SKPBD3BWP16P90LVT g4317__9315(.A1 (n_102), .A2 (n_86), .A3
       (n_104), .A4 (n_87), .ZN (n_190));
  ND2SKNBD3BWP16P90LVT g4318__9945(.A1 (n_148), .A2 (n_149), .ZN
       (n_189));
  NR4SKPBD3BWP16P90LVT g4319__2883(.A1 (n_85), .A2 (n_113), .A3 (n_95),
       .A4 (n_69), .ZN (n_188));
  ND2SKNBD4BWP16P90LVT g4320__2346(.A1 (n_151), .A2 (n_162), .ZN
       (n_187));
  ND2SKNBD3BWP16P90LVT g4321__1666(.A1 (n_140), .A2 (n_137), .ZN
       (n_186));
  ND2SKNBD2BWP16P90LVT g4322__7410(.A1 (n_133), .A2 (n_157), .ZN
       (n_185));
  ND2SKNBD3BWP16P90LVT g4323__6417(.A1 (n_138), .A2 (n_156), .ZN
       (n_184));
  ND2SKNBD3BWP16P90LVT g4324__5477(.A1 (n_159), .A2 (n_136), .ZN
       (n_183));
  NR4SKPBD3BWP16P90LVT g4325__2398(.A1 (n_109), .A2 (n_75), .A3 (n_64),
       .A4 (n_76), .ZN (n_182));
  NR4SKPBD2BWP16P90LVT g4326__5107(.A1 (n_103), .A2 (n_90), .A3 (n_60),
       .A4 (n_72), .ZN (n_181));
  ND2SKNBD3BWP16P90LVT g4327__6260(.A1 (n_155), .A2 (n_143), .ZN
       (n_180));
  NR4SKPBD3BWP16P90LVT g4328__4319(.A1 (n_101), .A2 (n_59), .A3 (n_70),
       .A4 (n_71), .ZN (n_179));
  NR4SKPBD3BWP16P90LVT g4329__8428(.A1 (n_110), .A2 (n_92), .A3
       (n_105), .A4 (n_80), .ZN (n_178));
  ND2SKNBD3BWP16P90LVT g4330__5526(.A1 (n_142), .A2 (n_135), .ZN
       (n_177));
  NR4SKPBD3BWP16P90LVT g4331__6783(.A1 (n_129), .A2 (n_96), .A3 (n_67),
       .A4 (n_78), .ZN (n_176));
  ND2SKNBD3BWP16P90LVT g4332__3680(.A1 (n_153), .A2 (n_164), .ZN
       (n_175));
  ND2SKNBD3BWP16P90LVT g4333__1617(.A1 (n_152), .A2 (n_134), .ZN
       (n_174));
  ND2SKNBD3BWP16P90LVT g4334__2802(.A1 (n_150), .A2 (n_131), .ZN
       (n_173));
  NR4SKPBD3BWP16P90LVT g4335__1705(.A1 (n_88), .A2 (n_106), .A3 (n_79),
       .A4 (n_73), .ZN (n_172));
  NR4SKPBD3BWP16P90LVT g4336__5122(.A1 (n_97), .A2 (n_83), .A3 (n_66),
       .A4 (n_77), .ZN (n_171));
  ND2SKNBD3BWP16P90LVT g4337__8246(.A1 (n_146), .A2 (n_163), .ZN
       (n_170));
  NR4SKPBD3BWP16P90LVT g4338__7098(.A1 (n_84), .A2 (n_100), .A3 (n_58),
       .A4 (n_68), .ZN (n_169));
  ND2SKNBD3BWP16P90LVT g4339__6131(.A1 (n_132), .A2 (n_147), .ZN
       (n_168));
  NR4SKPBD2BWP16P90LVT g4340__1881(.A1 (n_81), .A2 (n_94), .A3 (n_65),
       .A4 (n_93), .ZN (n_167));
  NR4SKPBD3BWP16P90LVT g4341__5115(.A1 (n_107), .A2 (n_108), .A3
       (n_63), .A4 (n_74), .ZN (n_166));
  NR2SKPBD1BWP16P90LVT g4342__7482(.A1 (n_203), .A2 (n_115), .ZN
       (n_217));
  NR2SKPBD2BWP16P90LVT g4343__4733(.A1 (n_203), .A2 (n_128), .ZN
       (n_215));
  CKNR2D2BWP16P90LVT g4344__6161(.A1 (n_203), .A2 (n_125), .ZN (n_228));
  CKNR2D2BWP16P90LVT g4346__9945(.A1 (n_203), .A2 (n_123), .ZN (n_226));
  NR2SKPBD1BWP16P90LVT g4348__2346(.A1 (n_203), .A2 (n_120), .ZN
       (n_224));
  NR2SKPBD1BWP16P90LVT g4349__1666(.A1 (n_203), .A2 (n_121), .ZN
       (n_223));
  CKNR2D2BWP16P90LVT g4350__7410(.A1 (n_203), .A2 (n_118), .ZN (n_222));
  NR2SKPD1BWP16P90LVT g4351__6417(.A1 (n_203), .A2 (n_119), .ZN
       (n_221));
  NR2SKPD1BWP16P90LVT g4352__5477(.A1 (n_203), .A2 (n_127), .ZN
       (n_220));
  CKNR2D2BWP16P90LVT g4353__2398(.A1 (n_203), .A2 (n_126), .ZN (n_216));
  CKNR2D2BWP16P90LVT g4354__5107(.A1 (n_203), .A2 (n_116), .ZN (n_214));
  NR2SKPBD2BWP16P90LVT g4355__6260(.A1 (n_203), .A2 (n_111), .ZN
       (n_219));
  CKNR2D2BWP16P90LVT g4356__4319(.A1 (n_203), .A2 (n_114), .ZN (n_213));
  NR2SKPBD2BWP16P90LVT g4357__8428(.A1 (n_203), .A2 (n_117), .ZN
       (n_218));
  OAI22SKND3BWP16P90 g4358__5526(.A1 (n_27), .A2 (\mem[0] [3]), .B1
       (\mem[6] [3]), .B2 (n_42), .ZN (n_165));
  AOI22SKPD4BWP16P90LVT g4359__6783(.A1 (\mem[0] [2]), .A2 (n_26), .B1
       (n_32), .B2 (\mem[2] [2]), .ZN (n_164));
  AOI22OPTPBD2BWP16P90LVT g4360__3680(.A1 (\mem[0] [7]), .A2 (n_26),
       .B1 (\mem[2] [7]), .B2 (n_32), .ZN (n_163));
  AOI22SKPD3BWP16P90LVT g4361__1617(.A1 (\mem[0] [1]), .A2 (n_26), .B1
       (n_44), .B2 (\mem[9] [1]), .ZN (n_162));
  OAI22SKND1BWP16P90LVT g4362__2802(.A1 (n_27), .A2 (\mem[0] [5]), .B1
       (\mem[2] [5]), .B2 (n_33), .ZN (n_161));
  OAI22SKND1BWP16P90LVT g4363__1705(.A1 (n_27), .A2 (\mem[0] [0]), .B1
       (\mem[7] [0]), .B2 (n_51), .ZN (n_160));
  AOI22OPTPBD2BWP16P90LVT g4364__5122(.A1 (n_26), .A2 (\mem[0] [6]),
       .B1 (\mem[10] [6]), .B2 (n_39), .ZN (n_159));
  OAI22D1BWP16P90LVT g4365__8246(.A1 (n_31), .A2 (\mem[8] [5]), .B1
       (\mem[4] [5]), .B2 (n_35), .ZN (n_158));
  AOI22SKPD3BWP16P90LVT g4366__7098(.A1 (\mem[4] [4]), .A2 (n_34), .B1
       (n_29), .B2 (\mem[1] [4]), .ZN (n_157));
  AOI22D3BWP16P90LVT g4367__6131(.A1 (n_34), .A2 (\mem[4] [0]), .B1
       (\mem[2] [0]), .B2 (n_32), .ZN (n_156));
  AOI22SKPD3BWP16P90LVT g4368__1881(.A1 (n_34), .A2 (\mem[4] [2]), .B1
       (\mem[6] [2]), .B2 (n_41), .ZN (n_155));
  AOI22SKPD3BWP16P90LVT g4369__5115(.A1 (\mem[6] [5]), .A2 (n_41), .B1
       (\mem[7] [5]), .B2 (n_52), .ZN (n_154));
  AOI22D3BWP16P90LVT g4370__7482(.A1 (\mem[3] [2]), .A2 (n_25), .B1
       (\mem[7] [2]), .B2 (n_52), .ZN (n_153));
  AOI22SKPD3BWP16P90LVT g4371__4733(.A1 (n_34), .A2 (\mem[4] [1]), .B1
       (\mem[14] [1]), .B2 (n_50), .ZN (n_152));
  AOI22SKPD3BWP16P90LVT g4372__6161(.A1 (n_32), .A2 (\mem[2] [1]), .B1
       (\mem[13] [1]), .B2 (n_48), .ZN (n_151));
  AOI22SKPD3BWP16P90LVT g4373__9315(.A1 (n_46), .A2 (\mem[11] [4]), .B1
       (\mem[7] [4]), .B2 (n_52), .ZN (n_150));
  AOI22SKPD4BWP16P90LVT g4374__9945(.A1 (\mem[9] [6]), .A2 (n_44), .B1
       (\mem[7] [6]), .B2 (n_52), .ZN (n_149));
  AOI22D2BWP16P90LVT g4375__2883(.A1 (n_32), .A2 (\mem[2] [6]), .B1
       (n_46), .B2 (\mem[11] [6]), .ZN (n_148));
  AOI22SKPD3BWP16P90LVT g4376__2346(.A1 (n_29), .A2 (\mem[1] [3]), .B1
       (\mem[14] [3]), .B2 (n_50), .ZN (n_147));
  AOI22SKPD4BWP16P90LVT g4377__1666(.A1 (n_34), .A2 (\mem[4] [7]), .B1
       (\mem[7] [7]), .B2 (n_52), .ZN (n_146));
  OAI22SKND3BWP16P90 g4378__7410(.A1 (n_49), .A2 (\mem[14] [5]), .B1
       (\mem[11] [5]), .B2 (n_45), .ZN (n_145));
  OAI22SKND1BWP16P90LVT g4379__6417(.A1 (n_23), .A2 (\mem[12] [5]), .B1
       (\mem[10] [5]), .B2 (n_38), .ZN (n_144));
  AOI22SKPD4BWP16P90LVT g4380__5477(.A1 (n_29), .A2 (\mem[1] [2]), .B1
       (\mem[5] [2]), .B2 (n_40), .ZN (n_143));
  AOI22SKPD3BWP16P90LVT g4381__2398(.A1 (n_29), .A2 (\mem[1] [5]), .B1
       (\mem[13] [5]), .B2 (n_48), .ZN (n_142));
  AOI22D3BWP16P90LVT g4382__5107(.A1 (\mem[3] [5]), .A2 (n_25), .B1
       (\mem[5] [5]), .B2 (n_40), .ZN (n_141));
  AOI22SKPD3BWP16P90LVT g4383__6260(.A1 (n_25), .A2 (\mem[3] [7]), .B1
       (\mem[5] [7]), .B2 (n_40), .ZN (n_140));
  OAI22SKND1BWP16P90LVT g4384__4319(.A1 (n_31), .A2 (\mem[8] [0]), .B1
       (\mem[6] [0]), .B2 (n_42), .ZN (n_139));
  AOI22SKPD4BWP16P90LVT g4385__8428(.A1 (\mem[10] [0]), .A2 (n_39), .B1
       (n_44), .B2 (\mem[9] [0]), .ZN (n_138));
  AOI22SKPD3BWP16P90LVT g4386__5526(.A1 (n_29), .A2 (\mem[1] [7]), .B1
       (\mem[6] [7]), .B2 (n_41), .ZN (n_137));
  AOI22SKPD4BWP16P90LVT g4387__6783(.A1 (\mem[8] [6]), .A2 (n_30), .B1
       (\mem[5] [6]), .B2 (n_40), .ZN (n_136));
  AOI22SKPD4BWP16P90LVT g4388__3680(.A1 (n_44), .A2 (\mem[9] [5]), .B1
       (\mem[15] [5]), .B2 (n_37), .ZN (n_135));
  AOI22SKPD4BWP16P90LVT g4389__1617(.A1 (n_46), .A2 (\mem[11] [1]), .B1
       (\mem[15] [1]), .B2 (n_37), .ZN (n_134));
  AOI22SKPD3BWP16P90LVT g4390__2802(.A1 (n_40), .A2 (\mem[5] [4]), .B1
       (\mem[15] [4]), .B2 (n_37), .ZN (n_133));
  AOI22SKPD3BWP16P90LVT g4391__1705(.A1 (\mem[5] [3]), .A2 (n_40), .B1
       (n_37), .B2 (\mem[15] [3]), .ZN (n_132));
  AOI22SKPD3BWP16P90LVT g4392__5122(.A1 (n_26), .A2 (\mem[0] [4]), .B1
       (\mem[3] [4]), .B2 (n_25), .ZN (n_131));
  OAI22SKND1BWP16P90LVT g4393__8246(.A1 (n_31), .A2 (\mem[8] [3]), .B1
       (n_23), .B2 (\mem[12] [3]), .ZN (n_130));
  NR2D1BWP16P90 g4394__7098(.A1 (\mem[10] [2]), .A2 (n_38), .ZN
       (n_129));
  ND3D0BWP16P90 g4395__6131(.A1 (waddr[2]), .A2 (n_54), .A3 (waddr[0]),
       .ZN (n_128));
  OR3D0BWP16P90 g4396__1881(.A1 (waddr[0]), .A2 (waddr[2]), .A3 (n_53),
       .Z (n_127));
  IND3D0BWP16P90 g4397__5115(.A1 (waddr[0]), .B1 (waddr[2]), .B2
       (n_54), .ZN (n_126));
  ND2D0BWP16P90 g4398__7482(.A1 (n_55), .A2 (n_20), .ZN (n_125));
  ND2D0BWP16P90 g4400__6161(.A1 (n_55), .A2 (n_6), .ZN (n_123));
  ND2D0BWP16P90 g4402__9945(.A1 (n_57), .A2 (n_19), .ZN (n_121));
  ND2D0BWP16P90 g4403__2883(.A1 (n_57), .A2 (n_20), .ZN (n_120));
  OR2D0BWP16P90 g4404__2346(.A1 (n_56), .A2 (n_8), .Z (n_119));
  ND2D0BWP16P90 g4405__1666(.A1 (n_57), .A2 (n_6), .ZN (n_118));
  IND3D0BWP16P90 g4406__7410(.A1 (waddr[2]), .B1 (n_1), .B2 (n_6), .ZN
       (n_117));
  ND3D0BWP16P90 g4407__6417(.A1 (n_1), .A2 (n_6), .A3 (waddr[2]), .ZN
       (n_116));
  OR3D0BWP16P90 g4408__5477(.A1 (waddr[2]), .A2 (n_0), .A3 (n_8), .Z
       (n_115));
  ND3D0BWP16P90 g4409__2398(.A1 (n_1), .A2 (n_7), .A3 (waddr[2]), .ZN
       (n_114));
  INR2D1BWP16P90 g4410__5107(.A1 (n_44), .B1 (\mem[9] [3]), .ZN
       (n_113));
  INR2OPTPBD2BWP16P90 g4411__6260(.A1 (n_44), .B1 (\mem[9] [2]), .ZN
       (n_112));
  IND3D0BWP16P90 g4412__4319(.A1 (waddr[2]), .B1 (waddr[0]), .B2
       (n_54), .ZN (n_111));
  NR2D0BWP16P90LVT g4413__8428(.A1 (\mem[10] [7]), .A2 (n_38), .ZN
       (n_110));
  INR2D1BWP16P90 g4414__5526(.A1 (n_40), .B1 (\mem[5] [1]), .ZN
       (n_109));
  NR2D1BWP16P90 g4415__6783(.A1 (\mem[6] [1]), .A2 (n_42), .ZN (n_108));
  NR2D0BWP16P90LVT g4416__3680(.A1 (\mem[10] [1]), .A2 (n_38), .ZN
       (n_107));
  INR2OPTPBD1BWP16P90 g4417__1617(.A1 (n_40), .B1 (\mem[5] [0]), .ZN
       (n_106));
  NR2D1BWP16P90LVT g4418__2802(.A1 (\mem[9] [7]), .A2 (n_43), .ZN
       (n_105));
  INR2D1BWP16P90 g4419__1705(.A1 (n_44), .B1 (\mem[9] [4]), .ZN
       (n_104));
  NR2D0P75BWP16P90 g4420__5122(.A1 (\mem[6] [6]), .A2 (n_42), .ZN
       (n_103));
  NR2D0BWP16P90LVT g4421__8246(.A1 (\mem[6] [4]), .A2 (n_42), .ZN
       (n_102));
  NR2D0BWP16P90LVT g4422__7098(.A1 (\mem[10] [4]), .A2 (n_38), .ZN
       (n_101));
  NR2OPTPBD1BWP16P90 g4423__6131(.A1 (\mem[10] [3]), .A2 (n_38), .ZN
       (n_100));
  NR2D1BWP16P90LVT g4424__1881(.A1 (\mem[11] [2]), .A2 (n_45), .ZN
       (n_99));
  INR2D1BWP16P90 g4425__5115(.A1 (n_48), .B1 (\mem[13] [2]), .ZN
       (n_98));
  NR2D0BWP16P90LVT g4426__7482(.A1 (n_49), .A2 (\mem[14] [7]), .ZN
       (n_97));
  NR2D0BWP16P90LVT g4427__4733(.A1 (\mem[14] [2]), .A2 (n_49), .ZN
       (n_96));
  INR2D1BWP16P90 g4428__6161(.A1 (n_48), .B1 (\mem[13] [3]), .ZN
       (n_95));
  NR2D0P75BWP16P90LVT g4429__9315(.A1 (\mem[13] [6]), .A2 (n_47), .ZN
       (n_94));
  INR2D1BWP16P90LVT g4430__9945(.A1 (n_29), .B1 (\mem[1] [6]), .ZN
       (n_93));
  NR2D1BWP16P90 g4431__2883(.A1 (\mem[13] [7]), .A2 (n_47), .ZN (n_92));
  NR2D2BWP16P90 g4432__2346(.A1 (\mem[11] [0]), .A2 (n_45), .ZN (n_91));
  NR2D1BWP16P90 g4433__1666(.A1 (\mem[14] [6]), .A2 (n_49), .ZN (n_90));
  NR2D1BWP16P90 g4434__7410(.A1 (\mem[14] [0]), .A2 (n_49), .ZN (n_89));
  NR2D0P75BWP16P90 g4435__6417(.A1 (n_47), .A2 (\mem[13] [0]), .ZN
       (n_88));
  NR2D0P75BWP16P90LVT g4436__5477(.A1 (\mem[14] [4]), .A2 (n_49), .ZN
       (n_87));
  NR2D1BWP16P90 g4437__2398(.A1 (\mem[13] [4]), .A2 (n_47), .ZN (n_86));
  NR2D0BWP16P90LVT g4438__5107(.A1 (\mem[7] [3]), .A2 (n_51), .ZN
       (n_85));
  NR2D1BWP16P90 g4439__6260(.A1 (n_45), .A2 (\mem[11] [3]), .ZN (n_84));
  NR2D1BWP16P90 g4440__4319(.A1 (\mem[11] [7]), .A2 (n_45), .ZN (n_83));
  NR2D1BWP16P90 g4441__8428(.A1 (n_36), .A2 (\mem[15] [2]), .ZN (n_82));
  NR2D1BWP16P90LVT g4442__5526(.A1 (\mem[15] [6]), .A2 (n_36), .ZN
       (n_81));
  INR2D1BWP16P90LVT g4443__6783(.A1 (n_37), .B1 (\mem[15] [7]), .ZN
       (n_80));
  INR2OPTPBD2BWP16P90 g4444__3680(.A1 (n_37), .B1 (\mem[15] [0]), .ZN
       (n_79));
  NR2D2BWP16P90 g4445__1617(.A1 (\mem[8] [2]), .A2 (n_31), .ZN (n_78));
  NR2D1BWP16P90LVT g4446__2802(.A1 (\mem[8] [7]), .A2 (n_31), .ZN
       (n_77));
  NR2D1BWP16P90LVT g4447__1705(.A1 (\mem[1] [1]), .A2 (n_28), .ZN
       (n_76));
  NR2D1BWP16P90 g4448__5122(.A1 (\mem[7] [1]), .A2 (n_51), .ZN (n_75));
  NR2D2BWP16P90 g4449__8246(.A1 (\mem[8] [1]), .A2 (n_31), .ZN (n_74));
  INR2OPTPBD2BWP16P90 g4450__7098(.A1 (n_29), .B1 (\mem[1] [0]), .ZN
       (n_73));
  NR2D2BWP16P90LVT g4451__6131(.A1 (\mem[4] [6]), .A2 (n_35), .ZN
       (n_72));
  NR2D2BWP16P90LVT g4452__1881(.A1 (\mem[2] [4]), .A2 (n_33), .ZN
       (n_71));
  NR2D1BWP16P90LVT g4453__5115(.A1 (\mem[8] [4]), .A2 (n_31), .ZN
       (n_70));
  NR2D1BWP16P90LVT g4454__7482(.A1 (\mem[2] [3]), .A2 (n_33), .ZN
       (n_69));
  NR2D2BWP16P90LVT g4455__4733(.A1 (\mem[4] [3]), .A2 (n_35), .ZN
       (n_68));
  NR2D2BWP16P90 g4456__6161(.A1 (\mem[12] [2]), .A2 (n_23), .ZN (n_67));
  NR2D0P75BWP16P90LVT g4457__9315(.A1 (\mem[12] [7]), .A2 (n_23), .ZN
       (n_66));
  NR2D2BWP16P90LVT g4458__9945(.A1 (\mem[12] [6]), .A2 (n_23), .ZN
       (n_65));
  NR2D0P75BWP16P90LVT g4459__2883(.A1 (\mem[3] [1]), .A2 (n_24), .ZN
       (n_64));
  NR2D2BWP16P90 g4460__2346(.A1 (\mem[12] [1]), .A2 (n_23), .ZN (n_63));
  INR2OPTPBD2BWP16P90LVT g4461__1666(.A1 (n_25), .B1 (\mem[3] [0]), .ZN
       (n_62));
  NR2D2BWP16P90 g4462__7410(.A1 (\mem[12] [0]), .A2 (n_23), .ZN (n_61));
  NR2D1BWP16P90LVT g4463__6417(.A1 (\mem[3] [6]), .A2 (n_24), .ZN
       (n_60));
  NR2D1BWP16P90LVT g4464__5477(.A1 (\mem[12] [4]), .A2 (n_23), .ZN
       (n_59));
  NR2D2BWP16P90 g4465__2398(.A1 (\mem[3] [3]), .A2 (n_24), .ZN (n_58));
  INVD0BWP16P90 g4466(.I (n_57), .ZN (n_56));
  INVD0BWP16P90 g4467(.I (n_54), .ZN (n_53));
  CKND1BWP16P90 g4468(.I (n_52), .ZN (n_51));
  CKND1BWP16P90 g4469(.I (n_50), .ZN (n_49));
  CKND1BWP16P90 g4470(.I (n_48), .ZN (n_47));
  CKND1BWP16P90 g4471(.I (n_46), .ZN (n_45));
  INVSKPD2BWP16P90 g4472(.I (n_43), .ZN (n_44));
  CKND1BWP16P90 g4473(.I (n_42), .ZN (n_41));
  AN2D0BWP16P90 g4474__5107(.A1 (n_21), .A2 (waddr[2]), .Z (n_57));
  NR2D0BWP16P90 g4475__6260(.A1 (n_22), .A2 (waddr[2]), .ZN (n_55));
  NR2D0BWP16P90 g4476__4319(.A1 (n_0), .A2 (waddr[1]), .ZN (n_54));
  NR2D1BWP16P90 g4477__8428(.A1 (n_17), .A2 (n_16), .ZN (n_52));
  NR2D0BWP16P90 g4478__5526(.A1 (n_14), .A2 (n_9), .ZN (n_50));
  NR2D1BWP16P90 g4479__6783(.A1 (n_12), .A2 (n_9), .ZN (n_48));
  NR2SKPD0P75BWP16P90 g4480__3680(.A1 (n_10), .A2 (n_16), .ZN (n_46));
  ND2D0BWP16P90 g4481__1617(.A1 (n_13), .A2 (n_11), .ZN (n_43));
  ND2SKND1BWP16P90 g4482__2802(.A1 (n_15), .A2 (n_18), .ZN (n_42));
  INVSKND2BWP16P90 g4483(.I (n_39), .ZN (n_38));
  CKND1BWP16P90 g4484(.I (n_37), .ZN (n_36));
  INVSKND2BWP16P90 g4485(.I (n_35), .ZN (n_34));
  INVSKPD2BWP16P90 g4486(.I (n_33), .ZN (n_32));
  INVSKND0P75BWP16P90 g4487(.I (n_31), .ZN (n_30));
  INVSKND2BWP16P90 g4488(.I (n_28), .ZN (n_29));
  INVSKND2BWP16P90 g4489(.I (n_27), .ZN (n_26));
  CKND1BWP16P90 g4490(.I (n_25), .ZN (n_24));
  AN2D2BWP16P90 g4491__1705(.A1 (n_13), .A2 (n_18), .Z (n_40));
  NR2D0BWP16P90 g4492__5122(.A1 (n_14), .A2 (n_10), .ZN (n_39));
  NR2D2BWP16P90 g4493__8246(.A1 (n_16), .A2 (n_9), .ZN (n_37));
  ND2D0BWP16P90 g4494__7098(.A1 (n_3), .A2 (n_18), .ZN (n_35));
  ND2SKND0P75BWP16P90 g4495__6131(.A1 (n_5), .A2 (n_15), .ZN (n_33));
  ND2D1BWP16P90 g4496__1881(.A1 (n_3), .A2 (n_11), .ZN (n_31));
  ND2D0BWP16P90 g4497__5115(.A1 (n_13), .A2 (n_5), .ZN (n_28));
  ND2SKND0P75BWP16P90 g4498__7482(.A1 (n_3), .A2 (n_5), .ZN (n_27));
  NR2D1BWP16P90 g4499__4733(.A1 (n_4), .A2 (n_16), .ZN (n_25));
  OR2D0P75BWP16P90 g4500__6161(.A1 (n_9), .A2 (n_2), .Z (n_23));
  INVD0BWP16P90 g4501(.I (n_21), .ZN (n_22));
  INVD0BWP16P90 g4502(.I (n_18), .ZN (n_17));
  INVD0BWP16P90 g4503(.I (n_15), .ZN (n_14));
  INVD0BWP16P90 g4504(.I (n_13), .ZN (n_12));
  INVD0BWP16P90 g4505(.I (n_11), .ZN (n_10));
  INVD0BWP16P90 g4506(.I (n_8), .ZN (n_7));
  INVD0BWP16P90 g4507(.I (n_5), .ZN (n_4));
  INVD0BWP16P90 g4508(.I (n_3), .ZN (n_2));
  INVD0BWP16P90 g4509(.I (n_1), .ZN (n_0));
  NR2D0BWP16P90 g4567__9315(.A1 (waddr[3]), .A2 (wfull), .ZN (n_21));
  NR2D0BWP16P90 g4568__9945(.A1 (waddr[1]), .A2 (waddr[0]), .ZN (n_20));
  INR2D0BWP16P90 g4569__2883(.A1 (waddr[0]), .B1 (waddr[1]), .ZN
       (n_19));
  INR2D0BWP16P90 g4570__2346(.A1 (raddr[2]), .B1 (raddr[3]), .ZN
       (n_18));
  ND2D0BWP16P90 g4571__1666(.A1 (raddr[1]), .A2 (raddr[0]), .ZN (n_16));
  INR2D0BWP16P90 g4572__7410(.A1 (raddr[1]), .B1 (raddr[0]), .ZN
       (n_15));
  INR2D0BWP16P90 g4573__6417(.A1 (raddr[0]), .B1 (raddr[1]), .ZN
       (n_13));
  INR2D0BWP16P90 g4574__5477(.A1 (raddr[3]), .B1 (raddr[2]), .ZN
       (n_11));
  ND2D0BWP16P90 g4575__2398(.A1 (raddr[3]), .A2 (raddr[2]), .ZN (n_9));
  ND2D0BWP16P90 g4576__5107(.A1 (waddr[1]), .A2 (waddr[0]), .ZN (n_8));
  INR2D0BWP16P90 g4577__6260(.A1 (waddr[1]), .B1 (waddr[0]), .ZN (n_6));
  NR2D0BWP16P90 g4578__4319(.A1 (raddr[2]), .A2 (raddr[3]), .ZN (n_5));
  NR2D0BWP16P90 g4579__8428(.A1 (raddr[0]), .A2 (raddr[1]), .ZN (n_3));
  INR2D0BWP16P90 g4580__5526(.A1 (waddr[3]), .B1 (wfull), .ZN (n_1));
  IINR3D2BWP16P90LVT g2(.A1 (n_55), .A2 (n_19), .B1 (n_203), .ZN
       (n_240));
  IINR3D2BWP16P90LVT g4652(.A1 (n_55), .A2 (n_7), .B1 (n_203), .ZN
       (n_241));
endmodule

module rptr_empty_ADDRSIZE4(rclk, rrst_n, rinc, rq2_wptr, rempty,
     arempty, raddr, rptr);
  input rclk, rrst_n, rinc;
  input [4:0] rq2_wptr;
  output rempty, arempty;
  output [3:0] raddr;
  output [4:0] rptr;
  wire rclk, rrst_n, rinc;
  wire [4:0] rq2_wptr;
  wire rempty, arempty;
  wire [3:0] raddr;
  wire [4:0] rptr;
  wire [4:0] rgraynext;
  wire [4:0] rbinnext;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  DFCNQD0BWP16P90 \rptr_reg[3] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[3]), .Q (rptr[3]));
  XOR2D0BWP16P90 g259__6783(.A1 (rbinnext[3]), .A2 (rbinnext[4]), .Z
       (rgraynext[3]));
  DFCNQD0BWP16P90 \rptr_reg[2] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[2]), .Q (rptr[2]));
  XOR2D0BWP16P90 g261__3680(.A1 (rbinnext[2]), .A2 (rbinnext[3]), .Z
       (rgraynext[2]));
  XOR2D0BWP16P90 g262__1617(.A1 (rptr[4]), .A2 (n_11), .Z
       (rbinnext[4]));
  HA1D0BWP16P90 g263__2802(.A (raddr[3]), .B (n_10), .CO (n_11), .S
       (rbinnext[3]));
  DFCNQD0BWP16P90 \rptr_reg[1] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[1]), .Q (rptr[1]));
  XOR2D0BWP16P90 g265__1705(.A1 (rbinnext[1]), .A2 (rbinnext[2]), .Z
       (rgraynext[1]));
  HA1D0BWP16P90 g266__5122(.A (raddr[2]), .B (n_9), .CO (n_10), .S
       (rbinnext[2]));
  DFCNQD0BWP16P90 \rptr_reg[0] (.CDN (rrst_n), .CP (rclk), .D
       (rgraynext[0]), .Q (rptr[0]));
  XOR2D0BWP16P90 g268__8246(.A1 (rbinnext[0]), .A2 (rbinnext[1]), .Z
       (rgraynext[0]));
  HA1D0BWP16P90 g269__7098(.A (raddr[1]), .B (n_8), .CO (n_9), .S
       (rbinnext[1]));
  HA1D0BWP16P90 g270__6131(.A (raddr[0]), .B (n_7), .CO (n_8), .S
       (rbinnext[0]));
  INR2D0BWP16P90 g271__1881(.A1 (rinc), .B1 (rempty), .ZN (n_7));
  DFSNQD0BWP16P90 rempty_reg(.SDN (rrst_n), .CP (rclk), .D (n_6), .Q
       (rempty));
  NR4D0BWP16P90 g294__5115(.A1 (n_5), .A2 (n_4), .A3 (n_2), .A4 (n_1),
       .ZN (n_6));
  ND2D0BWP16P90 g295__7482(.A1 (n_3), .A2 (n_0), .ZN (n_5));
  XOR2D0BWP16P90 g296__4733(.A1 (rq2_wptr[3]), .A2 (rgraynext[3]), .Z
       (n_4));
  XNR2D0BWP16P90 g297__6161(.A1 (rq2_wptr[2]), .A2 (rgraynext[2]), .ZN
       (n_3));
  XOR2D0BWP16P90 g298__9315(.A1 (rq2_wptr[4]), .A2 (rbinnext[4]), .Z
       (n_2));
  XOR2D0BWP16P90 g299__9945(.A1 (rq2_wptr[1]), .A2 (rgraynext[1]), .Z
       (n_1));
  XNR2D0BWP16P90 g300__2883(.A1 (rq2_wptr[0]), .A2 (rgraynext[0]), .ZN
       (n_0));
  DFCNQD0BWP16P90 \rbin_reg[1] (.CDN (rrst_n), .CP (rclk), .D
       (rbinnext[1]), .Q (raddr[1]));
  DFCNQD0BWP16P90 \rbin_reg[2] (.CDN (rrst_n), .CP (rclk), .D
       (rbinnext[2]), .Q (raddr[2]));
  DFCNQD0BWP16P90 \rbin_reg[3] (.CDN (rrst_n), .CP (rclk), .D
       (rbinnext[3]), .Q (raddr[3]));
  DFCNQD0BWP16P90 \rbin_reg[4] (.CDN (rrst_n), .CP (rclk), .D
       (rbinnext[4]), .Q (rptr[4]));
  DFCNQD0BWP16P90 \rbin_reg[0] (.CDN (rrst_n), .CP (rclk), .D
       (rbinnext[0]), .Q (raddr[0]));
endmodule

module RC_CG_MOD_56(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  CKLNQOPTBBD2BWP16P90LVT RC_CGIC_INST(.E (enable), .CP (ck_in), .TE
       (test), .Q (ck_out));
endmodule

module wptr_full_ADDRSIZE4(wclk, wrst_n, winc, wq2_rptr, wfull, awfull,
     waddr, wptr);
  input wclk, wrst_n, winc;
  input [4:0] wq2_rptr;
  output wfull, awfull;
  output [3:0] waddr;
  output [4:0] wptr;
  wire wclk, wrst_n, winc;
  wire [4:0] wq2_rptr;
  wire wfull, awfull;
  wire [3:0] waddr;
  wire [4:0] wptr;
  wire [4:0] wbin;
  wire [4:0] wbinnext;
  wire [4:0] wgraynext;
  wire n_0, n_1, n_2, n_3, n_4, n_7, n_9, n_10;
  wire n_11, n_12, n_14, n_16, n_17, n_18, n_19, n_20;
  wire n_24, n_26, n_27, n_28, n_29, n_35, n_45, n_47;
  wire n_48, n_49, n_50, n_51, n_52, rc_gclk;
  RC_CG_MOD_56 RC_CG_HIER_INST16(.enable (n_35), .ck_in (wclk), .ck_out
       (rc_gclk), .test (1'b0));
  BUFFD0BWP16P90 g774(.I (wbin[0]), .Z (waddr[0]));
  CKXOR2D4BWP16P90LVT g1092__2346(.A1 (wbinnext[4]), .A2 (n_49), .Z
       (wgraynext[3]));
  IOAI21D4BWP16P90LVT g1094__1666(.A1 (n_27), .A2 (wptr[4]), .B (n_29),
       .ZN (wbinnext[4]));
  ND4SKND2BWP16P90LVT g1095__7410(.A1 (winc), .A2 (n_24), .A3 (n_17),
       .A4 (waddr[3]), .ZN (n_29));
  XOR2D4BWP16P90LVT g1098__6417(.A1 (n_52), .A2 (wbinnext[0]), .Z
       (wgraynext[0]));
  ND3SKND2BWP16P90LVT g1102__2398(.A1 (winc), .A2 (n_24), .A3 (n_16),
       .ZN (n_28));
  NR3SKPD3BWP16P90LVT g1103__5107(.A1 (n_50), .A2 (n_51), .A3 (n_16),
       .ZN (n_27));
  ND3OPTPAD2BWP16P90LVT g1106__4319(.A1 (winc), .A2 (n_20), .A3 (n_12),
       .ZN (n_26));
  IOA22D4BWP16P90LVT g1108__5526(.A1 (wbin[0]), .A2 (n_19), .B1
       (wbin[0]), .B2 (n_19), .ZN (wbinnext[0]));
  AN2D0BWP16P90 g1111__3680(.A1 (n_20), .A2 (waddr[2]), .Z (n_24));
  AN2D0BWP16P90 g1113__2802(.A1 (n_18), .A2 (waddr[1]), .Z (n_20));
  INVSKPD4BWP16P90 g1114(.I (n_19), .ZN (n_35));
  ND2OPTPBD6BWP16P90LVT g1115__1705(.A1 (winc), .A2 (n_14), .ZN (n_19));
  AN2D0BWP16P90 g1116__5122(.A1 (wbin[0]), .A2 (n_14), .Z (n_18));
  INVSKPD0P75BWP16P90 g1117(.I (wptr[4]), .ZN (n_17));
  INVSKND0P75BWP16P90 g1118(.I (waddr[3]), .ZN (n_16));
  INVD0P75BWP16P90 g1120(.I (wfull), .ZN (n_14));
  INVSKND0P75BWP16P90 g1122(.I (waddr[2]), .ZN (n_12));
  XOR2D8BWP16P90LVT g2__8246(.A1 (n_52), .A2 (wbinnext[2]), .Z
       (wgraynext[1]));
  AOAI211D4BWP16P90LVT g1124__7098(.A1 (winc), .A2 (n_20), .B (n_12),
       .C (n_26), .ZN (wbinnext[2]));
  XOR2D4BWP16P90LVT g1125__6131(.A1 (n_49), .A2 (wbinnext[2]), .Z
       (wgraynext[2]));
  DFCNQD2BWP16P90LVT wfull_reg(.CDN (wrst_n), .CP (wclk), .D (n_11), .Q
       (wfull));
  NR4SKPBD3BWP16P90LVT g1096__1881(.A1 (n_9), .A2 (n_10), .A3 (n_3),
       .A4 (n_0), .ZN (n_11));
  ND3SKNBD3BWP16P90LVT g1097__5115(.A1 (n_1), .A2 (n_2), .A3 (n_7), .ZN
       (n_10));
  MOAI22D4BWP16P90LVT g1126__7482(.A1 (wgraynext[3]), .A2
       (wq2_rptr[3]), .B1 (wgraynext[3]), .B2 (wq2_rptr[3]), .ZN (n_9));
  ND2D1P5BWP16P90LVT g1127__6161(.A1 (wgraynext[1]), .A2 (n_4), .ZN
       (n_7));
  DFCNQD1BWP16P90LVT \wbin_reg[0] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[0]), .Q (wbin[0]));
  DFCNQD1BWP16P90LVT \wbin_reg[2] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[2]), .Q (waddr[2]));
  DFCNQD4BWP16P90LVT \wbin_reg[3] (.CDN (wrst_n), .CP (rc_gclk), .D
       (n_49), .Q (waddr[3]));
  DFCNQD0BWP16P90LVT \wbin_reg[4] (.CDN (wrst_n), .CP (rc_gclk), .D
       (wbinnext[4]), .Q (wptr[4]));
  DFCNQD1BWP16P90LVT \wbin_reg[1] (.CDN (wrst_n), .CP (rc_gclk), .D
       (n_52), .Q (waddr[1]));
  INVD0BWP16P90 g1130(.I (wq2_rptr[1]), .ZN (n_4));
  XOR2D8BWP16P90LVT g1131__9945(.A1 (wgraynext[2]), .A2 (wq2_rptr[2]),
       .Z (n_3));
  IND2D2BWP16P90LVT g1132__2883(.A1 (wq2_rptr[0]), .B1 (wgraynext[0]),
       .ZN (n_2));
  IND2D4BWP16P90LVT g1133__2346(.A1 (wgraynext[1]), .B1 (wq2_rptr[1]),
       .ZN (n_1));
  IOAI21D1BWP16P90LVT g1134__1666(.A1 (wgraynext[0]), .A2
       (wq2_rptr[0]), .B (n_47), .ZN (n_0));
  DFCNQD1BWP16P90LVT \wptr_reg[0] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[0]), .Q (wptr[0]));
  DFCNQD1BWP16P90LVT \wptr_reg[3] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[3]), .Q (wptr[3]));
  DFCNQD0BWP16P90 \wptr_reg[1] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[1]), .Q (wptr[1]));
  DFCNQD0BWP16P90 \wptr_reg[2] (.CDN (wrst_n), .CP (wclk), .D
       (wgraynext[2]), .Q (wptr[2]));
  ND2SKNBD4BWP16P90LVT g3(.A1 (winc), .A2 (n_18), .ZN (n_45));
  CKXOR2D1BWP16P90LVT g1136(.A1 (wbinnext[4]), .A2 (wq2_rptr[4]), .Z
       (n_47));
  ND2D4BWP16P90LVT g1137(.A1 (n_48), .A2 (n_28), .ZN (n_49));
  IOA21D4BWP16P90LVT g1138(.A1 (winc), .A2 (n_24), .B (waddr[3]), .ZN
       (n_48));
  INVSKND2BWP16P90LVT g1139(.I (winc), .ZN (n_50));
  CKND1BWP16P90 g1140(.I (n_24), .ZN (n_51));
  XNR2D8BWP16P90LVT g1141(.A1 (n_45), .A2 (waddr[1]), .ZN (n_52));
endmodule

module ipr(w_clk, w_rst_n, r_clk, r_rst_n, error_flag, read_if_req,
     read_if_addr, read_if_be, read_if_we, read_if_gnt, read_if_rvalid,
     read_if_rdata, write_if_req, write_if_addr, write_if_wdata,
     write_if_we, write_if_be, write_if_gnt, write_if_rvalid,
     write_if_rdata);
  input w_clk, w_rst_n, r_clk, r_rst_n, read_if_req, read_if_we,
       write_if_req, write_if_we;
  input [31:0] read_if_addr, write_if_addr, write_if_wdata;
  input [3:0] read_if_be, write_if_be;
  output error_flag, read_if_gnt, read_if_rvalid, write_if_gnt,
       write_if_rvalid;
  output [31:0] read_if_rdata, write_if_rdata;
  wire w_clk, w_rst_n, r_clk, r_rst_n, read_if_req, read_if_we,
       write_if_req, write_if_we;
  wire [31:0] read_if_addr, write_if_addr, write_if_wdata;
  wire [3:0] read_if_be, write_if_be;
  wire error_flag, read_if_gnt, read_if_rvalid, write_if_gnt,
       write_if_rvalid;
  wire [31:0] read_if_rdata, write_if_rdata;
  wire [3:0] async_fifo_i_waddr;
  wire [3:0] async_fifo_i_raddr;
  wire [4:0] async_fifo_i_rq2_wptr;
  wire [4:0] async_fifo_i_rptr;
  wire [4:0] async_fifo_i_wq2_rptr;
  wire [4:0] async_fifo_i_wptr;
  wire [4:0] async_fifo_i_sync_r2w_inst_wq1_rptr;
  wire [4:0] async_fifo_i_sync_w2r_inst_rq1_wptr;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, async_fifo_i_n_16,
       async_fifo_i_n_26, fifo_empty, fifo_full, n_41, n_45;
  wire n_47, n_52, n_53, re, we;
  assign write_if_rdata[0] = 1'b0;
  assign write_if_rdata[1] = 1'b0;
  assign write_if_rdata[2] = 1'b0;
  assign write_if_rdata[3] = 1'b0;
  assign write_if_rdata[4] = 1'b0;
  assign write_if_rdata[5] = 1'b0;
  assign write_if_rdata[6] = 1'b0;
  assign write_if_rdata[7] = 1'b0;
  assign write_if_rdata[8] = 1'b0;
  assign write_if_rdata[9] = 1'b0;
  assign write_if_rdata[10] = 1'b0;
  assign write_if_rdata[11] = 1'b0;
  assign write_if_rdata[12] = 1'b0;
  assign write_if_rdata[13] = 1'b0;
  assign write_if_rdata[14] = 1'b0;
  assign write_if_rdata[15] = 1'b0;
  assign write_if_rdata[16] = 1'b0;
  assign write_if_rdata[17] = 1'b0;
  assign write_if_rdata[18] = 1'b0;
  assign write_if_rdata[19] = 1'b0;
  assign write_if_rdata[20] = 1'b0;
  assign write_if_rdata[21] = 1'b0;
  assign write_if_rdata[22] = 1'b0;
  assign write_if_rdata[23] = 1'b0;
  assign write_if_rdata[24] = 1'b0;
  assign write_if_rdata[25] = 1'b0;
  assign write_if_rdata[26] = 1'b0;
  assign write_if_rdata[27] = 1'b0;
  assign write_if_rdata[28] = 1'b0;
  assign write_if_rdata[29] = 1'b0;
  assign write_if_rdata[30] = 1'b0;
  assign write_if_rdata[31] = 1'b0;
  assign read_if_rdata[8] = 1'b0;
  assign read_if_rdata[9] = 1'b0;
  assign read_if_rdata[10] = 1'b0;
  assign read_if_rdata[11] = 1'b0;
  assign read_if_rdata[12] = 1'b0;
  assign read_if_rdata[13] = 1'b0;
  assign read_if_rdata[14] = 1'b0;
  assign read_if_rdata[15] = 1'b0;
  assign read_if_rdata[16] = 1'b0;
  assign read_if_rdata[17] = 1'b0;
  assign read_if_rdata[18] = 1'b0;
  assign read_if_rdata[19] = 1'b0;
  assign read_if_rdata[20] = 1'b0;
  assign read_if_rdata[21] = 1'b0;
  assign read_if_rdata[22] = 1'b0;
  assign read_if_rdata[23] = 1'b0;
  assign read_if_rdata[24] = 1'b0;
  assign read_if_rdata[25] = 1'b0;
  assign read_if_rdata[26] = 1'b0;
  assign read_if_rdata[27] = 1'b0;
  assign read_if_rdata[28] = 1'b0;
  assign read_if_rdata[29] = 1'b0;
  assign read_if_rdata[30] = 1'b0;
  assign read_if_rdata[31] = 1'b0;
  assign error_flag = 1'b0;
  fifomem_DATASIZE8_ADDRSIZE4_FALLTHROUGH1
       async_fifo_i_fifomem_inst(.wclk (w_clk), .wclken (we), .waddr
       (async_fifo_i_waddr), .wdata (write_if_wdata[7:0]), .wfull
       (fifo_full), .rclk (UNCONNECTED_HIER_Z), .rclken
       (UNCONNECTED_HIER_Z0), .raddr (async_fifo_i_raddr), .rdata
       (read_if_rdata[7:0]));
  rptr_empty_ADDRSIZE4 async_fifo_i_rptr_empty_inst(.rclk (r_clk),
       .rrst_n (r_rst_n), .rinc (re), .rq2_wptr
       (async_fifo_i_rq2_wptr), .rempty (fifo_empty), .arempty
       (async_fifo_i_n_26), .raddr (async_fifo_i_raddr), .rptr
       (async_fifo_i_rptr));
  wptr_full_ADDRSIZE4 async_fifo_i_wptr_full_inst(.wclk (w_clk),
       .wrst_n (w_rst_n), .winc (we), .wq2_rptr
       (async_fifo_i_wq2_rptr), .wfull (fifo_full), .awfull
       (async_fifo_i_n_16), .waddr (async_fifo_i_waddr), .wptr
       (async_fifo_i_wptr));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[4] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[4]), .Q
       (async_fifo_i_wq2_rptr[4]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[3] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[3]), .Q
       (async_fifo_i_wq2_rptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[2] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[2]), .Q
       (async_fifo_i_wq2_rptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[1] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[1]), .Q
       (async_fifo_i_wq2_rptr[1]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[1] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[1]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[1]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[2] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[2]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[3] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[3]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq2_rptr_reg[0] (.CDN
       (w_rst_n), .CP (w_clk), .D
       (async_fifo_i_sync_r2w_inst_wq1_rptr[0]), .Q
       (async_fifo_i_wq2_rptr[0]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[4] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[4]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[4]));
  NR2OPTPBD16BWP16P90LVT g269__6417(.A1 (n_53), .A2 (n_41), .ZN (we));
  INR3D0BWP16P90 g224__2398(.A1 (read_if_rvalid), .B1
       (read_if_addr[2]), .B2 (read_if_addr[3]), .ZN (re));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[4] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[4]), .Q
       (async_fifo_i_rq2_wptr[4]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[3] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[3]), .Q
       (async_fifo_i_rq2_wptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[2] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[2]), .Q
       (async_fifo_i_rq2_wptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[1] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[1]), .Q
       (async_fifo_i_rq2_wptr[1]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq2_wptr_reg[0] (.CDN
       (r_rst_n), .CP (r_clk), .D
       (async_fifo_i_sync_w2r_inst_rq1_wptr[0]), .Q
       (async_fifo_i_rq2_wptr[0]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[2] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[2]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[2]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[1] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[1]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[1]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[0] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[0]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[0]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[4] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[4]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[4]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_w2r_inst_rq1_wptr_reg[3] (.CDN
       (r_rst_n), .CP (r_clk), .D (async_fifo_i_wptr[3]), .Q
       (async_fifo_i_sync_w2r_inst_rq1_wptr[3]));
  DFCNQD0BWP16P90 \async_fifo_i_sync_r2w_inst_wq1_rptr_reg[0] (.CDN
       (w_rst_n), .CP (w_clk), .D (async_fifo_i_rptr[0]), .Q
       (async_fifo_i_sync_r2w_inst_wq1_rptr[0]));
  DFCNQD4BWP16P90 write_gnt_dly_reg(.CDN (w_rst_n), .CP (w_clk), .D
       (write_if_gnt), .Q (write_if_rvalid));
  DFCNQD0BWP16P90 read_gnt_dly_reg(.CDN (r_rst_n), .CP (r_clk), .D
       (read_if_gnt), .Q (read_if_rvalid));
  INVSKND18BWP16P90LVT g178_0(.I (write_if_req), .ZN (n_41));
  NR3SKPBD6BWP16P90LVT g2(.A1 (n_45), .A2 (write_if_rvalid), .A3
       (n_52), .ZN (write_if_gnt));
  IND2OPTPBD12BWP16P90LVT g3(.A1 (fifo_full), .B1 (write_if_req), .ZN
       (n_45));
  NR3SKPBD6BWP16P90LVT g276(.A1 (n_47), .A2 (read_if_we), .A3
       (read_if_rvalid), .ZN (read_if_gnt));
  IND2OPTPBD12BWP16P90LVT g277(.A1 (fifo_empty), .B1 (read_if_req), .ZN
       (n_47));
  INVSKND16BWP16P90LVT g279(.I (write_if_we), .ZN (n_52));
  CKND18BWP16P90 g177_1(.I (write_if_we), .ZN (n_53));
endmodule

