PULP_APP = test
PULP_APP_FC_SRCS = test.c
PULP_APP_HOST_SRCS = test.c
PULP_CFLAGS = -O3 -g
#PULP_CFLAGS = -O2 -finline-functions
#PULP_CFLAGS = -O3 -finline-functions -fno-inline-functions-called-once
include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
